### ISSUE TITLE
Just installed FSPowerTools, lost all my F# env settings in Vstudio

### ISSUE THREAD

**Issue by antogh** [fsprojects/VisualFSharpPowerTools#1005]
Hi, I'm new to F# and Vstudio extensions, so I don't know if having more experience could avoid this issue, anyway I thought it could be useful to report it.

As I finished to install the power tools all of my settings I made in Vstudio about F# environment (font and color for many F# items) have been lost and reset to default, so I had to redo every custom setting in Vstudio again, that took me half an hour. 
My  fault I didn't save settings after many changes, I wil do it now. 

Also true that Vstudio way to change env settings could be much improved, instead of manually browsing long list of ui elements to find the one you want and change it, you could just point and click in the IDE the element you want to change and have it automatically selected in the list, that's more a Vstudio issue or maybe could be, if possible,  a new feature to implement in power tools. Also the ability to make a single change common to a group of items would be a nice feature (e.g. same color for  methods, values and types) instead of repeating ourself going one by one manually trhough the long list setting the same value over and over again.

**Comment by dungpa** [comment]
Sorry that you experience the issue.

AFAIK we don't touch any of these settings inside Visual Studio. Perhaps for now, it's better to use 'Tools -> Import and Export Settings" to avoid the problem.

**Comment by dungpa** [comment]
There's nothing to do here. Please open an issue if you find any concrete problem.
