### ISSUE TITLE
FSharpChecker.ProjectChecked event is raised for no reason

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1016]
This lambda https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L358-L375 is called 1-5 times for the same project and document even though the document has not changed - just move the caret with keyboard or click anywhere with mouse. It's extremely strange and I've no idea what's happening. 

(`StartBackgroundCompile ` here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L329 is not called too often, it's called only if a file has changed).

**Comment by dungpa** [comment]
Is the anonymous function called for different `projectFileName`? We have another `StartBackgroundCompile` inside its body https://github.com/fsprojects/VisualFSharpPowerTools/blob/f6fffb6e9d1cab23346171f675a882f3850e0e35/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L370.

**Comment by vasily-kirichenko** [comment]
`projectFileName` is the same.

**Comment by vasily-kirichenko** [comment]
I think it's triggered by this line https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L320

**Comment by vasily-kirichenko** [comment]
Yes. That's because we always pass `AllowStaleResults.No`. Do you remember why?

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1017
