### ISSUE TITLE
Two instances of HighlightUsageTagger are created for each open document

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1019]
I added the following line 
```fsharp
Logging.logInfo "HUT(hash = %d).updateAtCaretPosition" (self.GetHashCode())
```
here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/HighlightUsageTagger.fs#L82 and got the following output on each caret / mouse movement:

First document:
```
[VFPT][Information 02:10:54 PM] HUT(hash = 18949207).updateAtCaretPosition
[VFPT][Information 02:10:54 PM] HUT(hash = 53112446).updateAtCaretPosition
```
Second document:
```
[VFPT][Information 02:10:58 PM] HUT(hash = 47211933).updateAtCaretPosition
[VFPT][Information 02:10:58 PM] HUT(hash = 6033088).updateAtCaretPosition
```

**Comment by vasily-kirichenko** [comment]
I'm almost afraid to dive with debugger into our codebase :(

**Comment by vasily-kirichenko** [comment]
https://github.com/cloudRoutine/EditorUtilsFS/blob/b381e8b2075e0822f4e1fa210cea1296eea8b5ce/src/EditorUtilsFS/EditorUtilFactory.fs#L26

**Comment by dungpa** [comment]
Good for you. Everytime you debug, you find a new bug.

I'll send a PR for this one.

**Comment by vasily-kirichenko** [comment]
I'm already working on it. I added EditorUtils and use `EditorUtilsFactory.CreateBasicTagger`. It almost works.

**Comment by vasily-kirichenko** [comment]
Maybe we should inherit from this class https://github.com/jaredpar/EditorUtils/blob/6b1fa3d19dd4bc48ed5cd0501094155edf76cebc/Src/EditorUtils/AsyncTaggerSource.cs ? It'd simplify things greatly and maybe eliminate bugs.

**Comment by dungpa** [comment]
I think the tricky part is to avoid disposing taggers twice.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1020
