### ISSUE TITLE
Scrollbar markers too wide

### ISSUE THREAD

**Issue by pver** [fsprojects/VisualFSharpPowerTools#1026]
After updating from v1.8.0 to v1.9.0 (in Visual Studio 2012) I now notice that the markers in the scrollbar area are too wide:

![image](https://cloud.githubusercontent.com/assets/1618378/8325325/ea565362-1a58-11e5-81c4-19e2485c88f2.png)

They are fully functional, but they look scary like this :-)

I couldn't test/verify on a newer Visual Studio version yet. I also have Resharper installed, not sure of that interferes with the Power Tools?

**Comment by dungpa** [comment]
Thanks for letting us know. I will take a look.

**Comment by pver** [comment]
Thanks!

A bit more info on this: I retested on a VS 2013 setup (also with ReSharper installed) and everything looks fine on that machine. So it looks like this is a VS 2012 specific issue (version 1.8.0 looked fine though on the same setup). 
I'll also see if I can further track down the root cause of the issue.

**Comment by pver** [comment]
Discovered something else: it looks like the height of the document editor (or the scrollbar) is somehow taken into account when calculating the width of the markers. I've made a screen capture to demonstrate this behaviour:
![marker width demo](https://cloud.githubusercontent.com/assets/1618378/8377752/3ce60552-1c14-11e5-8a92-c9640f861ffc.gif)

**Comment by dungpa** [comment]
Great. Thanks a lot for the investigation. It does help. I will find a fix soon.

**Comment by dungpa** [comment]
@pver Could you help me to check this hotfix version at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.10.0-a1506262012/artifacts? Thanks a lot.

**Comment by pver** [comment]
@dungpa Sure! I have to check it on my computer at work, so I'll have to do it after the weekend, but I'll test it first thing on Monday and give feedback. Already a big thanks for looking into it.

**Comment by pver** [comment]
@dungpa I did a test with the hotfix version and it works perfectly :+1: Thanks!

**Comment by dungpa** [comment]
Great. It was an easy fix thanks to your finding.
