### ISSUE TITLE
[Code generation] Changing self identifier used by "implement interface" feature is not applied for open files

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1033]
You have to close and reopen a document to use changed self identifier, which is not a great user experience.

**Comment by dungpa** [comment]
Most of our settings require reopening files to take effects. Some features (folder organization, task lists) even require restarting Visual Studio. I'm not sure what we can do to improve that.

We could add a label "Please reopen files for the changes to take effects" to 'Code Generation' dialog (similar to what have been done for general dialog). Hopefully it's more intuitive for users.

**Comment by vasily-kirichenko** [comment]
What about a new MEF service, `Settings`, which could be injected into our feature-implementing classes in `Logic` project. Those `Settings` should be 'live', i.e. the settings dialog modifies them after it's closed and the new setting values are immediately available.

**Comment by dungpa** [comment]
The idea is cool but I'm not sure how to implement it, sorry.
