### ISSUE TITLE
Parsing and checking should be stopped when buffer is changed

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1036]
The problem: we request parse and check results for current file constantly when user is editing a file. That's OK, but for large files / projects checking may take up to several *minutes* (FCS for example). As a result, user never gets up-to-date coloring / highlight refs / lint / etc.; what he gets is heavy CPU load for nothing. 

Yes, we try to kill current checking (in one place - colorizer, so it cannot have any effect anyway) by cancelling `Async` in which we are calling FCS, but FCS asyncs are not cancellable. 

The right approach is to pass a callback here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L194. The callback should return `true` if the buffer for which we requested checking has been changed. This results with current checking stopped immediately. Then we request new check results for new buffer and so on.

How to implement:

* a singleton object holding a `Map` `full file name => BufferState` (maybe just adjust `OpenDocumentsTracker` for this?)
```fsharp
type BufferState =
  { mutable IsChanged: bool }
  member x.IsResultObsolete() = x.IsChanged
```
* `BufferState.IsResultObsolete` is passed to `FSharpChecker.ParseAndCheckFileInProject`
* the singleton is listening to all open buffers' changed events 
* when it receives an event, it sets `IsChanged <- true` which forces FCS to stop checking (if it's active) and prevent outdated buffers checking.

Result: user gets fresh results in time required to check file / project.

**Comment by dungpa** [comment]
Sound reasonable. 

We should take advantage of `OpenDocumentsTracker`; it already subscribes for all `BufferChanged` events.

One thing is unclear about your proposal. When will `IsChanged` be marked false again? It's problematic to use mutable record fields in potentially multithreading situations.

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1100
