### ISSUE TITLE
Use new Visual Studio 2015 UI to rename bindings (variables)

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1041]
Could you update the logic to be able to rename bindings (variables) inline like it does Visual Studio 2015 instead of showing a dialog window?

**Comment by dungpa** [comment]
That logic belongs to Visual C#/VB language services. We can only do it if it is exposed as a public extension point in VS SDK.

**Comment by xperiandri** [comment]
I guess that if it works in editor which is common across Visual Studio it must available to all the languages

**Comment by dungpa** [comment]
It's not possible to do this atm. I'm closing this until there is a public API to do it.
