### ISSUE TITLE
Enable Snippets in F#

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1042]
Could you enable Snippet service for F#
http://apollo13cn.blogspot.com/2012/06/f-code-snippet-visual-studio-2012-addon.html
Like it was done by this guy.
And provide a latest set of snippets from
http://fsharpcodesnippet.codeplex.com/
With Power Tools

I already asked Tao Liu to open source its extension.

I don't know if it is a good or bad idea to include them into power tools. So what do you think?

**Comment by dungpa** [comment]
In general, we welcome any PR adding unmaintained F# extensions to VFPT. However, the PR has to go through scrutiny so that the new part is in harmony with the rest of the code base. I'm not sure anyone wants to take that challenge for F# snippets.

**Comment by vasily-kirichenko** [comment]
I agree. I've never used snippets and never met a person who uses them. So if you really wants them integrated into this addin, go ahead.

**Comment by vasily-kirichenko** [comment]
We are managing feature requests on User Voice.
