### ISSUE TITLE
Ctrl+. doesn't work in Visual Studio 2015

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1043]
I try to use Ctrl+. in Visual Studio 2015 but it doesn't work.
However smart tag appears using mouse

**Comment by xperiandri** [comment]
Is it possible to use analyzers in F# like in C#?
So light bulb appears if some refactoring is available?

**Comment by vasily-kirichenko** [comment]
Same. It does not work in vs 2015 though.

**Comment by ashtonkj** [comment]
You can get it to work by binding the key for View.ShowSmartTag to something (I use CTRL + , ). It will then work with FS Power Tools.

**Comment by vasily-kirichenko** [comment]
Ctrl + , is used for find all references.

**Comment by ashtonkj** [comment]
I rarely use find all references. I always use the smart tag options, so it wasn't much of a loss for me :P

**Comment by dungpa** [comment]
Closing as a dup of https://github.com/fsprojects/VisualFSharpPowerTools/issues/987.

We should move to the new API that occupies 'Ctrl + .' key binding at some point. It's very tricky since we would like to keep the features as is for VS 2013 and VS 2012.

**Comment by xperiandri** [comment]
I think that it is a time to spit codebase
Maybe using Shared Project
