### ISSUE TITLE
Widen Scope refactoring

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1045]
Do you know if it is possible to implement Widen Scope refactoring using Visual Studio 2015 Light Bulb feature?

**Comment by vasily-kirichenko** [comment]
What it should do?

**Comment by xperiandri** [comment]
Move a nested function 1 level up
If at the higher level is module then into that module else to the higher level function

**Comment by vasily-kirichenko** [comment]
We are managing feature requests on User Voice.
