### ISSUE TITLE
Use Light Bulb API instead of Smart Tag API in VS2015

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1049]
We need to move to a new modern way of refactoring by using Light Bulb API instead of Smart Tag API in VS2015

**Comment by xperiandri** [comment]
We need to update:
- implement interface
- rename
- generate record stub
- generate union pattern match cases
- generate references for FSI

@dungpa, @vasily-kirichenko, have I forgotten anything which needs to be updated to use Light Bulb?

**Comment by dungpa** [comment]
Mostly correct. You should add "Resolve unopened namespaces" and remove "Generate references for FSI".

**Comment by vasily-kirichenko** [comment]
@dungpa So, it can be compiled in VS 2015 only, right? Can you formulate the process? Should we add `FSharpVSPowerTools.Logic.VS2015` project and put all VS 2015 stuff there? Should the project be included into `FSharpVSPowerTools.v14.sln` only?

Could you write a short description how our stuff organized regarding different version of VS?

**Comment by ovatsus** [comment]
Please make it an option so you can opt to have just the current SmartTags with the discrete underline instead of the LightBulb

**Comment by xperiandri** [comment]
@ovatsus, do you think someone will ever use Smart Tags instead if he has Light Bulb?
Light Bulb is a primary way of doing refactoring in Visual Studio 2015.
Smart Tag even can't be executed using Ctrl+.

**Comment by dungpa** [comment]
@vasily-kirichenko It can be compiled with VS 2013 if we include VS 2015 dlls into build process. And they can appear in both solutions.

Here is how it works:

 - `FSharpVSPowerTools.Logic.VS2015` exports a provider with fully working solution. It exports as `VS2015` attribute.
 - `FSharpVSPowerTools.Logic` exports a provider which simply returns null. It exports as `VS2013` attribute.
 - The main facade uses `ImportMany` and choose the most recent VS version. The logic is the same as https://github.com/fsprojects/VisualFSharpPowerTools/blob/7e0ea76fc23be871ce5aebd02272d7feed8447e2/src/FSharpVSPowerTools.Logic/NavigateToItem.fs#L33-L51.

We should test that it works fine in VS 2015 and doesn't throw exceptions in VS2013. The main logic of the feature is almost similar as that of smart tags.

**Comment by dungpa** [comment]
@vasily-kirichenko Something new you may not notice. In Properties page of `FSharpVSPowerTools.csproj`, you can change experimental instance of `Visual Studio 12` to that of `Visual Studio 14` so that deployment can be done on directly VS 2015. We can use this to develop in VS 2013 and test in both VS 2013 and VS 2015.

**Comment by xperiandri** [comment]
I wonder what is the purpose to do such dances with a tambourine? :)

**Comment by vasily-kirichenko** [comment]
@dungpa I tried to build in 2013 and "run without debugger" with 2015. It launches, but the addin was not installed. So I've given up and move to 2015 for now. It hangs rather often though, and I have to kill it and restart.

**Comment by dungpa** [comment]
I can F5 (run under debugging) to install and debug VFPT on VS 2015. There might be some exceptions, but it works after ignoring those. It's quite handy since VS 2013 is much more stable to use than VS 2015.

**Comment by vasily-kirichenko** [comment]
I'm trying to use 2015 -> 2015 and what I get on Ctrl+F5:

![image](https://cloud.githubusercontent.com/assets/873919/9054797/8b17dd62-3a8d-11e5-8ee3-6c98c29ae656.png)

I never seen anything like this in my whole life.

**Comment by vasily-kirichenko** [comment]
It does not work for me :( This is VS 2013 output:

```
1>CreateVsixContainer:
1>  Creating VSIX Container...
1>  Creating the package with the following compression level. "Normal".
1>  FSharpVSPowerTools -> D:\git\VisualFSharpPowerTools\bin\FSharpVSPowerTools.vsix
1>FindExistingDeploymentPath:
1>  Extension 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' located at 'C:\USERS\KOT\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0EXP\EXTENSIONS\FSHARP.ORG\VISUAL F# POWER TOOLS\2.0.1\'.
1>DeployVsixExtensionFiles:
1>  VsixID = FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8
1>  VsixVersion = 2.0.1
1>  VsixDeploymentPath = C:\Users\kot\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\
1>  Copying file from "obj\Release\FSharpVSPowerTools.dll" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\FSharpVSPowerTools.dll".
1>  Copying file from "obj\Release\extension.vsixmanifest" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\extension.vsixmanifest".
1>  Copying file from "obj\Release\FSharpVSPowerTools.pdb" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\FSharpVSPowerTools.pdb".
1>  Extension 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' has been enabled.
1>CopyVsixManifestFile:
1>  Copying file from "obj\Release\extension.vsixmanifest" to "..\..\bin\extension.vsixmanifest".
1>  FSharpVSPowerTools -> D:\git\VisualFSharpPowerTools\bin\extension.vsixmanifest
1>DeployToVisualStudio2015:
1>  Deploying extension to Visual Studio 2015...
1>ZipProjects:
1>  Zipping ProjectTemplates
1>  FSharpVSPowerTools -> 
1>ZipItems:
1>  Zipping ItemTemplates
1>  FSharpVSPowerTools -> 
1>_CopyOutOfDateSourceItemsToOutputDirectory:
1>Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
1>CopyFilesToOutputDirectory:
1>  FSharpVSPowerTools -> D:\git\VisualFSharpPowerTools\bin\FSharpVSPowerTools.dll
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>GeneratePkgDef:
1>  Creating intermediate PkgDef file.
1>  VSSDK1033: Skipping generation of PkgDef because all files are up to date.
1>CheckCTOFileHasChanged:
1>Skipping target "CheckCTOFileHasChanged" because all output files are up-to-date with respect to the input files.
1>RestorePackages:
1>  "D:\git\VisualFSharpPowerTools\.paket\paket.exe" restore --references-files D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Core\paket.references
1>  0 seconds - ready.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>CopyFilesToOutputDirectory:
1>  FSharpVSPowerTools.Core -> D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Core\bin\Release\FSharpVSPowerTools.Core.dll
1>RestorePackages:
1>  "D:\git\VisualFSharpPowerTools\.paket\paket.exe" restore --references-files D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\paket.references
1>  0 seconds - ready.
1>MainResourcesGeneration:
1>Skipping target "MainResourcesGeneration" because all output files are up-to-date with respect to the input files.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>CopyFilesToOutputDirectory:
1>  FSharpVSPowerTools.Logic -> D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\bin\Release\FSharpVSPowerTools.Logic.dll
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>CreateVsixContainer:
1>  Creating VSIX Container...
1>  Creating the package with the following compression level. "Normal".
1>  FSharpVSPowerTools -> D:\git\VisualFSharpPowerTools\bin\FSharpVSPowerTools.vsix
1>FindExistingDeploymentPath:
1>  Extension 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' located at 'C:\USERS\KOT\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\FSHARP.ORG\VISUAL F# POWER TOOLS\2.0.1\'.
1>DeployVsixExtensionFiles:
1>  VsixID = FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8
1>  VsixVersion = 2.0.1
1>  VsixDeploymentPath = C:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\
1>  Copying file from "obj\Release\FSharpVSPowerTools.dll" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\FSharpVSPowerTools.dll".
1>  Copying file from "obj\Release\extension.vsixmanifest" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\extension.vsixmanifest".
1>  Copying file from "obj\Release\FSharpVSPowerTools.pdb" to "C:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp\Extensions\fsharp.org\Visual F# Power Tools\2.0.1\\FSharpVSPowerTools.pdb".
1>  Extension 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' has been enabled.
1>CopyVsixManifestFile:
1>  Copying file from "obj\Release\extension.vsixmanifest" to "..\..\bin\extension.vsixmanifest".
1>  FSharpVSPowerTools -> D:\git\VisualFSharpPowerTools\bin\extension.vsixmanifest
1>CreateMenuPkgDef:
1>Skipping target "CreateMenuPkgDef" because it has no outputs.
1>CreateMenuPkgDef:
1>Skipping target "CreateMenuPkgDef" because it has no outputs.
1>
1>Build succeeded.
```
Everything looks OK, but VFPT does not appear in Extensions and Updates dialog nor it works, of course.

**Comment by vasily-kirichenko** [comment]
If I change `/rootsuffix` to some new value, then it does not work even VS 2015 -> VS 2015. Could you reproduce it?

**Comment by xperiandri** [comment]
Did you install RTM on top of RC or did you do 2015 RTM clean install?

**Comment by dungpa** [comment]
Nothing looks suspicious from the log. You can try to bump version in `extension.vsixmanifest` and check that all assemblies are copied to `C:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp\Extensions\fsharp.org\Visual F# Power Tools\<version>` correctly.

**Comment by vasily-kirichenko** [comment]
It does not help. 
I revert rootsuffix to Exp and the extension was appear, but colors everywhere in VS was broken, so I deleted `c:\Users\kot\AppData\Local\Microsoft\VisualStudio\14.0Exp` folder entirely and Ctrl+F5 again. No VFPT :( 

Could you remove that folder and try to repeat this behavior?

**Comment by dungpa** [comment]
I confirm that removing that folder and Ctrl + F5, VFPT isn't installed.

When I increase VFPT version and run F5, VFPT is installed to Experimental instance again.

**Comment by xperiandri** [comment]
1. Does resetting settings to details by importing default for you, possibly F# default, help?
2. Doing rebuild usually helps for me to force extensions deploy to experimental instance.
3. Check deployment path

**Comment by vasily-kirichenko** [comment]
@dungpa I have issues.

`ISuggestedActionsSourceProvider` and `ISuggestedActionsSource` are defined in `C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.Language.Intellisense\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Language.Intellisense.dll` (VS 2015) only. Logic project references `D:\github\FSharpVSPowerTools\lib\vs2012\Microsoft.VisualStudio.Language.Intellisense.dll` where those interfaces are absent. So, the only place where we can `Export` `ISuggestedActionsSourceProvider` is Logic.VS2015 project (https://github.com/vasily-kirichenko/FSharpVSPowerTools/blob/light-bulb/src/FSharpVSPowerTools.Logic.VS2015/ResolveUnopenedNamespaceSuggestedActionsSourceProvider.fs#L14). But it does not work at all - light bulb does not appear and breakpoints are not active. Am I right that we can export from `FSharpVSPowerTools` assembly only? If so, I cannot see a solution.

**Comment by dungpa** [comment]
We can add VS2015's `Microsoft.VisualStudio.Language.Intellisense.dll` to `lib\vs2015` folder and reference on both projects.

In order to use the new project as a MEF component; it should be added to https://github.com/fsprojects/VisualFSharpPowerTools/blob/7e0ea76fc23be871ce5aebd02272d7feed8447e2/src/FSharpVSPowerTools/source.extension.vsixmanifest#L27.

**Comment by vasily-kirichenko** [comment]
I'm afraid I don't understand why we need VS2015 project at all. What could go wrong if we implement `ISuggestedActionsSourceProvider` right in Logic project? VS 2013 will throw?

**Comment by dungpa** [comment]
I'm not sure either. I think it should work with both providers on Logic project.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/9118182/687bb3e6-3c77-11e5-9ef2-4048b7f922b3.png)

:)

**Comment by dungpa** [comment]
Wow. Time to celebrate :+1:.

**Comment by xperiandri** [comment]
Yahoo! I'm happy.
Is it also possible to implement a preview of changes for F#?

**Comment by vasily-kirichenko** [comment]
"Resolve unopened namespaces" is done here https://github.com/fsprojects/VisualFSharpPowerTools/pull/1069

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1079

**Comment by dungpa** [comment]
@xperiandri Could you please install this build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508110519 and give us feedback on the new lightbulb functionalities? Thanks.

**Comment by xperiandri** [comment]
Light bulb works well

However "Resolve unopened namespaces" works not as expected

I got
``` F#
open FSharp.Text.RegexProvider
type UrlRegex = Regex<"background(-image)?: url\(\"??(?<url>\S+)\???\d*\"??\)">
```

So I commented
``` F#
/// open FSharp.Text.RegexProvider
```

But suggestion appear only for
``` F#
open System.Text.RegularExpressions
```
And it must not appear for a type provider.

But as I understand it is a problem of class resolution logic.

**Comment by dungpa** [comment]
@xperiandri We don't have assembly metadata for erased type providers. So it's a limitation that unfortunately we can't bypass.

**Comment by xperiandri** [comment]
OK, but anyway a type declared from TypeProvider is a type.
So it can be found, can't it?

**Comment by xperiandri** [comment]
Finally I was explained how to create a standard UI for displaying changes made by action.
https://github.com/dotnet/roslyn/issues/4520#issuecomment-152046626

**Comment by dungpa** [comment]
@xperiandri PRs are welcome.
