### ISSUE TITLE
Source code formatting breaks code by removing whitespace from expression

### ISSUE THREAD

**Issue by bentayloruk** [fsprojects/VisualFSharpPowerTools#1050]
Source code formatting breaks the expression `(Blah.TryCreate inputBlah)`, by removing the whitespace.  The following complete example code shows the working version:

``` fsharp
module File1

type Blah = 
  private
  | Blah of string
  
  static member TryCreate msg = 
    if msg = "" then None
    else Some(Blah msg)
  
  member __.Value = 
    match __ with
    | Blah msg -> msg

let inputBlah = "So, I was like, Visual Studio did wat!?"
let someBlahing = (Blah.TryCreate inputBlah).Value
```

After formatting, the last line has been changed and the code is broken:

```fsharp
module File1

type Blah = 
  private
  | Blah of string
  
  static member TryCreate msg = 
    if msg = "" then None
    else Some(Blah msg)
  
  member __.Value = 
    match __ with
    | Blah msg -> msg

let inputBlah = "So, I was like, Visual Studio did wat!?"
let someBlahing = (Blah.TryCreateinputBlah).Value
```

**Comment by dungpa** [comment]
Thanks for reporting. I'll have a look.

**Comment by bentayloruk** [comment]
Great.  What does the `upstream` label denote?  An issue in FCS/another dependency?

**Comment by dungpa** [comment]
It's an issue in https://github.com/dungpa/fantomas engine. The 'upstream' label reminds me to push a fix there.

**Comment by bentayloruk** [comment]
Thank you @dungpa!  Your amazing work is very much appreciated by me! :tada:
