### ISSUE TITLE
VS2015 CE RTM crashes on startup with F# Power Tools installed

### ISSUE THREAD

**Issue by asik** [fsprojects/VisualFSharpPowerTools#1052]
On a clean install of VS2015 Community Edition, when I install F# Power Tools and restart, VS2015 crashes on startup. Then it crashes every time I try to open an F# solution. Uninstalling F# Power Tools fixes the problem.

Obviously not everyone is having this issue, I'm not sure what information I could provide that would be relevant. I previously had VS2015 RC which I uninstalled before installing VS2015 CE. My locale is also French (Canada).

Update: after reinstalling the extension again, it now works without crashing. ...

**Comment by dungpa** [comment]
Do you select Visual F# to be installed when setting up VS 2015 RTM? See a similar issue https://github.com/fsprojects/VisualFSharpPowerTools/issues/1048.

Our assumption is that VS 2015 should have F# installed before installing our extension. However, things suddenly changed in VS 2015 RTM when F# isn't included in a typical installation.

**Comment by asik** [comment]
Yes I did. I could open an F# solution fine before installing the extension.

**Comment by dungpa** [comment]
We released v2.0.0 with a few fixes for F# 4.0 and VS 2015. Please give it a try and let us know if there is any issue.
