### ISSUE TITLE
Display file contents in Solution Explorer

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1063]
Is it possible to display F# file contents in Solution Explorer like it is done for C#?
I mean that when you open C# file node it displays a list of classes in a file. Then if you expand a class it will display a list of its members.

I want the same thing for F# so it will display all the modules, types and functions in that class.
In order to be able to search from within Solution Explorer

**Comment by dungpa** [comment]
Feature request: http://vfpt.uservoice.com/forums/247560-general/suggestions/6785640-feaure-request-code-navigation-using-class-view
Related discussion: http://visualfsharp.codeplex.com/workitem/135

**Comment by dungpa** [comment]
I agree it could be useful. 

Hope one day @ReedCopsey could help with this.

**Comment by xperiandri** [comment]
Does this feature really has name Class View?

**Comment by vasily-kirichenko** [comment]
The first thing I do in a fresh installed VS is disabling this feature through the registry. 

We manage feature requests on User Voice, so I'm closing this.
