### ISSUE TITLE
navigation bar in signature file empty

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/VisualFSharpPowerTools#1067]
nothing in navigation bar of signature files
I'm on Win10, VS2015, but I'm pretty sure this is also a problem under 8.1, VS2013

**Comment by vasily-kirichenko** [comment]
Navigation bar is a part of Visual F# Tools, we just turn it on in devenv.exe.config 
Please, report the issue in VFT repository.

**Comment by jackfoxy** [comment]
Done.
https://github.com/Microsoft/visualfsharp/issues/572
