### ISSUE TITLE
VS 2015 Coloring Issues 

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/VisualFSharpPowerTools#1075]
### Syntax Highlighting isn't working 
![2015-08-09_00-37-37](https://cloud.githubusercontent.com/assets/680051/9153590/de20111a-3e2e-11e5-9c84-432cfdf2a0c8.png)

### `|`  `<` `,` `_` Recognized as Plain Text 
![2015-08-09_00-51-39](https://cloud.githubusercontent.com/assets/680051/9153620/4c52a51a-3e31-11e5-93e1-85a63d4d3679.png)
![2015-08-09_00-53-51](https://cloud.githubusercontent.com/assets/680051/9153621/50070c8c-3e31-11e5-84d3-ea6f0569aa68.png)
![2015-08-09_01-04-02](https://cloud.githubusercontent.com/assets/680051/9153645/8e298c00-3e32-11e5-92f5-1865f8e410ea.png)

### Unused Declarations shown on Scrollbar but color isn't changed
![2015-08-09_00-57-12](https://cloud.githubusercontent.com/assets/680051/9153626/9f096334-3e31-11e5-89eb-8b5f71cb593b.png)

**Comment by dungpa** [comment]
@cloudRoutine Would you mind to try the latest build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508090831/artifacts?

We fixed the color ordering recently, so this one might go away as well.

**Comment by cloudRoutine** [comment]
Awesome, the coloring is working now.

**Comment by dungpa** [comment]
Thanks. 

I think it should work. Maybe quotation background color makes it hard to read?

**Comment by cloudRoutine** [comment]
![2015-08-09_19-20-59](https://cloud.githubusercontent.com/assets/680051/9157443/cabe5814-3ecb-11e5-989c-210c31a82507.png)

It only works partially, Value types, and F# types seem to be recognized while numerals, operators, strings, patterns, and modules are ignored.
