### ISSUE TITLE
F12 does not work in current master

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1078]
![image](https://cloud.githubusercontent.com/assets/873919/9155223/92ff87f2-3eb9-11e5-93fb-757509ed242a.png)

**Comment by dungpa** [comment]
It works fine for me on VS2013 and VS2015.

Does it fail on every example you tried? Does it fail on both VS2013 and VS2015?

**Comment by vasily-kirichenko** [comment]
It works on another machine.
