### ISSUE TITLE
Lightbulb for "Value or constructor 'symbol' is not defined" is empty when clicked.

### ISSUE THREAD

**Issue by jeroldhaas** [fsprojects/VisualFSharpPowerTools#1080]
Undefined values or constructor error shows a :bulb: lightbulb, but provides no options when clicked / hotkey is typed.

version 2.0.6

**Comment by dungpa** [comment]
@jeroldhaas Can you show a screenshot or a small repro?

**Comment by jeroldhaas** [comment]
![lightbulb](https://cloud.githubusercontent.com/assets/835976/9155970/0fad9cf2-3e98-11e5-8805-be403fe1c932.png)

**Comment by jeroldhaas** [comment]
I have attempted to restructure the code in various ways to find out if previous lines of code are conflicting with the parser's ability to resolve a proper solution, however I haven't been able to get the lightbulb to work properly with the undefined error.

**Comment by vasily-kirichenko** [comment]
will fix it in a minute

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1081
