### ISSUE TITLE
Auto-generated XML doc mis-appropriates functor as param when using declaration with signature (Haskell-style?)

### ISSUE THREAD

**Issue by jeroldhaas** [fsprojects/VisualFSharpPowerTools#1085]
Example Code (`|` shown where editor caret is placed):
```F#
/// <summary>
/// |
/// </summary>
/// <param name="func"></param>
let func : int -> int -> int list =
    fun x y ->
        List.append [x] [y]
```

However, when written in less uncommon (normal?) style, it works properly:
```F#
/// <summary>
/// |
/// </summary>
/// <param name="x"></param>
/// <param name="y"></param>
let func2 (x:int) (y:int) : int list =
    List.append [x] [y]
```

Resulting intellisense hints:
![image](https://cloud.githubusercontent.com/assets/835976/9284825/595df7ac-42ad-11e5-926b-9304f92a2112.png)

...then, after attempting to enter 2nd param (even trying `Ctl-Shift-Space`:
![image](https://cloud.githubusercontent.com/assets/835976/9284977/13b0e974-42af-11e5-87ba-b8383a5ebc42.png)

...placed into a module, however, names appear nicely:
![image](https://cloud.githubusercontent.com/assets/835976/9285085/1cda6c5e-42b0-11e5-8325-cce55c759ba7.png)

...but, once again, when I start typing in params:
![image](https://cloud.githubusercontent.com/assets/835976/9285132/93fb1a5e-42b0-11e5-8381-c11f18f7599a.png)

**Comment by vasily-kirichenko** [comment]
The first thing is a value of type `int -> int -> int list`, the second is a function. The only thing VFPT does wrong is trying to deduce *any* arguments from the value.
