### ISSUE TITLE
Crucial space omitted by formatter when accessing record members

### ISSUE THREAD

**Issue by EdAyers** [fsprojects/VisualFSharpPowerTools#1087]
```F#
  type foo = {
    number : int
  }

  let f = fst
  let g x = (f x).number
```
Hitting Format-Document (Ctrl-K, Ctrl-D) in VS2015 causes the above code to look like;

```F#
  type foo = 
    { number : int }
  
  let f = fst
  let g x = (fx).number
```
note how `f x` has become `fx` leading to a build error.

**Comment by dungpa** [comment]
I think we have fixed a similar bug recently. Could you please check the recent v2.0.7 build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508110519/artifacts? Thanks.

**Comment by EdAyers** [comment]
Yep, it's fixed on the above build

**Comment by dungpa** [comment]
Thank you. I'm closing this as fixed.
