### ISSUE TITLE
Rename functionality does not update XML docs

### ISSUE THREAD

**Issue by Rickasaurus** [fsprojects/VisualFSharpPowerTools#1088]
This would really be nice to have.

**Comment by andredublin** [comment]
I'd like to take on this task.

**Comment by vasily-kirichenko** [comment]
Greate, go ahead. 

I thing FParsec fits here nicely. 

Also I think that new XML doc parser should yield hints or warnings if argument / type / etc. names are outdated in comments.

**Comment by vasily-kirichenko** [comment]
VS 2017 has rename refactoring out of the box. It does not update XML docs either, so if you still care about this, open an issue in VFT repo.
