### ISSUE TITLE
Quick info panel shows wrong namespace

### ISSUE THREAD

**Issue by bleis-tift** [fsprojects/VisualFSharpPowerTools#1089]
repro steps:

1. create solution
1. add `Sample.Core` project
1. add referece to `Sample.Core`
1. build
1. add `open Sample.Core`
1. Quick info panel shows wrong namespace (expected `Sample.Core` but `Microsoft.FSharp.Core`)

note: tooltip shows correct namespace.

![image](https://cloud.githubusercontent.com/assets/169348/9347393/eb2c29a6-4663-11e5-9d0b-a2ff6c9d3a3d.png)

**Comment by vasily-kirichenko** [comment]
What does tooltip show?

**Comment by dungpa** [comment]
It's very likely that we don't pass enough contextual info to FCS. They may expect long identifiers but we pass short identifier at https://github.com/fsprojects/VisualFSharpPowerTools/blob/e736aa38668d182696b04dd2f6e6dd637b2515f1/src/FSharpVSPowerTools.Logic/QuickInfoMargin.fs#L101.

We may have `Sample.Core` in the tooltip results, but it could be truncated before displaying in QuickInfo panel.

**Comment by vasily-kirichenko** [comment]
It seems it works ok for me:

![image](https://cloud.githubusercontent.com/assets/873919/9351162/d4005120-465f-11e5-9091-0d1c097b8a93.png)

Try to rebuild the solution and reopen VS.

**Comment by dungpa** [comment]
I can repro following the steps above. 

(Sent Vasily a repro solution by email.)
