### ISSUE TITLE
load-references does not auto-regenerate in VS2015

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#1090]
Manually calling "Generate references for F# Interactive" works fine - it just doesn't happen on building solutions any more.

**Comment by vasily-kirichenko** [comment]
I confirm it does not auto update in VS 2013 either (on master).

**Comment by dungpa** [comment]
Weird. It used to work at one point. I wonder what have changed inside VS.

Does auto-update of syntax coloring work any longer https://github.com/fsprojects/VisualFSharpPowerTools/blob/f0b2ac7a5261ebc7ee2f3b5d3e68ca1004365948/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L345-L354?

**Comment by vasily-kirichenko** [comment]
Checked it on master on a tiny solution in VS 2013. Works OK. Strange. I'm absolutely sure it did not work on my solution at work and I constantly had to execute the command manually.
