### ISSUE TITLE
Generated references could use forward slashes as path seperators

### ISSUE THREAD

**Issue by devboy** [fsprojects/VisualFSharpPowerTools#1093]
When generating references for FSI:

```
#I __SOURCE_DIRECTORY__
#r @"..\..\..\src\bin\Debug\FunSharp.Library.dll"
#r @"System.Core.dll"
#r @"System.dll"
#r @"System.Numerics.dll"
#r @"..\..\..\lib\Xwt.dll"
#r @"..\..\..\lib\Xwt.Gtk.dll"
```

Backslashes don't work on non-windows platforms, whereas Windows can handle forward slashes.
Would like to be able to use the generated files on OSX without manually replacing the slashes ;)

**Comment by dungpa** [comment]
Oh, I have never thought of that.

Do you want to send a PR? Handling relative path is done at https://github.com/fsprojects/VisualFSharpPowerTools/blob/e736aa38668d182696b04dd2f6e6dd637b2515f1/src/FSharpVSPowerTools.Logic/FsiReferenceCommand.fs#L69-L77

**Comment by devboy** [comment]
Will try to find the time ;)

**Comment by vasily-kirichenko** [comment]
Hurry up, I've almost picked this one :)

**Comment by devboy** [comment]
Please, go ahead. This week is quite tight for me ;)

**Comment by vasily-kirichenko** [comment]
Same ;)

**Comment by dungpa** [comment]
I would prefer that @devboy PRs and @vasily-kirichenko reviews  the code (and I'm cheerleading).

The more contributors there are, the merrier the project is :-).
