### ISSUE TITLE
Complete FSharpLint integration

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#1094]
There are only two remaining things to finish:

 - Add UI for changing Lint settings
 - Add docs for FSharpLint integration

**Comment by dungpa** [comment]
@duckmatt When you have a prototype UI for changing FSharpLint settings, please send a PR. We could help a bit in order to complete the feature.

**Comment by duckmatt** [comment]
Okay great, I've got a fully functioning UI for the options now, looking at hooking it up to the new configuration management I've been adding to FSharpLint. I'll get a work in progress pull request together

**Comment by dungpa** [comment]
It has been done in v2.1.0. Thanks Matt for the great work.

**Comment by duckmatt** [comment]
No problem, thank you for including it
