### ISSUE TITLE
Parenthesized expression formatting

### ISSUE THREAD

**Issue by torbonde** [fsprojects/VisualFSharpPowerTools#1102]
Consider the following code
```
type Foo() =
    let bar = (Some 42, "abc")
    member x.Baz = (fst bar).Value
```
When formatting this (using Ctrl-K Ctrl-D, for instance), the space in the parenthesized expression gets stripped. I.e. the result of formatting is
```
type Foo() = 
    let bar = (Some 42, "abc")
    member x.Baz = (fstbar).Value

```

**Comment by dungpa** [comment]
I think I have fixed it on master recently. Could you please check https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/artifacts?

**Comment by torbonde** [comment]
It appears to be working! Thanks.:)
