### ISSUE TITLE
Smart string breaking

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1104]
![1](https://cloud.githubusercontent.com/assets/873919/9682445/68a1b8d0-530f-11e5-9655-29b855f976e5.gif)

Lexer should be enough for this, so it'd work blazing fast.

**Comment by dungpa** [comment]
Look cool. But what's the use case for this?

I wonder whether Scala has something similar to F#'s triple-quote strings. It seems like triple-quote strings should be used instead of concatenating string literals.

**Comment by vasily-kirichenko** [comment]
Well, Scala has triple-quoted strings as well :)

![1](https://cloud.githubusercontent.com/assets/873919/9682756/4a260408-5312-11e5-97c4-2e6316f64755.gif)

**Comment by dungpa** [comment]
Again, I don't understand when users need this (other than being cool :D).
