### ISSUE TITLE
Move `ResolveUnopenedNamespaceTagger.updateAtCaretPosition` to ThreadPool

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1105]
![pasted image at 2015_09_05 19_34](https://cloud.githubusercontent.com/assets/873919/9700396/b5a9f976-5409-11e5-88c5-09121adf539f.png)

**Comment by dungpa** [comment]
Interesting. How does dotTrace know this is a UI freeze?

From the screenshot, nothing gets run on the main thread. It seems like GC happens here. What can we do about this?

**Comment by vasily-kirichenko** [comment]
Yep, it's GC :( FCS produces objects like crazy:

![pasted image at 2015_09_05 21_30](https://cloud.githubusercontent.com/assets/873919/9700837/377f9de6-541b-11e5-936a-65a586e9c09b.png)

Anyway, I moved all `updateAtCaretPosition` functions to ThreadPool here  https://github.com/fsprojects/VisualFSharpPowerTools/pull/1106

**Comment by vasily-kirichenko** [comment]
I think it's the compiler itself who creates so many objects. No hope to remove UI freezes :(

**Comment by dungpa** [comment]
Unless we fix the issues in FCS :-) /cc @dsyme

**Comment by dsyme** [comment]
Certainly, the compiler and FCS allocates, and always will - it can't do its work without that.  

One question which I'd like expert help with is why those allocations are leading to Gen2 collections (which I presume are the intense bands shown above), and why those collections are stopping the world for such long times (which I presume depends partly on the GC settings being used by VS - but I would have expected those to be set for minimal stop-the-world interruption)

Part of the problem will be overall memory pressure but perhaps there are other reasons too.  Any help/insight appreciated.

**Comment by vasily-kirichenko** [comment]
My guess: gen2 is full with FCS caches data, that's why collecting it is so expensive. I will try to get VS snapshot and look at get2.

**Comment by dsyme** [comment]
> My guess: gen2 is full with FCS caches data, that's why collecting it is so expensive. I will try to get VS snapshot and look at get2.

Yes, definitely.  Reducing the amount of caching (strong and/or weak) you do will certainly improve things (at the cost of non-trivial recomputation). 

But I still wonder if there's a root cause why the majority of Gen2's are being triggered (other than overall memory pressure)

**Comment by vasily-kirichenko** [comment]
> Reducing the amount of caching (strong and/or weak) you do will certainly improve things (at the cost of non-trivial recomputation).

I believe it's FCS caches, not VFPT. We cache very few and very simple (no complex object graphs) data actually. FCS, on the other hand, caches complex structures that come right from inside the compiler code. Maybe I'm wrong. 

> But I still wonder if there's a root cause why the majority of Gen2's are being triggered (other than overall memory pressure)

I think it was memory pressure since it was FCS solution open, with which VS has performance issues even with VFPT disabled. VS had not frozen for some small time (~1 minute), but then started freezing every few seconds - it was practically impossible to edit files at all.

**Comment by dsyme** [comment]
> I believe it's FCS caches, not VFPT. We cache very few and very simple (no complex object graphs) data actually. FCS, on the other hand, caches complex structures that come right from inside the compiler code. Maybe I'm wrong. 

Right, but [you set the parameters for FCS cache sizes](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L173), you can adjust those - doing so should help control overall memory usage (at the cost of recomputation).  Also it is possible to submit modifications to FCS to change the configurability and/or operation of the caches.

**Comment by vasily-kirichenko** [comment]
> Right, but you set the parameters for FCS cache sizes, you can adjust those - doing so should help control overall memory usage (at the cost of recomputation).

Yes, but in FCS solution case those settings do not help (because the solution contains very few projects and one of them is huge). 

So I think we should change type of the cached data itself, but it's problematic since we tend to traverse it deeply. Maybe making more stuff `lazy` would help?

**Comment by dsyme** [comment]
I see, thanks. One approach here would be to move FCS out of process to a 64-bit process, allowing it to use more memory (on >4GB machines, which are common now).  But moving FCS out of process is really not easy since a number of different kinds of references tend to be kept live by tooling like VFPT.

Perhaps someone could experiment with what it would take to build VFPT on top of FsAutoComplete (an out-of-process tool which presumably handles these things better).

Reducing FCS memory usage bit by bit is a hard path to follow - with good work you might get 25% saving, but the pauses above will just reappear on a marginally bigger solution.

**Comment by vasily-kirichenko** [comment]
I like the idea of external x64 process very much. I'll explore FsAutoComplete, thanks (I didn't know it can do more than just providing auto-completion).

However, one thing is problematic. As Visual F# Tools uses in-process FCS analog, extracting FCS out of VFPT would not solve the problem entirely - it'd cut memory usage by factor of 2 (or better as VFPT does cross project analysis).
