### ISSUE TITLE
VS unit tests fail on master

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#1107]
After #1106, getting cursor positions moves to ThreadPool. 

Setting cursor position might occur after the first TagChanged event, therefore, test assertions fail.

These unit tests need to be updated.

**Comment by vasily-kirichenko** [comment]
I've read it 10 times and still don't understand :) Could you point at problematic code?

**Comment by dungpa** [comment]
The code is fine. The test infrastructure is problematic.

`DocumentEventListener` always invokes `updateCursorPosition` when a tagger is created. Before we check cursor positions on UI thread so the checks often occur after we set cursor positions on VS unit tests. Now, getting cursor positions and setting them are asynchronous, their order is non-deterministic.

I changed the unit tests to always set cursor positions very early in #1108.
