### ISSUE TITLE
Are all fonts + colours exported correctly in settings?

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#1113]
I've been testing out the Export Settings feature of VS. I exported all fonts and colours, and located the FSharp settings in there. Here's one: -

```xml
<Item Name="FSharp.Function" Foreground="0x00FAD53F" Background="0x01000001" BoldFont="No"/>
```
However, in VS for "F# Functions / Methods", I have RGB of 63,213,250 which is ```3FFAD5``` - which seems to suggest that the settings are being exported as GBR rather than RGB - is this supposed to be?

**Comment by dungpa** [comment]
Not sure what we can do here. Exporting settings is handled by VS.

Could you check how built-in colors are exported? For example, changing Identifier or String colors and inspect them after exporting settings.

**Comment by isaacabraham** [comment]
Sorry I never got back to this - I think it went away after I upgraded VS.
