### ISSUE TITLE
[Coloring] Add Punctuation category

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/VisualFSharpPowerTools#1122]
[Based on Build 2.1.0-a1509210048](https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1509210048)
#### Angle brackets

![](http://i.imgur.com/GvVRa2c.png)
#### Comma

![](http://i.imgur.com/jnOwE6J.png)
#### Period

![](http://i.imgur.com/ib2JwJ0.png)
#### Bar

![](http://i.imgur.com/JYpt9bM.png)
#### Paren

![](http://i.imgur.com/By1szv8.png)
#### Colon

![](http://i.imgur.com/mlfesX2.png)

proof that classification tool works

![](http://i.imgur.com/qxpPf6z.png)
![](http://i.imgur.com/1e3boJ0.png)
![](http://i.imgur.com/AmBN5rd.png)
![](http://i.imgur.com/HkTM35N.png)

---

`<` `>` `[<` `>]` `[|` `|]`  `,`  `.`  `|`  `(`  `)`  `[`  `]` `{` `}` `;`  `:`  

In VS 2015 it seems like they would fall under the punctuation classification and be colored according to 

![](http://i.imgur.com/uXSj9Q0.png)
The equivalent symbols in C# are considered puntuation

---

According to the F# Spec they're Symbolic Keywords
![](http://i.imgur.com/OqaVTC5.png)

**Comment by vasily-kirichenko** [comment]
I cannot see what are the problems with all these cases.

**Comment by dungpa** [comment]
I don't think there is any bug here. You could get `Delimiter` tokens https://github.com/fsharp/FSharp.Compiler.Service/blob/87798dc4b93fb7f813260bdf70120c94a0ec175c/src/fsharp/vs/ServiceLexing.fs#L125 and plug them into `Punctuation` category :-).

**Comment by vasily-kirichenko** [comment]
We discussed it with @cloudRoutine and he is going to make a PR with the exactly same solution you suggest :)

**Comment by vasily-kirichenko** [comment]
The feature is deprecated and will be reimplemented in VFT repo.
