### ISSUE TITLE
Function type alias is not colored

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/VisualFSharpPowerTools#1126]
At definition: 
![image](https://cloud.githubusercontent.com/assets/1169339/10197287/17016dc6-6797-11e5-93ca-51ee4344f6c3.png)

At usage:
![image](https://cloud.githubusercontent.com/assets/1169339/10197304/2aba3dfc-6797-11e5-9c51-9a0beb1df413.png)

**Comment by vasily-kirichenko** [comment]
Is it colored as function?

**Comment by OkayX6** [comment]
No :)

**Comment by vasily-kirichenko** [comment]
Is `unit -> unit` a type?

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1129
