### ISSUE TITLE
Docs should note helpful commands/hotkeys

### ISSUE THREAD

**Issue by daxfohl** [fsprojects/VisualFSharpPowerTools#1127]
In particular, I found the generate-stubs feature difficult to use, not realizing there was a command `View.ShowSmartTag` (by default mapped to hotkeys <kbd>Shift+Alt+F10</kbd> and <kbd>Ctrl+.</kbd>) to bring up that context menu.

**Comment by dungpa** [comment]
Could you please send a PR for this? We have a list of key bindings at http://fsprojects.github.io/VisualFSharpPowerTools/#Default-Keymap, it would be great to keep it up-to-date.

The source of docs is at https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/docs/content/index.fsx

**Comment by dungpa** [comment]
Closing. Feel free to send a PR if you find a better way to document shortcut keys.
