### ISSUE TITLE
General Approach to Syntax Highlighting

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/VisualFSharpPowerTools#1131]
## General Approach to Syntax Highlighting

When you look at the other languages that VS supports, each one has a full set of syntax/language construct categories so that its color scheme can exist independent of all the other languages, F# should do the same.
## Need To Add
-    F# Keywords
-    F# Identifiers
-    F# Number Literal
-    F# String Literal
-    F# Character
-    F# Comment
-    F# Documentation Comment
-    F# Compiler Preprocessor
-    F# Interface
-    F# Generic Type
-    F# Delegate
-    F# Namespace
-    F# Punctuation
-    F# Enum
-    F# Unit of Measure
-    F# Properties ( ? )

There are some ambiguous cases for classification 

```
let! use! do! yield! return! 
```

  ^ treat as keywords

```
|  ( ) [ ] [< >] [| |] { } , ;; ;  <@ @> <@@ @@> : < > (arrow brackets for generics) 
```

   ^ treat as punctuation

but for cases like  `(++)`  `(-|-)` etc, the parens should be colored the same as an operator 

`#` for flexible types should inherit the color for interfaces
`'` & `^` should inherit the color for generic types

Code Quotations should only change the background color of the spans they encompass. The foreground coloring for all of the expressions inside
the quotation should remain visible.

**Comment by dungpa** [comment]
I agree in principle.

However, C# doesn't have separate categories for literals/comments/identifiers, etc.
Historically, Visual F# Tools also use these built-in categories; we shouldn't override those because it may lead to color clashing. 
So we still have to use literals/comments/identifiers as general categories for F# code.

> Code Quotations should only change the background color of the spans they encompass. The foreground coloring for all of the expressions inside
the quotation should remain visible.

This is an ordering bug. Feel free to open a separate issue for that.

**Comment by cloudRoutine** [comment]
C++

**Comment by vasily-kirichenko** [comment]
> Code Quotations should only change the background color of the spans they encompass. The foreground coloring for all of the expressions inside
the quotation should remain visible.

That's the way it works now.

**Comment by cloudRoutine** [comment]
### C++
![](http://i.imgur.com/epvJQHx.png)

### Powershell
![](http://i.imgur.com/tAqhaa3.png)

### D
![](http://i.imgur.com/gIJcUVv.png)

Other languages have seen it fit to push the categories beyond C#'s, so I don't think we should let C# hold us back ;)

C# doesn't have its own specific categories because C# is the assumed default language, and the categories `String`, `Number`, `Comment`, `Function`, are pretty much it's property   

And It uses xml documentation comments as it's other comment category
![](http://i.imgur.com/HlqhJwF.png)

Leaving out these categories makes it harder to setup a cohesive color scheme for each language.   

Resharper and [Viasfora](https://visualstudiogallery.msdn.microsoft.com/19609469-380e-4fcf-bcde-e31caeb658b2) manage to override colors without issue.  

Historically Visual F# has made the wrong decision about these built in categories and we shouldn't continue to make their mistake.

Plus having all of the F# categories grouped together in the Options menu makes it easier for users to customize their color schemes.

**Comment by vasily-kirichenko** [comment]
I suspect most people don't use even the categories we already have. I rarely see (on screencasts and screenshots) Patterns, Mutable vars, Operators and Functions categories colorized. What's the point to introduce even more of them?

**Comment by cloudRoutine** [comment]
The reason why they don't might not be because they don't want the options, but that the process of setting up and configuring fonts and colors in VS is incredibly tedious and painful. If VFPT had an import/export configuration setting and shipped with some syntax color schemes you'd probably see a lot more of them.

**Comment by vasily-kirichenko** [comment]
I agree about a bunch of color schemes :+1:

**Comment by vasily-kirichenko** [comment]
The whole syntax highlighting feature is deprecated and will be rewritten with new colorization data available in FCS, in VFT repo.
