### ISSUE TITLE
Code Quotations Foreground Highlighting

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/VisualFSharpPowerTools#1132]
Code Quotations should only change the background color of the spans they encompass. The foreground coloring for all of the expressions inside
the quotation should remain visible.

@vasily-kirichenko  I uninstalled VFPT before taking this screenshot.
[Reinstalled VFPT using this build](https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1509301808)
![](http://i.imgur.com/K4yUMR6.png)

```
    type Condition (expr: Expr<bool>) =
        member __.Expr = expr

    let (|AAA|_|) _ = Some ()
    let func x y = x + y
    let x = <@ Condition <@ 3435 > 243 @> , "some string", 
                typeof<bool> ,(|AAA|_|) () , 22::[] ,
                [| 22.0, 2234.0 |], func 2 5 , (+) 10 13, 
                "operator" = "red?" , @"string" 
            @>
```

**Comment by vasily-kirichenko** [comment]
That's how it looks like in VS 2013 (without the @dungpa fix):

![image](https://cloud.githubusercontent.com/assets/873919/10241199/73cdbcdc-68ee-11e5-8fb1-6865542c5868.png)

Strangely, the only thing that's wrong is that the AP usage is not colored (the obvious but with `let x = ` being colorized as quotation aside).

**Comment by vasily-kirichenko** [comment]
The wrong quotation ranges fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1135

**Comment by vasily-kirichenko** [comment]
Seems to work OK in VS 2015:

![image](https://cloud.githubusercontent.com/assets/873919/10262206/26749482-69c6-11e5-8b87-186ba438200e.png)
