### ISSUE TITLE
Color active patterns being used as functions

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#1137]
Example:
```fsharp
    let (|AAA|_|) _ = Some ()
    let _ = (|AAA|_|) ()
```

Currently, usage of active patterns isn't being colored at all.

The reason is that we have a sanity check to rule out faulty ranges at https://github.com/fsprojects/VisualFSharpPowerTools/blob/a2abbd756b4226b71fb03946cdc9def8b3278550/src/FSharpVSPowerTools.Core/SourceCodeClassifier.fs#L234-L255. Active patterns' ranges consist of ranges for `|AAA|_|`, so right columns are 3 character far off compared to those of normal identifiers. It's tricky to fix since the lexer often looks up by right columns.

We even have an ignored failing test for this https://github.com/fsprojects/VisualFSharpPowerTools/blob/a2abbd756b4226b71fb03946cdc9def8b3278550/tests/FSharpVSPowerTools.Core.Tests/SourceCodeClassifierTests.fs#L866-L873

Extracted from #1132.

**Comment by vasily-kirichenko** [comment]
Working on it. It's indeed tricky.
