### ISSUE TITLE
Open namespace/module for exceptions

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/VisualFSharpPowerTools#1144]
It didn't manage to open ``canopy.types``

![image](https://cloud.githubusercontent.com/assets/1169339/10314111/59866ffa-6c53-11e5-94e0-369a7abe60ef.png)

**Comment by vasily-kirichenko** [comment]
In pattern matching or everywhere?

**Comment by OkayX6** [comment]
Oh I didn't try, I'll tell you that in a few secs.

**Comment by OkayX6** [comment]
It's in Pattern matching (it works if I do ```let x = new CanopyException```) :).

**Comment by vasily-kirichenko** [comment]
Thanks. Will fix it.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/VisualFSharpPowerTools/pull/1146
