### ISSUE TITLE
MEF discovery error logged in VS2015 RTM, VFSPT 2.0.0

### ISSUE THREAD

**Issue by kkm000** [fsprojects/VisualFSharpPowerTools#1145]
I was scanning the MEF composition log `%LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache\Microsoft.VisualStudio.Default.err` for an unrelated reason, and stumbled at this message:

```
FSharpVSPowerTools.Folders.FSharpProjectSystemService.ctor(dte): expected exactly 1 export of EnvDTE.DTE but found 0.
   part definition FSharpVSPowerTools.Folders.FSharpProjectSystemService
```

I do not know if it is expected or not. I cannot also tell if any functionality is impaired, but I may easily be missing something. Just thought you should know.

**Comment by dungpa** [comment]
@kkm000 Thanks for letting us know.

The error comes from the Folder Organization feature. Could you enable the feature in General options dialog and try out whether it's still working?

**Comment by dungpa** [comment]
Closing since there is no real error here.
