### ISSUE TITLE
[Outlining] Missing functionality

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1152]
- [x] menu page for outlining where you can check which language constructs 
 - [x] you want outlined
 - [x] should be collapsed by default 
- [x] `open` blocks 
- [x]  `#*` blocks
- [x] `and` for mutually recursive types and functions 
- [x] lists
- [x]  arrays
- [x] attributes
- [x] computation expression
- [x] `if`
- [x] `else`
- [x] `elif`
- [x] `then`
- [x] `then` in constructors
- [x] `with` in object expressions
- [x] `member` in object expressions
- [x] `member` in type extensions
- [x] `match` 
- [x] lambdas
- [x] list comprehensions
- [x] `for` 
- [ ] `(* *)` comments 
- [x] `///` comment blocks
- [x] `//` comment blocks
- [x] semantically highlighted tooltips

**Comment by vasily-kirichenko** [comment]
Standard key bindings do not work. No context menu either.

**Comment by dungpa** [comment]
It seems that we're missing a lot of ranges of important constructs. I wonder whether we should make use of DepthParser here; it has lots of functions for processing ranges https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/DepthParser.fs ? 

There are different ways of using DepthParser: (1) Use their range functions (2) Use their main functions (3) Use their tags from a tag aggregator.

Either way, I think it's still better to recreate the logic one more time.

**Comment by dungpa** [comment]
I can take care of the key binding stuff. A command handler is missing here.

**Comment by vasily-kirichenko** [comment]
As we plan to add settings for what kind of symbols are outlined and what of them are collapsed by default, we should keep "kind" of block (module level N, let binding level N, DU, class, record, enum, PM etc.) alongside with it. It makes DepthParser unusable for the task.

**Comment by dungpa** [comment]
I understand that people want to control the depth of outlining. Why do we treat some constructs better than others? It seems too complex without added benefits.

Why don't we support all constructs above (if possible) and allow controlling outlining depth?

**Comment by vasily-kirichenko** [comment]
@dungpa ok
As you working on key bindings, are you sure "Collapse to definitions" will work?

**Comment by dungpa** [comment]
I'm not sure, but it's no harm to try. I'll only get to that in a few days when I have Internet at home.

**Comment by dkinitiate** [comment]
Keybindings work on my machine. Both via VsVim bindings, and via the normal bindings, and via the Edit menu.

**Comment by vasily-kirichenko** [comment]
Try it in experimental instance.

**Comment by vasily-kirichenko** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/pull/1159

**Comment by dungpa** [comment]
@dkinitiate Maybe another extension has implemented that for you. Possibly Python Tools for VS, NodeJs Tools for VS, PowerShell Tools for VS, etc.

**Comment by cloudRoutine** [comment]
@dungpa  `Ctrl+M, Ctrl+X` & `Ctrl+M, Ctrl+A` work for me too

**Comment by vasily-kirichenko** [comment]
Lots of missing features have been implemented in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1175 

What's left is a settings page and handling comments of all kinds.

**Comment by dungpa** [comment]
I'm working on semantically highlighted outlining hints.

**Comment by vasily-kirichenko** [comment]
@dungpa :+1: :+1: :+1:

**Comment by bleis-tift** [comment]
Can you treat the scope block?

```fsharp
begin
  let x = 10
  printfn "%d" x
end
(
  let x = 10
  printfn "%d" x
)
```

**Comment by vasily-kirichenko** [comment]
This is what customization dialog look like in IDEA:

![image](https://cloud.githubusercontent.com/assets/873919/10686260/efcfe99a-796a-11e5-8d0e-1273753ea3ed.png)

**Comment by dungpa** [comment]
We have lots of checkboxes in General Options dialog that uses WinForms. If you like more fancy solutions, we can look into Lint Options dialog in WPF :-).

**Comment by dungpa** [comment]
The only missing thing is block comment support. I'm gonna open a separate issue to track it.
