### ISSUE TITLE
VSIX is not installed into an experimental VS instance during debugging

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1155]
1. Change our usual Exp prefix to something else so the cmd args are like `/rootsuffix Exp5 /log`
2. Start debugging
3. VS pops up
4. No VFPT installed in it

**Comment by dungpa** [comment]
You need to bump VSIX version. Nothing is done if VS can't see a newer version of an extension.

**Comment by vasily-kirichenko** [comment]
@dungpa it does not help :(

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/commit/01099ec0de228524f1e482c9f0451ba1b0b58af9
