### ISSUE TITLE
Performance Discussion: CPU Stress, Large Files, Large Solutions, Memory Stress, Enabled Features etc.

### ISSUE THREAD

**Issue by dsyme** [fsprojects/VisualFSharpPowerTools#1160]
I've been looking into the CPU and Memory usage of VFPT briefly.  Repro using default settings with the latest VS gallery version:
- Open VS2015
- Open the big file "TypeChecker.fs" (without being in a project) from github.com/fsharp/fsharp or FCS
- Wait for CPU acquiesce on the system
- Make a one character change to the file and look at CPU and memory stats

On my laptop, the processing after a one character edit burns ~25 seconds of CPU time (quite a lot of it consuming 2 cores).   This feels like too much.

I started to go through the VFPT features systematically (and very manually) to work out what's taking memory and CPU when editing a large standalone file like this.  Here's what I see for the different features: 

| Feature | CPU | Memory |
| :-: | :-: | :-: |
| addin disabled | 3 sec/edit |  |
| addin enabled, all features disabled | +0 sec/edit | +120MB |
| Auto gen XML doc | +0 sec/edit  (?? on use) | +0MB |
| Source Code Formatting | +0 sec/edit  (?? on use) | +0MB |
| Navigation Bar | +0 sec/edit | +0MB |
| Highlight References | +0 sec/edit (+6sec on first use after edit) | +200MB (after use) |
| Rename Refactoring | +0 sec/edit  (+6sec on first use after edit) | +80MB (after use) |
| Indent Guides, Depth Colorizer | +2 sec/edit, but also got some long blocking (Gen2 GC?) pauses | +110MB (after use) |
| Navigate To | +0 sec/edit  (?? on use) | +80MB (?? on use) |
| Colorize (no gray out options) | +7 sec/edit  (?? on use) | +190MB |
| Colorize (gray out unused opens) | +27 sec/edit  (?? on use) | +210MB |
| Colorize (gray out unused defns) | > 600sec on first open and each edit | +100MB |
| QuickInfo Panel | +6 sec/edit | +190MB |
| FSharpLint | +12 sec/edit | +40MB |

There are some other features which I didn't check. 

Of these features, these stand out as being performance hogs:
- colorization
- "gray out" colorizations 
- FSharpLint 
- the QuickInfo Panel 

To be honest these are all currently probably too greedy to have them on by default - or perhaps you can afford one of these on by default  (unless you reduce costs) but I suspect not all. The "gray out" colorizations are off by default already but FSharpLint and QuickInfo panel look like perhaps they shouldn't be on by default. 

That said, I know there's been a lot work into performance in the last release and perhaps the CPU loads are now within system limits.  But proportionally, FSharpLint and QuickInfoPanel seem to be more performance intrusive than other features (I'm sure you know this) and should be the first ones for people to disable.

Another stress test is to open the F# compiler solution (fsharp.sln or all-vs2013.sln). Apart from startup the CPU times seem while editing to be much the same for the "single file" case above which is good - most edits should not incur a whole-project check.  Under the default settings, a single change to TypeChecler.fs soaks ~30seconds of CPU time.  With FSharpLint disabled it soaks ~15 seconds

Based on the above I'd recommend we consider turning FSharpLint and QuickInfo Panel off by default - on performance grounds.  Or somehow degrade this functionality automatically (e.g. reduce update frequency) when the system is under stress.

Best regards
don

**Comment by dsyme** [comment]
(One reason I'm mentioning  this is because I was using the new version today, editing FSharp.Compiler.Service became unusable after about 10 minutes.  However it seemed to be doing better than previous versions. This was even after disabling FSharpLint and QuickInfoPanel)

**Comment by vasily-kirichenko** [comment]
Don, am I understand correctly that Visual F# Tools internal compiler service is able to recheck `TypeChecker.fs` in 3 seconds? Assuming that FCS as fast as the VFT's CS, 22 seconds is VFPT overhead? I hardly believe it. We should test FCS on that file independently (outside VFPT). I profiled VS + VFPT many times and always almost all time was spent somewhere deep in FCS.

**Comment by vasily-kirichenko** [comment]
Interesting why the degradation? Something wrong with FCS caches I guess.

**Comment by vasily-kirichenko** [comment]
I profiled with Highlight references enabled (only). It took about 20 seconds while CPU was loaded at 25% (4-core). 3 threads were working (+ 1 GC one):

![image](https://cloud.githubusercontent.com/assets/873919/10466695/4d33a19a-71fe-11e5-8b76-b90da96e5fa2.png)

First:

![image](https://cloud.githubusercontent.com/assets/873919/10466647/fb5eadb0-71fd-11e5-8a2a-d9abaa5e0a31.png)

Second:

![image](https://cloud.githubusercontent.com/assets/873919/10466637/e807ce90-71fd-11e5-8717-a127af027f95.png)

Third:

![image](https://cloud.githubusercontent.com/assets/873919/10466621/d2d76c24-71fd-11e5-91b7-266069335931.png)

I cannot see anything related to VFPT. Everything is type checking.

**Comment by vasily-kirichenko** [comment]
With VFPT disabled:

![image](https://cloud.githubusercontent.com/assets/873919/10466870/3c6efb10-71ff-11e5-9ab9-568ec8e9e313.png)

Now we have one working thread (dotTrace does not show stacks for the bottom thread, so it's GC or something other unrelated), it's the type checker and it magically has done the job in 3 seconds. 

I make a conclusion that FCS is ~5 times slower at checking a file in project than VFT's compiler service.

**Comment by dungpa** [comment]
@dsyme I think the slowness on FSharpLint integration is an oversight. We only rely on untyped ASTs so it should be fast enough.

I did some improvements on Lint and QuickInfo in the new build, could you please check https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510132010/artifacts?

**Comment by dsyme** [comment]
Great to be able to get those profiling reports.  

Also, let me say that the latest version is a _huge_ improvement.  Those improvements are why I'm trying again on the really big solutions that I need to work on (previously I had deactivated many VFPT features on really big solutions).

I do want to go through things carefully, but the overall point was that the CPU budget feels a bit strained by a couple of the features.  Not to breaking point (memory is a still bigger problem in large solutions) but I wanted to document which specific features currently seem to be taking CPU time. Certainly the right long-term path is to get all the features right down under a smallest-possible budget.

Can you list out the _exact_ steps to get the figures for Highlight References, especially the "20 seconds" figure?  i.e. 

* which file you opened (I assume TypeChecker.fs, out of project context?)

* whether it includes startup time for devenv.exe (which I don't include)

* did you waited for things to acquiesce before starting profiling and editing?

* what edits you made?

* where the cursor was, i.e. did it trigger a highlight-references?

All things being equal FCS will be the same as VFT - at its core it's the same code being run by the same VM.  However there are other differences in play: for example:

* FCS's FSharp.Compiler.Service.dll is not NGEN'd but VFT's FSharp.LanguageService.Compiler.dll is.  From my knowledge of the CLR this will make no difference at all and I wouldn't even bother investigating it at this stage.  However it will lead to a 5-8 second extra startup cost to JIT the compiler code.

* VFPT is making different requests compared to VFT, and that can lead to duplicate work (work which may currently be necessary).  

* VFPT is making more requests compared to VFT, which might lead to more pressure on caches

* FCS uses different caches to VFT

OK... With nothing but highlight references enabled the table shows this for single-character "insert a space" edits in an enormous file (TypeChecker.fs) out of project context (no solution loaded):

* zero extra CPU overhead before highlighting a symbol

* 6 seconds extra CPU overhead the first time you highlight a symbol after an edit

I can recheck those figures if needed, they are only approximate.

My belief is that the 6 seconds would come from a 2 x parsed-and-check of the file (6 = 2x3, 3 is how long VFT takes).  The requests you are making for symbol information likely means that there are  two  checks of the file by FCS (once as part of the "background" incremental build, and once as an "active" request).  I think more visibility of the FCS requests being made would be helpful here.

It's only with Colorize, QUickInfoPanel and FSharpLint that I saw what felt like really significant extra overhead that added up to that 22seconds - and FSharpLint was responsible for most of that.This makes sense as these are the "active" features that require constant processing.

**Comment by dsyme** [comment]
BTW note that the memory costs for the different features mentioned above are not additive - when two features are enabled, they share a lot of FCS symbol/type-checking-results resources.

**Comment by 7sharp9** [comment]
In xamarin studio we also have similar issues, one thing Ive noticed is that the request to re-parse callback seems to get called if you request type checks too frequently.

i.e. If I make two requests for type checks 600ms apart the compiler will tell me that the file is dirty and need re-parsing on the second request …which then causes me to request another type check.

**Comment by vasily-kirichenko** [comment]
@7sharp9 but we have this logic https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L210-L215
which should prevent type checking a file until FCS is done with the previous one.

**Comment by vasily-kirichenko** [comment]
I profiled with VS Concurrency Visualizer with custom markers (see https://github.com/vasily-kirichenko/FSharpVSPowerTools/commit/5436dd4c5543f78f492470d17168c5c05e1e74fc)

![image](https://cloud.githubusercontent.com/assets/873919/10478510/c8ccfad2-7266-11e5-8b89-ab52b408dcb2.png)

`GetFSharpSymbolUse` (the big blue span) took 4.5 seconds which is comparable with what VFT can do (~3 seconds).

Small blue spans are `getTags` - it's called by VS to get tags, we see that it's called just after `GetFSharpSymbolUse` had finished and I confirm that the tags are appear quickly (in 4.5 seconds).

After `GetFSharpSymbolUse` had finished FCS starts to parsing and checking the whole project (!!!), see thread #9744. The gray rhombus are `FileChecked` FCS events:

![image](https://cloud.githubusercontent.com/assets/873919/10478666/dc894890-7267-11e5-82e0-7fdbfcbe929d.png)

The last event is `ProjectChecked`:

![image](https://cloud.githubusercontent.com/assets/873919/10478704/25cd7756-7268-11e5-8a11-83b0d88178d1.png)

I think it's clear that the problem with this particular scenario is that we call `StartBackgroundCompile` for unknown reason here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L359

@dsyme @7sharp9 could you comment on this ^^^ ?

**Comment by vasily-kirichenko** [comment]
Hm. I commented that line (https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/LanguageService.fs#L359) and it has not helped at all - FCS still makes full project check.

**Comment by vasily-kirichenko** [comment]
After commenting that line FCS stops performing full project checking.

**Comment by vasily-kirichenko** [comment]
Same scenario, now I'm profiling with all features which do not require project checking on:

![image](https://cloud.githubusercontent.com/assets/873919/10480440/e2347a70-7272-11e5-8031-85219a47dc00.png)

![image](https://cloud.githubusercontent.com/assets/873919/10480427/d8b7c3e4-7272-11e5-8f3f-cc98857c5f2b.png)

Notes:
* there are three long `ParseAndCheckFileInProject` calls, performed sequentially one after another 
 * first (after a space was inserted) took 4.3 seconds which is ok (the top large blue span)
 * second and third calls took ~600 ms each, which I think *far too slow for cached results*
* `GetFSharpSymbolUse` was waiting for the last P&C, so it took so long.
* there are two (or more) very fast `ParseAndCheckFileInProject` calls, like this:
![image](https://cloud.githubusercontent.com/assets/873919/10480664/23d4da5a-7274-11e5-8ea9-41c8bc5a47fa.png)
*which is very strange. I assume there should be one long P&C + ten or so (one per feature) very fact calls (milliseconds).*

**Comment by vasily-kirichenko** [comment]
The version with `StartBackgroundCompile` removed (+ "Gray out unused opens" does not need project check results) is here https://github.com/fsprojects/VisualFSharpPowerTools/pull/1168 

I believe FsLinter should be profiled separately, feeding `TypeChecker.fs` AST to it (it looks like the rules can be called in parallel?)

**Comment by vasily-kirichenko** [comment]
About linter. I profiled VFPT with it enabled on same scenario as above, but on my laptop. Parse&Check took 12 seconds, Linter - 8 seconds (linting itself):

```fsharp
let m = Markers.EnterSpan "Lint"
                let res = 
                    Lint.lintParsedFile
                        { Lint.OptionalLintParameters.Default with Configuration = Some config }
                        { Ast = ast
                          Source = source
                          TypeCheckResults = None
                          FSharpVersion = version }
                        doc.FullName
                m.Leave()
```
![image](https://cloud.githubusercontent.com/assets/873919/10494582/c522e1cc-72bf-11e5-8532-54073aaa56ac.png)

However Linter runs in separate thread, it took too much time and definetly should be profiled. /cc @duckmatt

**Comment by duckmatt** [comment]
I'll have a look at improving thee performance of the linter

**Comment by 7sharp9** [comment]
Is linter being given the parse and check results?

**Comment by vasily-kirichenko** [comment]
Parse results only, see the snippet above.

**Comment by dsyme** [comment]
Another general observation....  

The performance of Visual Studio really tanks whenever memory gets above 2.5GB.  That feels like a "hard" limit where the CLR just starts to GC too often, with long pauses on the UI thread.  It sometimes takes me minutes to save my work and exit when it gets into this state.  I only ever reach this limit when using VFPT on large solutions.

It's possible that VFPT should have some "situation critical" code that effectively starts to disable features (and reduce FCS cache sizes?) when we get to this limit.  FCS cache sizes can't currently be adjusted mid-flight though we could add that.  Or we could put this logic in FCS - but FCS can be used in 32-bit or 64-bit mode and this is really a problem coming from 32-bit memory limits.

**Comment by vasily-kirichenko** [comment]
I think the number of VFTP features enabled has no relation with memory consumption because all the memory is FCS caches. It's easy to reach 2.5 GB - just run "Find all refs" for a common symbol like `string` on a large solution. 

It would be nice if VFPT could pass FCS a callback which would return a status like "shrink the caches immediately" or "everything is ok" and it would be called periodically.

**Comment by dungpa** [comment]
@dsyme Is there any way to set FCS cache size limit? Let's say if the cache grows more than 1G, it should drop some old entries to have space for new entries.

**Comment by vasily-kirichenko** [comment]
@dungpa the caches use weak references for some of data (I cannot understand the logic in its fullness though), so it should do just that - throw data in case of memory pressure.

**Comment by dsyme** [comment]
@vasily-kirichenko  @dungpa  Not enough data held weakly to solve the problem, partly because weak data gets thrown away a bit too aggressively.

I agree that a "clean things out now!"  feature is needed to empty and downsize the FCS caches.

**Comment by dsyme** [comment]
Can I ask, why do you create [5 FSharpChecker instances](https://github.com/fsprojects/VisualFSharpPowerTools/search?utf8=%E2%9C%93&q=FSharpChecker)?  I think you should only create one.  AFAIK each holds it's own caches.

**Comment by vasily-kirichenko** [comment]
> I agree that a "clean things out now!" feature is needed to empty and downsize the FCS caches.
I think the feature should be less aggressive, like "clean up some of caches". Then we could periodically check how much memory devenv.exe uses and if it's still too high, call it again.

**Comment by vasily-kirichenko** [comment]
> Can I ask, why do you create 5 FSharpChecker instances? I think you should only create one. AFAIK each holds it's own caches.

Wow! Will check it immediately.

**Comment by vasily-kirichenko** [comment]
Omg. Will fix it.

**Comment by vasily-kirichenko** [comment]
Actually everything is ok and we have single FCS instance. I cleaned thing up a bit though here  https://github.com/fsprojects/VisualFSharpPowerTools/pull/1173

**Comment by vasily-kirichenko** [comment]
What's more, number of `FSharpCheck` instances does not matter anyway since the caches are static.

**Comment by 7sharp9** [comment]
In XS memory is a massive issue when working with the F# compiler solution.

**Comment by vasily-kirichenko** [comment]
@7sharp9 is it 32-bit too?

**Comment by 7sharp9** [comment]
Currently, yes.

**Comment by vasily-kirichenko** [comment]
What's the reasons?

**Comment by 7sharp9** [comment]
There are some issues relating to making Gdk 64 bit I think.

**Comment by dsyme** [comment]
@vasily-kirichenko   Great to have that cleaned up.  AFAICS the caches are not static, see

* https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2182

* https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2240

* https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2908

**Comment by vasily-kirichenko** [comment]
@dsyme great! I think the caches used to be static.

**Comment by dsyme** [comment]
@vasily-kirichenko  Yes I think so.  There's a module-static one here but that should really be made instance too: https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/IncrementalBuild.fs#L1090

**Comment by dsyme** [comment]
@vasily-kirichenko I see an FSharpChecker() call in FSharpLint here: https://github.com/fsprojects/FSharpLint/blob/d3d5d3e77dbdf5ed33dba13f2c2dd016e543f73f/src/FSharpLint.Application/Lint.fs#L312.  However some of the code also accepts the checker as a parameter

Are you passing your one-and-only FSharpChecker to FSharpLint or is it using its own one?

**Comment by dungpa** [comment]
We use `lintParsedFile` so cached untyped ASTs are used for linting.

**Comment by dsyme** [comment]
ok, thanks

**Comment by dsyme** [comment]
@vasily-kirichenko @dungpa Can you take a look at this please? https://github.com/fsharp/FSharp.Compiler.Service/pull/443

This may be of use in reducing the impact of the hitting-maximum-process-memory-grinds-everything-to-a-halt conditions I get when using VFPT on FSharp.COmpiler.Service.

**Comment by dsyme** [comment]
@vasily-kirichenko @dungpa If you have time, perhaps we could do a Skype session in the next few days.  There are some interesting results from observing the FCS queue - both in terms of too many requests being made (when perhaps they shouldn't be), and in terms of FCS not processing the requests fast enough because of a lack of caching of particular items.

But perhaps more importantly I want to show you how to observe the requests in the FCS queue arising as a result of the calls you're making.  See https://github.com/fsharp/FSharp.Compiler.Service/pull/445.

Some observations from what I've seen so far that aren't covered in that PR

* Every move of the cursor loads up a request to ``ParseAndCheckFileInProject``.  That's fine since these are cached (though the caching was misfunctioning in some cases - fixed by the PR).  But just be aware that you are throwing a lot of requests at FCS on every cursor movement - even if previous requests have not yet completed.  This is certainly the most natural way to write the VFPT code (presumably you make sure that you only display results from these async requests if the cursor is still in the right place by the time the results come back), but it relies on FCS calls being cheap and cached more than I had realised.  

To help with this, I've both fixed the caching to give back results from repeated requests, and implemented cancellation checking as operations get dequeued from the FCS operations queue.  Although the operations themselves can't be interrupted, if you have an async stuck at a ``let! ... = ParseAndCheckFileInProject...``, i.e. before that request actually gets processed by the FCS queue, then the operation will cancel correctly as it gets dequeued.  

* You are calling ``GetProjectOptionsFromScript`` a lot even when the input file is a ``Foo.fs`` non-script file.  I think [the depth colorizer is the culprit here](https://github.com/fsprojects/VisualFSharpPowerTools/blob/0fc4314320fb97cdad9249da1bf3fe21eaafb160/src/FSharpVSPowerTools.Core/DepthParser.fs#L343).  This call is not cached when the source text is changing.  I think you should be getting the project options here once for the file.

**Comment by 7sharp9** [comment]
In XS we only get the project options *once*, until the current project changes.  Then again we have to use much heavier checker options requests in order to service PCL aware checking results.

**Comment by vasily-kirichenko** [comment]
> You are calling GetProjectOptionsFromScript a lot even when the input file is a Foo.fs non-script file. I think the depth colorizer is the culprit here.

Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1177

**Comment by vasily-kirichenko** [comment]
> If you have time, perhaps we could do a Skype session in the next few days. 

I'm afraid my spoken English will be a big issue :(

**Comment by dsyme** [comment]
@vasily-kirichenko No problem, we can do it via github

**Comment by dsyme** [comment]
@vasily-kirichenko Which IM do you use to chat? thx

**Comment by vasily-kirichenko** [comment]
skype vasily.kirichenko

**Comment by vasily-kirichenko** [comment]
I tried to open 2.5GB VS dump in VS and it failed with Out of memory error :( dotTrace cannot even connect to it, it failed with a COM error.

**Comment by dungpa** [comment]
I don't have time in the near term. Too many things are going on with personal life atm.

@vasily-kirichenko Don can deal with my broken spoken English. I'm sure he can deal with yours. Please give it a try :-).

**Comment by dsyme** [comment]
@vasily-kirichenko  Yes direct debugging on the massive dumps is very hard

**Comment by vasily-kirichenko** [comment]
I've managed to get a snapshot of 1.4GB VS. Half of the managed memory is 16MB `byte[]` objects in LOH.

**Comment by vasily-kirichenko** [comment]
Rebuilding VFPT solution adds 100MB, force GC has not free it.

**Comment by vasily-kirichenko** [comment]
Just reached > 2GB on VFPT solution (> 3GB in peak (!)). Unfortunately, dotMemory cannot get snapshot, only total numbers:

![image](https://cloud.githubusercontent.com/assets/873919/10563537/88ed3afc-7596-11e5-9c83-4fb15557f762.png)

**Comment by vasily-kirichenko** [comment]
VS cannot open the dump either 
![image](https://cloud.githubusercontent.com/assets/873919/10563604/8eafa5d6-7598-11e5-9230-8d49d0f7bce3.png)

**Comment by vasily-kirichenko** [comment]
I added logging state of all FCS caches, see here https://github.com/vasily-kirichenko/FSharp.Compiler.Service/commit/21d377ca36cae9a87ab80e6212ca11b2a805a28d and here https://github.com/vasily-kirichenko/FSharpVSPowerTools/commit/32ec1f5f962128ab5d6977ee64df4cc1a0094cd9

Unfortunately, I've not found any suspicious behavior: all the caches stayed at about 5-8 in size, except `ilModuleReaderCache`, which grown to 75 entries and had been stayed at this size forever (it was tested on VFPT solution). And the devenv.exe process reached > 2GB, as usual. 

@dsyme have I logged all the FCS caches? If so, what else can eat the memory? As I said, I cannot analyze > 2GB snapshot in VS, and dotMemory cannot profile it either.

**Comment by buybackoff** [comment]
I have noticed a consistent slowdown when I have multiple errors in F# files. E.g. if I need to remove a dll reference or do some other big refactoring, on a powerful PC the experience becomes painful, on MacBookAir I have to turn off Power Tools completely because everything freezes and hangs. With Power Tools turned off, even MBA could handle a solution c.3 times larger than the size of Spreads/Deedle. There is some heavy activity that blocks GUI thread and it feels like it is restarted after every character input.

**Comment by dsyme** [comment]
@buybackoff If you have a consistent repro we could have a look, thanks

**Comment by buybackoff** [comment]
E.g. if I open visualfsharp main project without building proto compiler I could hardly navigate the project. Or if I remove Spreads.Core reference from Spreads.Collections CPU usage substantially increases during editing. The particular moment when VS often hangs is when squiggly red lines and red marks on the right bar disappear and then reappear.

**Comment by dsyme** [comment]
OK, I see, thanks.  Does this happen only when VFPT is enabled?

**Comment by buybackoff** [comment]
When I switch VFPT off it helps. Maybe I am reaching physical memory limits with VFPT on and start to swap on disk, but with 4Gb RAM, SSD and 10 Gb pagefile I could usually work more or less OK with 2-3 instances of VS and 20 Chrome tabs opens. I cannot tell for sure whether it is VFPT or built-in Visual Studio tools cause this.

**Comment by vasily-kirichenko** [comment]
dotTrace it please.

**Comment by vasily-kirichenko** [comment]
when devenv.exe process reaches > 2GB everything simply dies. just restart it.

**Comment by vasily-kirichenko** [comment]
I'm closing this. Performance issues should be discussed in VFT repository now.
