### ISSUE TITLE
Formatting is not working in VS2013

### ISSUE THREAD

**Issue by pavelhritonenko** [fsprojects/VisualFSharpPowerTools#1162]
Latest version of Visual F# Powertools (v2.1.0), Visual Studio 2013.

I see this error in status bar when I try to format some f# code fragment:

![image](https://cloud.githubusercontent.com/assets/2510026/10455371/935c2fa6-71c3-11e5-9b82-9306fe134789.png)

Looks like VFPT cannot find FSharp.Core 4.4.0.0

I don't have VS2015 on my machine.

**Comment by dungpa** [comment]
Thanks. I should have tested on a machine with VS2013 only.

**Comment by dungpa** [comment]
Fixed by #1267.
