### ISSUE TITLE
[Coloring] Keep old spans if new parser AST range is zero

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1205]
It should eliminate the case where while editing code becomes parsable/unparsable, which results with coloring/uncoloring all the time. The same logic is already used in Outlining feature.

**Comment by dungpa** [comment]
Any update? I see color blinking more often now because we're more responsive wrt typing than before.

**Comment by vasily-kirichenko** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/pull/1219

**Comment by vasily-kirichenko** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/pull/1230

**Comment by vasily-kirichenko** [comment]
Implemented.
