### ISSUE TITLE
[Outlining] Collapsed-by-default regions are expanded when file is opening

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1216]
![6677](https://cloud.githubusercontent.com/assets/873919/10717320/342ca9ec-7b65-11e5-8c8a-ff9f79effdc4.gif)

I'm not sure we can fix this since we get parser AST with a delay.

**Comment by dungpa** [comment]
We return outlining tags in an asynchronous manner. We can't avoid delays here.

I would say we abandon default collapsing and focus on default enabling of F# constructs. Default collapsing is a bit unusual; I don't recall any language in VS that does default collapsing.

**Comment by cloudRoutine** [comment]
I like the default collapsing a lot. I'm always going to collapse the hash directives and the opens so I'd rather the tool did it for me

**Comment by vasily-kirichenko** [comment]
OK, it's unlikely we can fix it.
