### ISSUE TITLE
[Coloring] Highlight Printf specifiers

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1232]
This is how R# does it:

![1](https://cloud.githubusercontent.com/assets/873919/10962522/fe220f34-83a9-11e5-8451-54a54631e6cf.gif)

I.e.:
* Format specifier + the formatted thing are highlighted independently from normal Highlight References feature, I mean specifiers are highlighted only if the cursor either on the specifier itself or it's on the formatting thing (not on one of its references).

**Comment by dungpa** [comment]
I'm not interested in this one. I would rather do #1130; it's so annoying to fix some simple Lint warnings manually.

**Comment by vasily-kirichenko** [comment]
The only quick fix action you can easily provide is one for trimming line endings. But, considering that it make absolutely no harm and can (or should) be turned off, I don't see any value in #1130 for now.

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1257
