### ISSUE TITLE
Improve code editing experience

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1236]
Editing code with VFPT turn on is *dramatically* worse than one having it off. Typing / deleting / moving code is annoying slow compared to completely smoothness of bare VFT. 

I believe this is the main reason why people do not use VFPT on real world projects.

**Comment by dungpa** [comment]
Can you identify a number of reproducible scenarios we would like to improve upon?

**Comment by vasily-kirichenko** [comment]
1. Open VFPT solution, type any code anywhere.
2. Switch off VFPT, restart VS, repeat #1.

If you still do not convinced, do the same in `TypeChecker.fs` in FCS solution.

**Comment by vasily-kirichenko** [comment]
I'm not saying it's unusable (however, I restarted VS 4 times in 2 hours because it quickly reached 2.5GB and became unusable), but typing performance is not absolutely smooth. I believe we can make it as good as bare VFT.

**Comment by dungpa** [comment]
On a related note, I started a branch to add performance test https://github.com/dungpa/PowerTools/tree/perf-tests. Here is the long-term plan:

- Use some common scenarios to record our performance metrics. We can start with (1) Open TypeChecker.fs and do semantic highlighting for the whole file (2) Choose a common symbol in FCS and invoke Find All References.

- Record statistics with relevant metrics e.g. CPU time, GC stats, memory usage.

- Keep a baseline of statistics to compare with old commits/tags/versions.

- All scenarios should be performed automatically as unit tests. Performance results will be extracted and published as AppVeyor artifacts.

These performance tests don't replace profiling, they help prevent regression when performance might change in a subtle way.

**Comment by vasily-kirichenko** [comment]
This PR https://github.com/fsprojects/VisualFSharpPowerTools/pull/1237 moved everything out from UI thread and code editing is now very smooth (at least for me, including `TypeChecker.fs`).

@dungpa Really great idea, but I'm afraid AppVeyor will produce very different results for CPU time from build to build.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1237
