### ISSUE TITLE
IdentifiersMustNotContainUnderscores conflicts with common usage of leading underscore

### ISSUE THREAD

**Issue by curtnichols** [fsprojects/VisualFSharpPowerTools#1243]
In **Lint** settings, the rule NameConventions/IdentifiersMustNotContainUnderscores warns of identifiers that have a leading underscore, which is a useful and common convention (see [here](https://fsprojects.github.io/VisualFSharpPowerTools/faq.html#Why-are-object-identifiers-in-members-marked-as-unused)).

![image](https://cloud.githubusercontent.com/assets/2353284/11097254/41ce2f30-8853-11e5-86ee-21f1f5620fdf.png)

This rule is enabled by default. Perhaps it should be modified to allow the leading underscore?

**Comment by vasily-kirichenko** [comment]
Please report this to FsLinter repository, it should be fixed there.

**Comment by duckmatt** [comment]
@curtnichols This [currently open here](https://github.com/fsprojects/FSharpLint/issues/119) I've added it to the next milestone, so should be in the next release of the linter

**Comment by curtnichols** [comment]
Thanks!
