### ISSUE TITLE
Add new Item Below inside Folder error

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/VisualFSharpPowerTools#1246]
When adding an Item inside a folder created by VFPT 

![](http://i.imgur.com/0LqCwyx.png)

the item appears at the bottom of the project instead

![](http://i.imgur.com/xeMSwW2.png)

when I try to use VFPT to move that file into the proper folder I get the error

![](http://i.imgur.com/plOCWLj.png)

then immediately after when I unload and then try to reload the project I get the error

![](http://i.imgur.com/O6swtTq.png)

when I check the `.fsproj` to correct the error I can see that the path of the folder isn't being added to the item in the xml file 
![](http://i.imgur.com/LB4wgWd.png)

because it's not  `<Compile Include="GUI\GeneralOptionsPage.fs" />` it seems like GUI is being asked to be rendered twice causing the error 

however it does match the folder the file was created in 

![](http://i.imgur.com/2mpe36i.png)

**Comment by dungpa** [comment]
Is this VS 2015 RTM? There are some bug fixes in F# project system in there. If it is VS 2013, there is not much we can do.

**Comment by cloudRoutine** [comment]
![](http://i.imgur.com/GdauHmg.png)

**Comment by dungpa** [comment]
It's great if you can make a minimal repro and submit to https://github.com/Microsoft/visualfsharp. It's a bug in F# project system that can't be fixed here.

**Comment by dungpa** [comment]
Closing. Feel free to report it to VFT.
