### ISSUE TITLE
[Highlight references] Highlight definition differently

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1262]
This is how VS 2015 (pure, without R#) highlights references:

![image](https://cloud.githubusercontent.com/assets/873919/11324011/0de703e6-9135-11e5-886b-cedc3d568b68.png)

Note that the definition is highlighted differently. I'm sure there's a standard color setting for this that we could reuse.

**Comment by dungpa** [comment]
I'll do this for 2.3.0.

**Comment by vasily-kirichenko** [comment]
Great. I think it will work in VS 2015 only (and it's ok).

**Comment by dungpa** [comment]
There might be performance regression, let me know if you see it. I can't see any difference while testing on VS 2013.
