### ISSUE TITLE
[Outlining] Store state in *.suo file

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1263]
Other than it's very cool to have, @cloudRoutine said one day that it's definitely possible and a common practice.

**Comment by vasily-kirichenko** [comment]
It turns out VS 2015 *already keep* the state.

**Comment by dungpa** [comment]
Nice. We don't have to do anything then.

**Comment by vasily-kirichenko** [comment]
I will recheck though.

**Comment by vasily-kirichenko** [comment]
Yes, it works in VS 2015 out of the box.
