### ISSUE TITLE
format code will Add redundant parentheses

### ISSUE THREAD

**Issue by greatim** [fsprojects/VisualFSharpPowerTools#1265]
my code:
    type TernaryExp = 
        
        static member Ternary(value, truePast : 't, falsePast : 't Lazy) = 
            if value then truePast
            else falsePast.Value
        
        static member Ternary(value, truePast : 't, falsePast : 't) = 
            if value then truePast
            else falsePast
    
    let inline ternaryExpHelper< ^t, ^a, ^b when (^t or ^b) : (static member Ternary : bool * ^a * ^b -> ^a)> v (a, b) = 
        ((^t or ^b) : (static member Ternary : bool * ^a * ^b -> ^a) (v, a, b))

Bug found in last line，once I format the code , it add a pair of redundant parentheses,format more, add more

**Comment by dungpa** [comment]
Thanks, I have a fix. Will push it shortly.
