### ISSUE TITLE
Please turn off end-of-line whitespace warnings by default

### ISSUE THREAD

**Issue by dsyme** [fsprojects/VisualFSharpPowerTools#1266]
I'm spending some time working with a finance industry customer. I just upgraded VFPT in that context and the "end of line whitespace warnings" came on by default. I found this felt wrong: I've personally never cared about end-of-line whitespace in 30 years of programming, so for me these warnings are spurious, and that's likely to be the case for a substantial number of other people - except where the majority of people on a project are using specific editors that (mistakenly IMHO) remove whitespace by default.

So I recommend this warning be off by default (or FSharpLint should be off by default, which I've suggested for possible performance reasons). It seems wrong for beginners (or even experienced F# programmers) to be asked to have an opinion about this setting and to then have to dig into options and disable something. The warning squiggles are intrusive enough that the substantial number of people who don't like the setting on by default will have to go turn it off explicitly. And it seems wrong that I find myself turning off FSharpLint just to get rid of these warnings (I know I don't have to turn off FSharpLint, but it's the quickest way to make the warnings go away).

thx
Don

**Comment by vasily-kirichenko** [comment]
I completely agree on all you wrote. I've never cared about line endings either and have this particular linter rule off.

**Comment by duckmatt** [comment]
I think the linter should be off by default (or perhaps run on demand via a
context menu like the stylecop extension), there's also currently a few
warnings that can be misleading without type information which won't be a
good experience for beginners

**Comment by dsyme** [comment]
Thanks for dealing with this.  And @duckmatt, thanks for the incredible work on FSharpLint too.  it is a wonderful tool!
