### ISSUE TITLE
Moving to VS 2015 and F# 4

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1271]
What do you think guys if we move development to VS 2015 and F# 4? What can possibly go wrong?

**Comment by dungpa** [comment]
VS2015 would not be a problem. My own issue is that my dev machine is still VS2013.

F# 4.0 may be a problem. We have loosen restrictions on FSharp.Core until now; we might have to ship FSharp.Core 4.0 with the extension. I don't know which problems can arise. /cc @dsyme

**Comment by vasily-kirichenko** [comment]
Yes, we must ship FSharp.Core 4.4.0.0 as we support VS 2013. I think we should try to switch. I will (not tomorrow though).

**Comment by vasily-kirichenko** [comment]
It's obsolete since we've merged with VFT which uses VS 2017.
