### ISSUE TITLE
[Outlining] Support for keyboard shortcuts

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#1275]
Support the standard VS shortcuts for outline blocks e.g. ```CTRL M + M``` collapses / expands a block.

**Comment by dungpa** [comment]
I'm not using outlining keyboard shortcuts much. Could you give a detailed list of missing shortcuts? 

If we do this, we should do all at once.

**Comment by isaacabraham** [comment]
These are taken from VS2015 in C# projects - I believe that they are the same as older versions.

![outlining](https://cloud.githubusercontent.com/assets/1781813/11498767/d32f7578-9821-11e5-82f9-7aba2bdcd54a.png)

**Comment by isaacabraham** [comment]
cool. looking forward to this!!!

**Comment by vasily-kirichenko** [comment]
@isaacabraham Just grab the latest build from AppVeyor.

**Comment by isaacabraham** [comment]
already have :-)

**Comment by isaacabraham** [comment]
This works like a charm by the way - brilliant stuff.
