### ISSUE TITLE
Everything is very slow on a WebSharper based project

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1280]
Current master from AppVeyor in VS 2015 U1:

![1](https://cloud.githubusercontent.com/assets/873919/11583709/d3d97944-9a6d-11e5-9429-f63d92ac7e8b.gif)

The previous build works completely ok.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/11583946/62e17edc-9a70-11e5-8bb2-59fe4edc56fa.png)

**Comment by dungpa** [comment]
The screenshot looks weird. Does this happen due to Highlight References change or due to FCS upgrade? Could you check?

**Comment by vasily-kirichenko** [comment]
I installed this one https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.3.0-a1511301754 and everything is still slow :( WTF

**Comment by dungpa** [comment]
I don't see anything obvious from https://github.com/fsharp/FSharp.Compiler.Service/compare/1.4.2.0...1.4.2.1. Will try to investigate further.

**Comment by vasily-kirichenko** [comment]
I localize it: it occurs on one project only, the one which is based on WebSharper and contains much code marked with `[<ReflectiveDefinition>]` attribute.

**Comment by vasily-kirichenko** [comment]
Commented all the attributes - same behavior. Maybe it's something with the project file?

**Comment by vasily-kirichenko** [comment]
Create hello world WebSharper project - everything is fast :(

**Comment by vasily-kirichenko** [comment]
* move the cursor to another symbol

Result: 600000 disk accesses, ~4500 acceses to a single *.fs file. 

Question: WTF is happening?

**Comment by dungpa** [comment]
Could you `git bisect` to figure out when the regression comes from?

**Comment by vasily-kirichenko** [comment]
Yes.

**Comment by vasily-kirichenko** [comment]
Good news, 70670188d190b0eb0252779bd6c108880b71af53 is OK.

**Comment by vasily-kirichenko** [comment]
"C:\Program Files (x86)\Git\bin\git.exe" bisect good
23414e4babd9c129b0f87bb32a2b9508698fa119 is the first bad commit
commit 23414e4babd9c129b0f87bb32a2b9508698fa119
Author: dungpa <phananhdung309@yahoo.com>
Date:   Mon Nov 30 18:43:40 2015 +0100

    Update to FSharpLint.Core 0.0.13

:100644 100644 b248c389b544c99a6ee29dec25b6b11e0e491bf1 2feed813a7e71c433b6b4979b43856e17732ebf9 M	paket.lock
Done

**Comment by vasily-kirichenko** [comment]
https://github.com/fsprojects/VisualFSharpPowerTools/commit/23414e4babd9c129b0f87bb32a2b9508698fa119#diff-2bfb11ab4230093400363f8d70eab088R7

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1288

**Comment by dsyme** [comment]
Could you add a standalone repro steps to the FCS bug please (e.g. that doesn't involve WebSharper or isolates what's strange about WebSharper projects)?

I thought moving VFPT from FCS 1.4.2.0 to 1.4.2.1 resulted in really huge performance gains particularly w.r.t. memory for VFPT?  Or at least I've been unable to consistently use VFPT until it picked up [this commit](https://github.com/fsharp/FSharp.Compiler.Service/commit/add00eaf0789cde563ffd26163037071bae8ab97)? It would be much better not to go back to 1.4.2.0 (at least in a public release) and instead resolve the new performance problem.

**Comment by vasily-kirichenko** [comment]
@dsyme the perf problem is reliably reproduced on FSharpVSPowerTools.Logic.VS2013 and FSharpVSPowerTools.Logic.VS2015 projects in VFPT solution. 

I've made a PR with rollback to 1.4.2.0

**Comment by dsyme** [comment]
OK. Please add a simple sequence of reliable repro steps to the FCS bug.  I still have no idea from the above how to reproduce the performance problem.  The thread above mentions "WebSharper" and "move the cursor to another symbol" and "ReflectedDefinition" and "FSharpVSPowerTools.Logic.VS2013".

**Comment by vasily-kirichenko** [comment]
* open VFPT solution 
* open any *.fs file from FSharpVSPowerTools.Logic.VS2013 or FSharpVSPowerTools.Logic.VS2015 project
* note how long it takes colors and Highlight references tag to appear
* move the cursor to any other symbol
* note that it takes several seconds to Highlight references tag to appear (to compare, open any file from FSharpVSPowerTools.Logic or FSharpVSPowerTools.Core projects)
* click on another symbol and execute Rename refactoring on it
* note how long it takes the dialog to initialize itself

**Comment by dsyme** [comment]
OK thanks.  I'll try to confirm this tomorrow (and also taking into account @nosami's feedback here: https://github.com/fsharp/FSharp.Compiler.Service/issues/488).
