### ISSUE TITLE
Add Class View support

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1281]
It should be useful to survive while exploring large files like our `UntypedAstUtils.fs` or just any file in the compiler/FCS repo.

**Comment by dungpa** [comment]
I have no objection. Could we prioritize #1284 :-)? That one may change the way we maintain VFPT (probably for the better); so it would be great to have it done soon.

**Comment by vasily-kirichenko** [comment]
I agree that #1284 is much more important.

**Comment by vasily-kirichenko** [comment]
I don't think this is a useful feature.
