### ISSUE TITLE
Installing the fsharp power tools before installing adding VS2015 update 1 breaks Roslyn

### ISSUE THREAD

**Issue by KevinRansom** [fsprojects/VisualFSharpPowerTools#1295]
Hi guys,

You are probably aware of this:  https://sergeytihon.wordpress.com/2015/12/01/how-to-restore-viual-studio-2015-after-update-1-dependency-dance/

It turns out that, when the Visual F# Power Tools are installed they write to the real devenv.exe.config
It turns out ... and it would be fair to say I didn't know this either ... writing to the devenve.exe.config file interferes with the visual studio teams ability to service that file in updates.

Here is a thread discussing the navigation bar:  https://github.com/fsprojects/VisualFSharpPowerTools/issues/37
Here is the PR that causes the problem: https://github.com/fsprojects/VisualFSharpPowerTools/pull/210

There is a devenv.exe.config that is generated when VSIXs are installed.  The contents of this app config file are merged with the devenv.exe.config file when devenv is started.  So that is the right place to make the changes.

However ... that file is regenerated whenever a VSIXis installed and so just adding the line, will not be a permanent solution.  I am trying to find out from the VSIX engineering team, what the correct solution is for you.

Thank you for your patience.

Kevin

**Comment by vasily-kirichenko** [comment]
I think the correct solution is to make it a proper Visual F# Tools setting and remove the devenv config messing out from VFPT.

**Comment by KevinRansom** [comment]
I think that would be a good choice.

**Comment by dungpa** [comment]
We're more than happy to remove Navigation Bar when Visual F# Tools accommodate it. Changing devenv.exe.config is error-prone and more trouble than it's worth.

**Comment by KevinRansom** [comment]
Okay I have opened an issue on visual# tools:  https://github.com/Microsoft/visualfsharp/issues/786

It says this:  
We need an alternate mechanism to enable these features:
// App.config keys for determining whether not-shipping features are turned on or off
// Edit devenv.exe.config and place these at the end.
// <appSettings>
// <add key="fsharp-regions-enabled" value="true" />
// <add key="fsharp-navigationbar-enabled" value="true" />
// <add key="fsharp-standalone-file-intellisense-enabled" value="false" />
// </appSettings>

Because of this design the powertools who used this feature correctly, happened to cause VS update 1 to do bad things to people who use Dev 15 and the PowerTools.

**Comment by vasily-kirichenko** [comment]
:+1:
