### ISSUE TITLE
[Highlight references] Symbol definition is not highlighted after "Go to definition/Peek definition" executed

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1298]

**Comment by dungpa** [comment]
What does this mean? Do you have a screenshot?

**Comment by vasily-kirichenko** [comment]
![1](https://cloud.githubusercontent.com/assets/873919/11911884/2cdd19be-a636-11e5-8197-4d0983230765.gif)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1405
