### ISSUE TITLE
Printf tagger shows entire tuple as first specifier when using forward pipe 2/3

### ISSUE THREAD

**Issue by shanecharles** [fsprojects/VisualFSharpPowerTools#1306]
<img width="239" alt="deconstruct" src="https://cloud.githubusercontent.com/assets/4616153/12074890/f29967be-b132-11e5-8dda-79ebf8d89394.PNG">

I got this.

**Comment by vasily-kirichenko** [comment]
We don't handle `||>`, `|||>` and so on in a special way.
