### ISSUE TITLE
Peek Definition does not work for fsx files

### ISSUE THREAD

**Issue by toburger** [fsprojects/VisualFSharpPowerTools#1313]
The menu entry for Peek Definition does not exist in F# script files.

**Comment by vasily-kirichenko** [comment]
It seems to work for me:

![1](https://cloud.githubusercontent.com/assets/873919/12092017/ad67c980-b30b-11e5-8ca7-60f3a43e0f32.gif)

**Comment by vasily-kirichenko** [comment]
Catch it: Peek Definition menu item does not appear for fsx files which are not a part of any F# project (i.e. they are just included into a Solution Folder or the like).

As we don't provide the menu item explicitly, I've no idea why VS removes it from FSX files.

**Comment by toburger** [comment]
Ah yes, sorry, it was a standalone fsx file, not part of a fsproj project.
