### ISSUE TITLE
[Peek Definition] should show metadata for external assemblies and C# projects

### ISSUE THREAD

**Issue by toburger** [fsprojects/VisualFSharpPowerTools#1314]
When I try to peek into another assembly it does nothing.
F12 in contrast shows the fsi window. I think the peek behavior should be consistent with the F12 experience.

**Comment by vasily-kirichenko** [comment]
@toburger Could you provide more details? If I Alt + F12 on a symbol defined in another F# project in same solution, then it does show the definition. If you are trying to a symbol defined in an external assembly or in a C# project in same solution, then yes, it does not show generated metadata. It's knows restriction. I someone wants to fix this, go ahead.

**Comment by toburger** [comment]
Correct, same solution, different project works.
Referenced assembly doesn't work. However `Go To Definition` (F12) works.

**Comment by vasily-kirichenko** [comment]
@toburger so do you think Alt + F12 should show generated metadata just as F12 does?

**Comment by toburger** [comment]
@vasily-kirichenko I think that would be consistent.

**Comment by remusp** [comment]
Hi, I'd like to fix this issue. For starters, I forked the code and I'm looking around...

**Comment by dungpa** [comment]
@remusp Welcome. Here are a few pointers to get started:

 - Extract Navigate to Metadata as an independent service https://github.com/fsprojects/VisualFSharpPowerTools/blob/f8c54cd763de2c8a151f0318f3787a9f1985ae4d/src/FSharpVSPowerTools.Logic/GoToDefinitionFilter.fs#L225-L305 (marked with `Export` attribute)

- `Import` that service to GotoDefinitionFilter
- `Import` the service to PeekDefinition and branch it out similar to what has been done it GotoDefinitionFilter https://github.com/fsprojects/VisualFSharpPowerTools/blob/f8c54cd763de2c8a151f0318f3787a9f1985ae4d/src/FSharpVSPowerTools.Logic.VS2015/PeekDefinition.fs#L86-L90

**Comment by remusp** [comment]
I know it's been a while, but here goes:
- I extracted Navigate to Metadata as a separate service
- imported it to GotoDefinitionFilter (via existing GoToDefinitionFilterProvider)
- imported it to PeekableItemSource (via existing PeekableItemSourceProvider)

I guess I now have to add a branch in PeekableItemSource.getDefinitionRange that uses NavigateToMetadata and returns Some (span, range) but so far I haven't been able to. Could you point me in the right direction?

I tried to just call NavigateToMetadata, guessing it will open the document as a side-effect, but I was wrong: https://github.com/remusp/VisualFSharpPowerTools/blob/0fd2b1f3fe8a6cd2291af21c72c47e72d21dccfd/src/FSharpVSPowerTools.Logic.VS2015/PeekDefinition.fs#L90-L94

Also, do you have any suggestions about how I could debug? The test visual studio instance that is created is unable to open any projects so currently I am using the vsix from the Debug folder in the actual VS instance I also use for development.

**Comment by vasily-kirichenko** [comment]
Please rebase on master.

Exp instance of VS 2015 is completely broken for me. I've not managed to fix it on several machines. So you have to build the VSIX in Debug mode, remove the previous version manually, install the VSIX, launch a normal VS instance, open a solution in it, then attach to it.

**Comment by dungpa** [comment]
@remusp I think you're on the right track. You have to supply the information needed by `PeekableItemSource`. It could be done by breaking `NavigateToMetadata` into two functions:

 (1). `GenerateMetadata` that generates the signature up until `OpenDocument` calls. This function returns the spans and ranges expected by `getDefinitionRange`
 (2). `ViewMetadata` that populates the document on a VS buffer.

So `GotoDefinitionFilter` uses both (1) and (2) while `PeekableItemSourceProvider` only uses (1).

You can always send a Work-In-Progress pull request. It would make it easier for discussion.

**Comment by dungpa** [comment]
Hi @remusp,

Would you mind if I use the changes in your branch and implement the remaining things as discussed here? Just want to finish off this issue.
