### ISSUE TITLE
Lightweight interface implementation does not work for members with curried arguments

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#1315]
If a member of an interface has arguments that contain multiple partially arguments, lightweight interface definitions don't work e.g. Suave's Logger interface looks like this in the heavyweight mode: -

```fsharp
member __.Log(arg1: LogLevel) (arg2: unit -> LogLine): unit = 
    failwith "Not implemented yet"
```

but the lightweight one looks like this: -
```fsharp
member __.Log(arg1 arg2) = failwith "Not implemented yet"
```
it should probably look like this instead

```fsharp
member __.Log arg1 arg2 = failwith "Not implemented yet"
```

**Comment by dungpa** [comment]
Hi Isaac,

Do you have time to look at this? I think `formatArgsUsage` function should be adjusted a bit when `hasTypeAnnotation` is false https://github.com/fsprojects/VisualFSharpPowerTools/blob/4e976909bc71f28a4d96829c1fee34c8591ebebf/src/FSharpVSPowerTools.Core/InterfaceStubGenerator.fs#L138-L160

**Comment by isaacabraham** [comment]
Yes - I'm intending to look at it this week coming, I was just extremely busy last week and wanted to put it down so it didn't get lost.

**Comment by dungpa** [comment]
That's great. Thanks.

**Comment by isaacabraham** [comment]
I think that this is the first time I've submitted a PR to any project that's worked first time :-)
