### ISSUE TITLE
Make "Generate references for F# interactive" available within C# projects

### ISSUE THREAD

**Issue by chillitom** [fsprojects/VisualFSharpPowerTools#1316]
I frequently use F# to test C# projects, would be great if the "Generate references for F# interactive" feature*  was still available within C# projects.  (Could perhaps limit to projects that include an .fsx file).

It's a shame that the C# REPL doesn't support `#I` and `__SOURCE_DIRECTORY__` otherwise this could work for both languages' REPLs.

*(which is brilliant, thank you!)

**Comment by dungpa** [comment]
@chillitom We have considered adding the feature for C# projects but unfortunately it didn't work out. The main reason is that VFPT doesn't understand C# projects enough to do assembly resolution correctly. Consequently, we can't generate assembly references in a correct order.

In the end, this feature request is in the scope of Roslyn in VS. There is a similar issue being opened there https://github.com/dotnet/roslyn/issues/669? I think there might be a chance that Roslyn team considers this for the new C# Interactive.

**Comment by dungpa** [comment]
Closing as out of scope.

**Comment by smoothdeveloper** [comment]
@dungpa, I have some code using Mono.Cecil and QuickGraph which I think works reasonably well.

I've noticed that even in my F# projects, sometimes the assembly load order is messed-up I'll try to figure out a reproduce case.

How much of confidence do we have that `projectProvider.CompilerOptions` will give all in correct order?

https://github.com/fsprojects/VisualFSharpPowerTools/blob/d64746369c27a0137f29bbd1df4daeb563e1c169/src/FSharpVSPowerTools.Logic/FsiReferenceCommand.fs#L126

**Comment by dungpa** [comment]
> How much of confidence do we have that projectProvider.CompilerOptions will give all in correct order?

It's hard to quantify. It should work as far as "Send References to F# Interactive" feature in Visual F# tools goes. If you spot any bug, it's probably present in Visual F# tools as well.
