### ISSUE TITLE
[Resolve unopened namespaces] Does not understand ModuleSuffix attribute

### ISSUE THREAD

**Issue by iainnicol** [fsprojects/VisualFSharpPowerTools#1320]
Suppose I have a module

```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Stop =
   let hammer = "time"
```
Also suppose that elsewhere I have the code fragment `hammer`, which I then ask the Visual Studio "lightbulb" to complete.  The lightbulb, powered by `ResolveUnopenedNamespaceTagger.fs` will incorrectly complete to `StopModule.hammer`.  Instead, it should complete to `Stop.hammer`.

**Comment by OkayX6** [comment]
I cannot repro...
Is it VS 2015?

![image](https://cloud.githubusercontent.com/assets/1169339/12715897/2f435e88-c8dd-11e5-9fa8-be1e9d21c77a.png)

**Comment by iainnicol** [comment]
Thanks for trying to repro.

Yes, VS2015.

Hmm, I can no longer repro either. Maybe a weird edge case as opposed to something fundamentally broken. I'll close this and pretend it didn't happen.
