### ISSUE TITLE
printf slot highlighting doesn't handle * slots correctly

### ISSUE THREAD

**Issue by latkin** [fsprojects/VisualFSharpPowerTools#1335]
Format specifiers with `*` consume 2 arguments, but the highlighting currently maps the specifier only to the first arg (and only the first arg to the specifier - the second arg gets incorrect mapping).

![printf](https://cloud.githubusercontent.com/assets/5943573/12871702/cd472d6e-cd3b-11e5-885e-e3cb9dd3aa7a.gif)

**Comment by vasily-kirichenko** [comment]
I've never heard about *. PR is very much appreciated.

**Comment by latkin** [comment]
Working on PR. Upstream FCS API needs 2 changes first
 - Report number of args associated with each specifier range
 - Start reporting `%%` as a specifier with 0 args

Will start there.  When considering `*`, one specifier can be associated with 0, 1, 2, or 3 args.
