### ISSUE TITLE
Modify auto completion behavior 

### ISSUE THREAD

**Issue by Shuun** [fsprojects/VisualFSharpPowerTools#1339]
How do I modify auto completion behavior so that auto-completion is issued automatically when writing a single character, instead of having to press ctrl-space? Also where can I modify the list returned by that auto-completion - to make the ordering in it a little smarter? Please just point me towards file/function where those things are/can be handled! :)

**Comment by vasily-kirichenko** [comment]
We don't do anything with autocompletion, all is done by Visual F# Tools. Please, create an issue here: https://github.com/Microsoft/visualfsharp/issues
