### ISSUE TITLE
Incorrect comment colouration

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#1342]
Comments like this: -

```fsharp
//==========================
// Here's a big comment
//==========================
```

seem to sometimes confuse the colorizer and all the code below is coloured as a comment. If you delete the comment and then undo, the issue goes away.

This doesn't happen all the time - I can't isolate the exact behaviour but it's definitely related to comments like the one above.

**Comment by vasily-kirichenko** [comment]
We does not colorize comments. I do see this bug time to time, only in VS 2015. Please, report the issue in VFT repository.
