### ISSUE TITLE
F# tooltip errors interfering with tooltip documentation; show both?

### ISSUE THREAD

**Issue by JasonKleban** [fsprojects/VisualFSharpPowerTools#1347]
Yes, I'm doing something wrong - that's why I need to see the documentation for this function so I can fix it or rule it out as the problem.

![documentationhidden](https://cloud.githubusercontent.com/assets/17498172/13673874/0ee2290a-e6a9-11e5-90e3-92b75a6d1589.gif)

I get stuck by this UI glitch all the time.

**Comment by smoothdeveloper** [comment]
@JasonKleban I concur but I believe tooltips and squiggles are managed entirely by Visual F# Tools itself.

Please consider opening an issue in Microsoft/visualfsharp repository instead.

**Comment by JasonKleban** [comment]
Ah ok, moved it.  https://github.com/Microsoft/visualfsharp/issues/1005
