### ISSUE TITLE
Missing reference for Microsoft Visual FSharp Editor Extensions

### ISSUE THREAD

**Issue by jterno** [fsprojects/VisualFSharpPowerTools#1354]
I have tried to install using the downloaded package and through 'Extensions and Updates' within visual studio. I have also downloaded and installed Visual F# Tools 4.0 RTM. I am able to create and run an F# project so I am not sure what else to do other than add the reference manually, which i am unsure how to do.

I am using visual studio enterprise 2015.

**Comment by dungpa** [comment]
Do you use VS 2015 RTM, Update 1 or Update 2? Could you paste the installation log which shows the failure here? Thanks.

**Comment by jterno** [comment]
[Install_Log.zip](https://github.com/fsprojects/VisualFSharpPowerTools/files/198602/Install_Log.zip)

**Comment by dungpa** [comment]
I removed the dependency, which doesn't seem to hold for VS 2015 Update 2 anymore. You can try the latest (stable) binary at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.4.0-a1603312135/artifacts

**Comment by jterno** [comment]
That worked! Thank you for your super fast and efficient help.
