### ISSUE TITLE
VFPT overrides the default background color in code editor

### ISSUE THREAD

**Issue by hmemcpy** [fsprojects/VisualFSharpPowerTools#1358]
### Description

When VFPT is enabled, it paints the background color in white, overriding the theme's color settings. This doesn't happen when VFPT is disabled.

I'm using a non-standard color scheme ([Jeff Atwood's Theme](https://blog.codinghorror.com/is-your-ide-hot-or-not/), which has the background color #F8F8F8.
When VFPT is enabled, it paints the background in white. In fact, the paining happens a second later after the code is change, so it's visible:
![animation](https://cloud.githubusercontent.com/assets/601206/14291387/100abb26-fb6c-11e5-92cd-26f4d23956b9.gif)

### Repro steps

1. Install the Jeff Atwood theme from the link above (import .vssettings) or simply change the text editor's background color to #F8F8F8 (R:248 G:248 B:248)
2. Open a .fs file with VFPT enabled.

### Expected behavior

Code background should match the VS settings.

### Actual behavior

Code background is white.

**Comment by hmemcpy** [comment]
After further investigation, this is a problem with the depth colorizer's hardcoded defaults.

**Comment by dungpa** [comment]
Do you have a suggested fix? Thanks.

**Comment by hmemcpy** [comment]
I'm looking into it... The culprit code is [fairly old one](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/DepthAdornmentManager.fs#L51). 

If a custom scheme is not found in the registry (the key location should be updated, btw), my suggestion would be to calculate the default color matrix based on the current theme's background color and another known value, perhaps one of the [VsBrushes](https://msdn.microsoft.com/ru-ru/library/microsoft.visualstudio.shell.vsbrushes.aspx).

**Comment by dungpa** [comment]
It sounds like a good idea. 

This functionality dates back 4 years before VFPT started. We adapted it a bit but never got a round to make it more idiomatic.

**Comment by dungpa** [comment]
@hmemcpy Any update :)?

**Comment by hmemcpy** [comment]
@dungpa yes! sorry for the delay :) Just sent a PR, please review.
(and please be gentle, F# n00b here :))
