### ISSUE TITLE
Incorrect colorization of mutable values

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/VisualFSharpPowerTools#1361]
### Description

Incorrect colorization of mutable values.
![image](https://cloud.githubusercontent.com/assets/1197905/14438140/31be6874-002d-11e6-977f-2d1e161ceba2.png)

### Repro steps

```fsharp
type TA (str:string, func: int -> int) =
    member val Str = str with get, set
    member val Func = func with get, set
```

### Expected behavior

`Func` should be also red

### Actual behavior

`Func` not red;)

### Related information 

![image](https://cloud.githubusercontent.com/assets/1197905/14438187/725b53ec-002d-11e6-8be4-e43ccbeb8ef4.png)

**Comment by vasily-kirichenko** [comment]
Read or real? ;)

**Comment by sergey-tihon** [comment]
:+1: Red :red_circle:

**Comment by vasily-kirichenko** [comment]
Wow. The amount of symbols for `member val Func = func with get, set` is abnormally insane. There are `Func@` and `( Func@ )` among others, some mutable, some not mutable...

**Comment by sergey-tihon** [comment]
Why `wontfix`?

**Comment by vasily-kirichenko** [comment]
It means the bug won't be fixed.
