### ISSUE TITLE
AltGr + "-" not work with update 2.4.1

### ISSUE THREAD

**Issue by umutkarakoc** [fsprojects/VisualFSharpPowerTools#1375]
### Description

AltGr + "-" not work with update 2.4.1
All other AltGr + key works

note: AltGr + "-" = "|" 
### Related information 

* Windows 10 Pro 64x
* Vs 2015 update 2
* Turkish Layout 
* No extra addon

**Comment by vasily-kirichenko** [comment]
What did `AltGr` + `-` do previously?

**Comment by umutkarakoc** [comment]
Sorry my mistake. AltGr + "-" = "|"    in turkish layout.  Alt

**Comment by vasily-kirichenko** [comment]
We don't do anything new with key bindings in 2.4.1 and touch them just a little in general. The first thing I'd check is ReSharper, it messes key binding wildly.

**Comment by umutkarakoc** [comment]
I have disabled all extensions(ReSharper vs) but not work.

**Comment by dungpa** [comment]
Do you have Visual F# Tools 4.0 installed i.e. could you be able to open fsproj files and build them inside Visual Studio?

**Comment by umutkarakoc** [comment]
I dont have any problem with build. I can do every think except write a char '|' . I unistall Power Tools and the key (altgr + '-' -> '|') is work. Then I reinstall power tools, bu not work now again

**Comment by umutkarakoc** [comment]
I disable 'Peek Definition' in options. Problem fixed.

**Comment by dungpa** [comment]
@umutkarakoc What is key binding for Peek Definition on your machine?
