### ISSUE TITLE
Can't close square brackets

### ISSUE THREAD

**Issue by aradicchi** [fsprojects/VisualFSharpPowerTools#1376]
### Description

Since 2.4.1 I can't close square brackets when editing, i.e. I can't write ']' character on editor.

### Known workarounds

Disabling the VS F# Power Tools extension.

### Related information 

* Windows 7 Pro 64bit
* 2.4.1
* Visual Studio 2015 Community (Update 1)
* F# Outlining

**Comment by dungpa** [comment]
@aradicchi Thank you for reporting the bug. 

Could you try the latest build to see if the issue has been fixed https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.0-a1605030805/artifacts?

**Comment by aradicchi** [comment]
Hi @dungpa, still having the same issue. In the meantime I switched VS to Update 2.

See the attached image to check if the installed build is correct.

![vfspowertools](https://cloud.githubusercontent.com/assets/6909443/14978545/ca6f19c4-111c-11e6-9a7a-325ebff75672.PNG)

**Comment by dungpa** [comment]
@aradicchi Is this related to the use of AltGr key?

Could you check if the problem goes away when Peek Definition is turned off in General Options dialog?

**Comment by aradicchi** [comment]
Yes, I'm using an Italian keyboard so the squared bracket is obtained via [AltGr].

By disabling Peek the problem seems to be fixed.

**Comment by dungpa** [comment]
Have you tried restarting Visual Studio and keeping Peek definition enabled?

I tried the local build and the problem went away for me after VS restart.

**Comment by aradicchi** [comment]
Yes, I tried but for me this doesn't work

**Comment by lepinay** [comment]
I'm running into the same issue but with closing curly '}' on french keyboard. I had to rollback to 2.3.0.

**Comment by embix** [comment]
I second that bug: german keyboard layout, fsharp project, tilde not working - disabling the *Peek Definition* is a nasty workaround.

**Comment by dungpa** [comment]
Hi all,

Would you mind trying this new build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.0-a1605110828/artifacts?

Now AltGr keys should work even if Peek definition is enabled. 

We selectively disable Peek definition on standalone files (not belonging to any project) by default in `F# Power Tools -> Configuration -> Misc -> Enable peek definition on standalone files`. This part of the feature is the source of the problem. That's the best thing we could do for now.

**Comment by embix** [comment]
Wow, that was fast. Works as expected. Thanks.

**Comment by aradicchi** [comment]
Thank you
