### ISSUE TITLE
Highlighting the variables breaks after a while

### ISSUE THREAD

**Issue by CodEFouR** [fsprojects/VisualFSharpPowerTools#1377]
At the beginning the highlighting works and I can see the variables are rendered in different colours. However after a while of editing, I cannot see the variable highlights - if I put the text cursor under the variable name, it's definition and references are not rendered. I have to close the file and reopen it to show the highlights. Other highlights like keywords, functions and types are not impacted. 

I have Windows 10 Pro with Visual Studio 2015 Update 2 installed.

**Comment by vasily-kirichenko** [comment]
@CodEFouR check out this build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.5.0-a1605100845/artifacts, it should fix the problem.

**Comment by dungpa** [comment]
Closing as it seems to be fixed in the related CR. Feel free to reopen the issue if it happens again.
