### ISSUE TITLE
Restore navigation bar to VFSPT

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/VisualFSharpPowerTools#1380]
### Description

https://github.com/fsprojects/VisualFSharpPowerTools/pull/1364 removed the navigation bar. This was a useful feature, and in the comment https://github.com/fsprojects/VisualFSharpPowerTools/pull/1364#issuecomment-214422511 @dsyme suggests a way forward.

### Repro steps

Feature removed in v2.4.1

### Expected behavior

Old navigation bar experience.

### Actual behavior

Feature removed in v2.4.1

### Known workarounds

none

### Related information 

v2.4.1

**Comment by vasily-kirichenko** [comment]
We are not planning to restore the old setting neither porting the navigation bar code from VFT. I suggest to enable it by changing devenv.exe.config by hand, the instructions are available here http://tomasp.net/blog/regions-navigation.aspx/

**Comment by dsyme** [comment]
Hi @vasily-kirichenko 

> We are not planning to restore the old setting neither porting the navigation bar code from VFT

Is there any specific reason for this, i.e. would you accept a PR to add this feature?

Thanks!
Don

**Comment by vasily-kirichenko** [comment]
Of course we would accept a PR :)

**Comment by dsyme** [comment]
:) thanks
