### ISSUE TITLE
Alt Gr + "+" key (square bracket) is not working in the editor

### ISSUE THREAD

**Issue by parmigianig** [fsprojects/VisualFSharpPowerTools#1391]
### Description

Key combination Alt Gr + "+" in not working (closing square bracket).

### Repro steps

Please provide the steps required to reproduce the problem

1. it is working in .cs files but not in .fs files.

2. don't know how to reproduce accurately.

### Expected behavior

editor should output "]" when pressing Alt Gr + "+"

### Actual behavior

editor outputs nothing. just sits still..

### Known workarounds

no workaround found...

### Related information 

* Windows 8
* Extension version (e.g. 2.3.0)
* Visual Studio version 2015 update 2
* Resharper but disabled. codemaid but now disabled. still the same issue...

**Comment by vasily-kirichenko** [comment]
We've fixed this bug. Please try this release https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/artifacts and tell us if the fix works for you.

**Comment by parmigianig** [comment]
Thank you @vasily-kirichenko! Perfectly working now! :)

**Comment by vasily-kirichenko** [comment]
That was not me, that was @dungpa :)

**Comment by parmigianig** [comment]
so thank you @dungpa ! and sorry for my mistake.
