### ISSUE TITLE
Outline guide lines became more obstrusive in recent release

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/VisualFSharpPowerTools#1393]
### Description

After updating from v 2.4.x to current 2.5.0 the outline feature seems to draw guidelines in a way which makes code not as readable as it used to:

![image](https://cloud.githubusercontent.com/assets/87944/16178512/afdba430-364a-11e6-8ec6-ec44b737ccb0.png)

When I disable outlining, the issue goes (but I lose outlining and guidelines)

Somehow the color seem to be picked up from my windows theme from the button face.

I tried to figure out which color setting would allow me to pick another color but weren't able to figure it out.

If you have any idea where I should look at in the codebase to try to fix that issue, please let me know.

### Known workarounds

None

### Related information 

* Windows 7 pro 64 bit
* 2.5.0
* VS 2015 Update 1

**Comment by vasily-kirichenko** [comment]
The colors are defined in the registry as described here https://lorgonblog.wordpress.com/2010/11/18/f-source-code-structural-colorizer-available/ (I've never tried it though)

**Comment by vasily-kirichenko** [comment]
It turns out there is a good "Indent Guides" VS extension, maybe it's a good idea to use it instead https://visualstudiogallery.msdn.microsoft.com/e792686d-542b-474a-8c55-630980e72c30

**Comment by smoothdeveloper** [comment]
As you pointed in chat, disabling the "Indent guides/Depth colorizer" feature in the settings fixes my problem.

I'll look at implementation of that feature if I notice anything regarding the chosen color.

Thanks a lot for your help!
