### ISSUE TITLE
Easier to use record stub generation

### ISSUE THREAD

**Issue by isaksky** [fsprojects/VisualFSharpPowerTools#1394]
Instead of this:

<img src="https://fsprojects.github.io/VisualFSharpPowerTools/img/record_stub_generation_typed_binding.gif">

What about doing something where if you type `Record.new`, then hit tab, you get that stub?

**Comment by cloudRoutine** [comment]
This feature works much better with the Lightbulb APIs in VS 2015

![recordstub](https://cloud.githubusercontent.com/assets/680051/16980286/44d24512-4e33-11e6-9e5e-580ab928c330.gif)
