### ISSUE TITLE
Organization of modules in FSharp.Editing

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/VisualFSharpPowerTools#1415]
Right now, Core project is a dump of
* top level utilitarian modules/functions
* infrastructure components (mostly related to facilitating dealing with underlying FCS)
* feature files (implementing logic of feature)

There is no separation of the files under several folders.

Should we create those folders:

* Utils
* Infrastructure
* Features

and move files under those?

**Comment by vasily-kirichenko** [comment]
Sounds great.

**Comment by cloudRoutine** [comment]
I think there should be multiple feature folders organized around functionality e.g. Navigation, Symbols, etc.

**Comment by smoothdeveloper** [comment]
@cloudRoutine I also agree with this, but I currently don't have proper overview of how to organize features (although they are organized already in FSharp.Editing.VisualStudio, that might be good enough).

**Comment by cloudRoutine** [comment]
That's the place to start from, it can be revised later if necessary
