### ISSUE TITLE
build.cmd compiles projects with F# 3.1

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1419]
Look at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.6.0-a1607121916

```
C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe
```
and an error conforming F# 3 is used:
```
...\EventHandling.fs(99,20): error FS0407: The mutable variable 'cts' is used in an invalid way. Mutable variables cannot be captured by closures. Consider eliminating this use of mutation or using a heap-allocated mutable reference cell via 'ref' and '!'.
```

**Comment by dungpa** [comment]
We should remove this part https://github.com/fsprojects/VisualFSharpPowerTools/blob/8e4b367d147456d0ecfafbca879090b241286fbb/build.fsx#L51-L54.

**Comment by vasily-kirichenko** [comment]
Yeah, just found it.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1420
