### ISSUE TITLE
Xml Documentation of VS SDK

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/VisualFSharpPowerTools#1425]
We have VS SDK assemblies in those folders : 

https://github.com/fsprojects/VisualFSharpPowerTools/tree/master/lib/vs2015

it would be convenient to add the .xml so we have documentation while editing the code.

**Comment by dungpa** [comment]
My suggestion is to move all these assemblies to NuGet packages and handle them via Paket https://www.nuget.org/profiles/VisualStudioExtensibility.

**Comment by smoothdeveloper** [comment]
Ok, I'll do a PR for this.

**Comment by smoothdeveloper** [comment]
I've been as far as having all projects to compile off the nuget packages, with all the separate version of VSSDK, although couldn't figure out the `Microsoft.TC.*` ones so those remain in the lib folder (as well as the native files).

Now the VSIX build still gives an error which I'm not able to figure out at this time.

**Comment by dungpa** [comment]
The test assemblies (Microsoft.TC.*) are no longer used. They can be removed I think.
Native assemblies might come with SourceLink NuGet package though I'm not sure. They can stay there if we can't find them anywhere.

**Comment by smoothdeveloper** [comment]
@dungpa TestUtilities project (which I assume is not really our code) doesn't compile without those. Our own VS test assembly depends on that project.

**Comment by dungpa** [comment]
You can choose to remove the classes that use these references if it's easy; otherwise, just leave them intact in lib folder.  We don't use this piece of test functionalities at all.
