### ISSUE TITLE
Functional wrappers to make VS SDK code easier to cope with

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/VisualFSharpPowerTools#1426]
I'm looking at few usage of SnapshotSpan / SnapshotPoint and it seems:

1. we don't use properly the VS API
1. we could make few F# helpers to keep API more F# idiomatic

### proper usage of VS API

in our existing code:

```fsharp
SnapshotSpan(x.Start, (SnapshotPoint (x.Snapshot,x.End.Position + num)))
```

If I'm right this is identical to:

```fsharp
SnapshotSpan(x.Start, x.End + num)
```

I think we should use the shorter instead, it also probably amounts to less allocations and require less tracking of state (passing correct ITextSnapshot, etc.)

### F# Helpers

````
VS.Snapshot.mkSpan x.Start (x.End + num)
```

Would few of those helpers keep our code more friendly to potential contributors who don't have much knowledge of VS API?

This also makes a first step toward a higher level DSL to deal with those while having 0 overhead with usage of small inline functions.

**Comment by cloudRoutine** [comment]
This is a good time to tackle this since we're reworking a large amount of the codebase and these changes can happen with the migrations.

**Comment by smoothdeveloper** [comment]
#1438 implements this
