### ISSUE TITLE
Add "breandcrumbs" bar

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1446]
Last release of IntelliJ IDEA added new "Breadcrumbs" toolbar:

![1](https://cloud.githubusercontent.com/assets/873919/16941726/99f5ab18-4d9a-11e6-8d80-215be39ee36e.gif)

If you click on a symbol on the toolbar, the cursor jumps to that symbol. 
If you click on a symbol with right mouse button, the whole entity definition is selected.
When you hover over a symbol on the toolbar, it shows its type and, for lambdas, the whole definition.

It's similar to Xamarin's navigation bar, but without ability to select other symbols with comboboxes. I'm not sure which style is better though. If we are gonna to resurrect VFT's Navigation bar, then it makes sense to rewrite it to mimic Xamarin's behavior.

**Comment by smoothdeveloper** [comment]
If each item could be a dropdown, and the first item is the list of modules/namespaces in the project, that would be killer feature :)

**Comment by vasily-kirichenko** [comment]
As I said, dropdowns makes it a different thing, you cannot click / right click on them to go-to-symbol / select definition with them.

**Comment by smoothdeveloper** [comment]
having a part with the text (breadcrumb) and a part with dropdown (the down arrow) would bring best of both worlds.

The underlying service which keeps track of hierarchy of node would be useful for other features as well, I intend to implement solution explorer tree nodes under .fs files at some point.

**Comment by cloudRoutine** [comment]
@vasily-kirichenko it's possible to make a WPF control that allows both, it doesn't have to be the kind used in the current navigation bar

**Comment by vasily-kirichenko** [comment]
OK!

**Comment by JohanLarsson** [comment]
When is this useful? For selecting code?

**Comment by vasily-kirichenko** [comment]
@JohanLarsson The main feature - instant understanding where you are in a large file, I mean in what module, type, method or function the cursor is.

**Comment by cloudRoutine** [comment]
@JohanLarsson this would be really useful, especially when working through unfamiliar source

@vasily-kirichenko  should we do the same kind of preview windows that we use for collapsed outlined regions, or should we have intellisense tooltips pop up on hover instead?

**Comment by JohanLarsson** [comment]
Wrote a [prototype](https://github.com/JohanLarsson/BreadCrumbBox) for the UI.
![animation](https://cloud.githubusercontent.com/assets/1640096/17002930/f38a7d82-4ecd-11e6-9478-69331c5a02bf.gif)

The control is an `ItemsControl` bound to a collection of nodes where each node has `Children` and a `SelectedChild`, we will need to write a viewmodel that exposes the ast and cursor position like this, probably pretty straightforward.

**Comment by vasily-kirichenko** [comment]
Could you port it to F# and make it a margin, similar to QuickInfoPanel?

**Comment by cloudRoutine** [comment]
There's no need for the nodes to be drop down menus, there's only ever one path down the AST to the cursor position

**Comment by vasily-kirichenko** [comment]
I agree. We should not mix navba rand this feature.

**Comment by JohanLarsson** [comment]
@vasily-kirichenko everything can be ported to f# given enough time ans skill :)
I'll have to figure out what a margin is, have not used the VS api much.
@cloudRoutine dropping the dropdowns will simplify things a lot. Without having used f# much I think I agree with @smoothdeveloper that they can be useful. Maybe best to start simple without them. 
About mixing features: screen space is a limited resource, if the ux can be made to make sense mixing could be a good thing.

**Comment by JohanLarsson** [comment]
![image](https://cloud.githubusercontent.com/assets/1640096/17019971/70947758-4f3f-11e6-82d2-df5cb2fdfafb.png)

@vasily-kirichenko Is ^ how you want it?

**Comment by vasily-kirichenko** [comment]
Yeah, but on gray background. Also, each _type_ of symbol should be colored differently.

**Comment by JohanLarsson** [comment]
Leftaligning it with the text is somewhat tricky, is it better than:
![image](https://cloud.githubusercontent.com/assets/1640096/17020784/d99b5c04-4f43-11e6-91e7-c9d2cd4b919b.png)
^ is simpler.
About the background: should probably be set by dynamicresource to a resourcekey to make it theme aware.

About styling content: the sky is not the limit.

**Comment by vasily-kirichenko** [comment]
It should be left aligned with text, as on the previous screenshot. 

The font should be the same as one used for code in editor.

Colors should be calm.

**Comment by JohanLarsson** [comment]
+1 about font
And I think maybe no colours at all, perhaps light up on mouseover or an underline with colour.
Making UI like a christmastree is not always awesome ux.

**Comment by smoothdeveloper** [comment]
Regarding colors / background, I believe we should use the semantic coloring used in the source code itself, modules have some color, mutable variables some color, interfaces some color etc.

**Comment by JohanLarsson** [comment]
That makes sense, maybe just use foreground on the text.

**Comment by vasily-kirichenko** [comment]
It turns out this feature is more annoying than useful.
