### ISSUE TITLE
[Rename] Does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1450]
master 

![image](https://cloud.githubusercontent.com/assets/873919/17066660/b44036c4-5050-11e6-8b9e-6840d5c19d31.png)

**Comment by dungpa** [comment]
Could you git bisect? There were a few PRs that touched XAML recently.

**Comment by smoothdeveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/87944/17068325/8d24a0ca-5050-11e6-8e6a-ad55c15654ec.png)

Confirm the same.

**Comment by cloudRoutine** [comment]
#1451 should fix this, the uri needed to be updated do properly access the resource dictionary. There was a warning for it in the xaml file, but treat warnings as errors doesn't seem to apply to xaml :expressionless:

**Comment by ReedCopsey** [comment]
@cloudroutine does that fix need to happen to any other xaml files?  I
thought the resources were shared with other UIs.

**Comment by cloudRoutine** [comment]
@ReedCopsey good call, I'd missed two. Although now I'm having this weird issue in the designer.

![](http://i.imgur.com/Sd5kvB6.png)

Last time I had visual studio open changing the uri fixed the error that was preventing it from loading. This time RenameDialog, FolderNameDialog, MoveToFolderDialog all wouldn't load initially despite working in the experimental instance, then once I clicked on the error bubble that comes up in the solution explorer when you mouse over the filename, it all worked again. :confused:

**Comment by cloudRoutine** [comment]
@ReedCopsey do you know of a way we could catch these sorts of errors at compile time over runtime?

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/VisualFSharpPowerTools/pull/1451

**Comment by ReedCopsey** [comment]
@cloudroutine I don't know of a way.  it's a problem for c# too.  ReSharper
finds it if the xaml is open, but even that's not reliable.
