### ISSUE TITLE
Although Outlining is turned off, some parts of the code appear outlined.

### ISSUE THREAD

**Issue by urbanhop** [fsprojects/VisualFSharpPowerTools#1460]
This is weird. I turned Outlining off (and disabled any other Outlining tools for F#). Still, some parts of the code, like DU cases or if-blocks, but only some and not many, appear collapsed. I toggled F# Power Tools several times on and off and am sure it is the culprit.

**Comment by dungpa** [comment]
Turning off outlining doesn't have immediate effects. After you close and reopen the files, outlining shouldn't appear anymore. I think VFPT is no-op wrt outlining after outlining is disabled. 

Is that the behaviour you observed as well?

**Comment by urbanhop** [comment]
Certainly I restarted VS between switching (and testing the wrong behavior). Outlined is switched off since weeks but I still encounter outlining. Maybe I find the time to contribute and fix this. Just thought others could add observations, hints or tips.

agreed this is minor + thx to all contributors

**Comment by cloudRoutine** [comment]
the spans get stored in the `.vs` user directory with other user specific solution data. If you delete that they should go away. I'm not sure how to clear that stuff from the VS API

**Comment by urbanhop** [comment]
bingo! thx a lot @cloudRoutine .

deleted .vs and outlines are gone. solved for me.

maybe, upon package / option loading, span-state should be deleted if outlining is turned off. leave it to the contributors to reopen in case.
