### ISSUE TITLE
"static let" breaks colorization

### ISSUE THREAD

**Issue by asik** [fsprojects/VisualFSharpPowerTools#1465]
When a "static let" is used in a class, the class name is improperly colorized.

![Proper colorizing](http://imgur.com/mEHG2dK.png)

![Bad colorizing](http://imgur.com/kEbKESz.png)

This is on 2.5.0 in Visual Studio 2015 Update 3.

**Comment by abelbraaksma** [comment]
I just tried to repro this, I can confirm it happens on my instance of VS 2015 (also Upd 3) as well.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1473

**Comment by vasily-kirichenko** [comment]
Grab 2.5.2 installer here https://github.com/fsprojects/VisualFSharpPowerTools/releases/download/2.5.2/FSharpVSPowerTools.vsix (I cannot upload it into VS gallery since it down or the like).

**Comment by vasily-kirichenko** [comment]
Finally managed to push it to VS Gallery.
