### ISSUE TITLE
Depth colorizer throws exception

### ISSUE THREAD

**Issue by Muhomorik** [fsprojects/VisualFSharpPowerTools#1466]
### Description

Editor sometimes throws exception.
![deptherror](https://cloud.githubusercontent.com/assets/11274409/17652602/67873c6a-6289-11e6-8bd0-2ebb8a11f260.png)

Log file includes this error:

<entry>
    <record>712</record>
    <time>2016/08/14 22:30:30.769</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IndexOutOfRangeException: Index was outside the bounds of the array.&#x000D;&#x000A;   at Microsoft.VisualStudio.FSharp.LanguageService.FSharpColorizer.ColorizeLine(Int32 line, Int32 _length, IntPtr _ptrLineText, Int32 lastColorState, UInt32[] attrs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.LanguageServiceClassificationTagger.ClassifyLine(Int32 lineNo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.LanguageServiceClassificationTagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
</entry>
### Repro steps

Couldn't reproduce.
### Related information

Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Visual F# 2015   00322-20000-00000-AA128
Microsoft Visual F# 2015
Visual F# Power Tools   2.5.0

**Comment by vasily-kirichenko** [comment]
Use VS 2017, where Guidelines are already implemented.
