### ISSUE TITLE
Peek Definition doesn't work in .fsx file on referenced assembly types

### ISSUE THREAD

**Issue by kflu** [fsprojects/VisualFSharpPowerTools#1467]
### Description

Peek definition (alt-F12) doesn't work in .fsx file on types or methods defined in a referenced assemblies
### Repro steps
1. Create `test.fsx` file
2. Specify Newtonsoft.Json as a nuget dependency and do `nuget install` or the like
3. type `JsonConvert.SerializeObject(1)` in `test.fsx`
4. Press alt-F12 on `SerializeObject()` method
### Expected behavior

The **metadata** of `JsonConvert.SerializeObject()` should be shown in the peek definition window.
### Actual behavior

The peek definition window only shows the same script file with cursor jumped onto the line that references the Newtonsoft.Json assembly (`#r "...Newtonsoft.Json.dll"`)

![issue](https://cloud.githubusercontent.com/assets/1031978/17719369/e63e64de-63ce-11e6-9507-019991755460.png)
### Known workarounds

None
### Related information
- Windows 10
- Extension version (e.g. 2.5.0)
- Visual Studio 2015 Enterprise Update 3 (14.0.25422.01)

**Comment by vasily-kirichenko** [comment]
The feature is now supported in VS 2017 out of the box, if there are bugs, create issues in VFT repo.
