### ISSUE TITLE
Highlight matching delimiters (braces, quotes) when pointed at with cursor

### ISSUE THREAD

**Issue by slav** [fsprojects/VisualFSharpPowerTools#1468]
### Description

Highlight matching delimiters when cursor is pointing at the delimiter. Braces are not as important in F# as in other languages, but still are used frequently (lambda functions, computation expressions, etc)

### Repro steps

Open a brace '(' and close a brace ')'.

### Expected behavior

When you move cursor to either brace, it and the matching brace should highlight.

### Actual behavior

When you point cursor at either brace there's no highlight.

### Related information 

* Visual Studio 15
* F# 4.0
* Latest Visual F# Power Tools
* Viasfora (for rainbow brackets)

**Comment by vasily-kirichenko** [comment]
this functionality is provided by Visual F# Tools, please report this bug there.
