### ISSUE TITLE
Namespace for function attribute is grayed out if attribute does not have the "Attribute" suffix

### ISSUE THREAD

**Issue by jimfoye** [fsprojects/VisualFSharpPowerTools#1470]
This is on 2.5.0. I searched prior issues but may have missed it.

See screenshots, the code is the Remoting.fs module from the Websharper (4.0 beta) Client Server template, very slightly modified.

The only symbol belonging to the WebSharper namespace is the Remote attribute on the DoSomething function. If the attribute lacks the "Attribute" suffix, then of course it's perfectly OK for the compiler, but now the namespace is grayed out. I would think that the expected behavior is that it's not.

![withsuffix](https://cloud.githubusercontent.com/assets/4249676/19326747/64f4f6e6-9091-11e6-8aa2-ead37bc55584.PNG)

![withoutsuffix](https://cloud.githubusercontent.com/assets/4249676/19326763/70abce9c-9091-11e6-88db-ec698897a0b0.PNG)

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it:
```fsharp
open System

module M =
    type MyAttribute() =
        inherit Attribute() 

open M

[<My>]
type Foo() = class end
```
`M` in `open M` is not grayed out.

I suspect `RemoteAttribute` is defined in a auto open module, not directly in `WebSharper`?

**Comment by jimfoye** [comment]
No, it's just a type in the namespace WebSharper. Source is here:

https://github.com/intellifactory/websharper/blob/f55d3abd2da64fe4b643417961b0033d4373023a/src/compiler/WebSharper.Core/Attributes.fs

If I try your code it also works fine for me.

A quick way to reproduce this is to just create a new sitelet app (I did it with the Websharper 4.0 beta VS extension, AKA "Zafir"), then open the generated "Remoting.fs" file. I'm attaching a screenshot - I have not edited this code, as did for my original post. 

![_capture](https://cloud.githubusercontent.com/assets/4249676/19838100/c0547cd4-9e95-11e6-96d9-fa71f006139c.PNG)

**Comment by vasily-kirichenko** [comment]
ok, I'll look at it (and play with WS 4 as well :) )
