### ISSUE TITLE
Visual F# Tools extension is reported by VS15 Preview 5 as slow

### ISSUE THREAD

**Issue by AmadeusW** [fsprojects/VisualFSharpPowerTools#1474]
### Description

Visual Studio 15 Preview 5 reports which extensions slow down Visual Studio. Visual F# Tools adds 5 seconds to the startup time.

We should take steps to reduce this time, for example by using _AsyncPackage_ instead of _Package_. 

![2016-10-17_16h28_21](https://cloud.githubusercontent.com/assets/1673956/19459381/502d240a-9487-11e6-8a7c-124ee919522a.png)
### Repro steps

Install Visual F# Tools in Visual Studio 15 Preview 5
Start VS a few times
Observe that at some point VS will report that the extension is slowing it down
### Expected behavior

Visual F# Tools turns on quickly, without raising alarms.
### Actual behavior

Visual F# Tools adds 5 seconds to VS load time.
### Known workarounds

None.
### Related information
- Windows 10 Update 1
- Extension version 15.4.1.0
- Visual Studio 15 Preview 5
- No other extensions installed
- Hardware: Intel i7-6700, SSD

**Comment by cloudRoutine** [comment]
@AmadeusW are there docs for the dev15 vssdk anywhere? I'd like to upgrade vfpt for dev15, but I don't know where I should be looking for guidance.

**Comment by AmadeusW** [comment]
[Here's a guide](https://msdn.microsoft.com/en-us/library/mt750288.aspx) to [AsyncPackage](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.asyncpackage.aspx).

A huge downside is that `AsyncPackage` is defined in `Microsoft.VisualStudio.Shell.14` (which comes with VS2015) and there is no way to provide a VSIX with both `AsyncPackage` for VS2015+ and `Package` for VS2013 support.

**Comment by cloudRoutine** [comment]
We already kind of do that, or at least we used to -
 * [dev13 - fsharp.editing.visualstudio](https://github.com/fsprojects/VisualFSharpPowerTools/tree/master/src/FSharp.Editing.VisualStudio)
* [dev14 - fsharp.editing.visualstudio.2015](https://github.com/fsprojects/VisualFSharpPowerTools/tree/master/src/FSharp.Editing.VisualStudio.v2015)
* [version split in manifest](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools/source.extension.vsixmanifest#L15-L18)

Everything is really in flux right now, the [restructuring of the extension to an out of process service](https://github.com/fsprojects/VisualFSharpPowerTools/issues/1406) will probably do a lot more than an asyncPackage 😜 but that'll be a long time coming and this async package is something we can do in the shorter run.

**Comment by AmadeusW** [comment]
That's a major undertaking! I'm curious how version split in manifest work. Currently we have only one `Package` type. With `AsyncPackage` there will be two package types. Will the version split in manifest be able to distinguish between packages?

**Comment by dungpa** [comment]
@AmadeusW No, it will not be able to distinguish between packages. As you said, the easiest way is to remove support for VS2013.

**Comment by kerams** [comment]
But `Visual F# Tools` is https://github.com/Microsoft/visualfsharp, not VFPT, right? I can't even install VPFT under Preview 5.

**Comment by vasily-kirichenko** [comment]
@kerams good point
@kerams VS Gallery does not allow to upload VFPT VSIX if it targets VS 15. AFAIK it must be compiled with VS 15, which adds some new metadata to it. You can set VS 15 target in VSIX properties and compile it yourself in VS 2015, then it should install into VS 15.

**Comment by vasily-kirichenko** [comment]
We are not going to support VS 2017.
