### ISSUE TITLE
[VS 15] Warning during installation

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1475]
![image](https://cloud.githubusercontent.com/assets/873919/19511498/1e26a3d6-95f0-11e6-96f0-70851f141e08.png)

**Comment by cloudRoutine** [comment]
I've been trying to figure out why this is happening now, it didn't show up during dev15 preview4, and it should be compatible based on the manifest, so maybe a dependency is behind it? Some totally deprecated part of the VSSDK?

**Comment by vasily-kirichenko** [comment]
I strongly suspect that's this warning is the reason why I've been not able to upload the new release to VS Gallery, see https://social.msdn.microsoft.com/Forums/en-US/f436998d-461d-4e4f-ae95-20a0e25395e0/is-visual-studio-gallery-down-on-uploading-extensions?forum=vsx

**Comment by vasily-kirichenko** [comment]
We are not going to support VS 2017.
