### ISSUE TITLE
Doesn't work with VS 2013 after update from 2.5.0

### ISSUE THREAD

**Issue by inosik** [fsprojects/VisualFSharpPowerTools#1483]
### Description

After I updated the extension from 2.5.0 to 2.5.6, all features stopped working. The option page in Tools > Options is visible. Disabling the other extensions didn't help. Starting Visual Studio with the `/log` switch didn't reveal anything. I also tried to install this extension on another machine with VS 2013 and I can observe the same behavior.

### Repro steps

Use this extension with VS 2013, apparently.

### Expected behavior

Everything that is enabled in the options should work.

### Actual behavior

Syntax highlighting, rename refactoring, F12 and everything else doesn't work at all.

### Known workarounds

Downgrade to 2.5.0.

### Related information 

* OS: Windows 7
* Extension version: starting with 2.5.2
* Visual Studio version: 12.0.40629.00 Update 5
* Other extensions installed in Visual Studio:
  * EditorConfig
  * Productivity Power Tools 2013
  * SubwordNavigation
  * And those that come with VS 2013

**Comment by inosik** [comment]
I've just tried to enable the "Diagnostic Mode", but I don't get any output in the output pane with 2.5.2, while 2.5.0 prints some information.

**Comment by abhiranjankumar00** [comment]
Faced same issue with above workaround.

**Comment by vasily-kirichenko** [comment]
I think we won't be supporting any version prior 2017. Actually I hope this project will be merged with Visual F# Tools soon.

**Comment by inosik** [comment]
> I think we won't be supporting any version prior 2017

That's really sad. F# tooling is pretty much non-existent in vanilla VS and I'm stuck on 2013 until my company decides to upgrade to VS 2017, or even the next one. I'm sure there are lots of people who are in a similar situation.

But if this is the way forwards, I think there should be a last *working* version of VFPT which doesn't prompt for broken updates.

**Comment by dsyme** [comment]
@inosik @vasily-kirichenko Having a stable VS2013/15 branch which an interested group of people could support over the next couple of years would be great.

**Comment by vasily-kirichenko** [comment]
OK, VS 2013 users should use 2.5.0.
