### ISSUE TITLE
Being build with VS 2017 RC, it does not work in VS 2015

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1484]
![image](https://cloud.githubusercontent.com/assets/873919/20400325/4dd31a16-ad05-11e6-8f5a-769114e6fe8b.png)

**Comment by Qudware** [comment]
How do you get it to work with VS 2017?

**Comment by vasily-kirichenko** [comment]
@Qudware grab it here https://github.com/fsprojects/VisualFSharpPowerTools/releases/tag/2.6.0

**Comment by vasily-kirichenko** [comment]
We are not gonna support VS 2017.
