### ISSUE TITLE
Feature-Request: Block selection

### ISSUE THREAD

**Issue by urbanhop** [fsprojects/VisualFSharpPowerTools#1490]
Would wish a **command that selects the current block**. That is the block the cursor is in. 
This would be in particular helpful when working on a block and sending that block frequently to Interactive. With such a command the current block could be executed in Interactive via 2 key-shortcuts: alt-blockselect + alt-bkspce .

example:

```
// ...

let inline increasing (a, b) = a > b

m.temperatures          // block begin
|> Seq.pairwise
|> Seq.map increasing   // executing cmd select-block while cursor is in this line 
|> Seq.indexed          // selects the whole block
|> print                // block end

// ...
```

see also my similar feature request in the Visual F# repo:
https://github.com/Microsoft/visualfsharp/issues/2033

**Comment by aaron-comyn** [comment]
Lovely idea, as REPL efficiency is a huge productivity matter.

Just to expound on the request: selecting the current context for the current block would also be nice.  

That is to say: if your current block is a sub function of a module it could be handy to send the entire module to FSI for recompilation.  Great work, all!

**Comment by vasily-kirichenko** [comment]
This project has being merged with Visual F# Tools. All feature requests and bug reports should be sent there.
