### ISSUE TITLE
Errors are hidden by Lint warning when Powertools is enabled

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/VisualFSharpPowerTools#1491]
### Description

If Lint issues a warning, it will top the error, showing an orange squiggly instead of a red one and the only way to find out the underlying error is by running a full build.

In this screenshot, it is not clear that _"Only functions may be marked inline"_ is actually an error and not a warning:

![image](https://cloud.githubusercontent.com/assets/16015770/21460102/0161543e-c945-11e6-931c-080013a05089.png)

Or (totally hiding the actual syntax error):

![image](https://cloud.githubusercontent.com/assets/16015770/21460127/4964d224-c945-11e6-8e0b-72906f60d587.png)

### Repro steps

You can see this in action in many ways, but this simple example is the one used in the screenshot:

```
let inline ( $# ) x = if isNull x then String.Empty else x
```

Or the following (without inline), totally hiding the error:

```
let ( $# ) x = if isNull x then String.Empty else x
```

### Expected behavior

I would expect the error to have higher precedence when hovering over and when drawing the squiggly. In fact, this is what is shown when starting Visual Studio in `/SafeMode`:

![image](https://cloud.githubusercontent.com/assets/16015770/21460172/a9cbd360-c945-11e6-93b9-a7674663a876.png)

Or:

![image](https://cloud.githubusercontent.com/assets/16015770/21460177/bcaaad44-c945-11e6-9bb0-fdeb612f57c9.png)

There is more than one thing wrong with the code, result of using a disallowed operator character, but none of these errors is shown.

### Actual behavior

The actual syntax errors are hidden. This can be seen in many situations where there is both a warning and an error on the same spot (and this happens a lot). This repro is just one of many ways to repro this.

### Known workarounds

Run the build and inspect the build log. Or disable Lint integration. But that isn't really a workaround. 

### Related information 

* Visual Studio 2015, Update 3
* Visual F# PoswerTools 2.5.6
* F# 4.0

Problem has been verified by trying to repro with extensions disabled (i.e., `/SafeMode`).

**Comment by vasily-kirichenko** [comment]
We're not gonna fix bugs for VS 2015 and we are not gonna support VS 2017. I believe there will be FsLint integration in VS 2017 (via Roslyn Analyzers rs I think).

**Comment by abelbraaksma** [comment]
@vasily-kirichenko, that's a bummer, I wasn't aware. Could we add that somewhere when people make a report, for instance in the template? It would save the developers and reporters a lot of time (and frustrations afterwards).

**Comment by vasily-kirichenko** [comment]
@abelbraaksma Sorry for wasting your time :( Basically we are moving all the functionality to Visual F# Tools, about 70% done. So consider VFPT as deprecated.

**Comment by abelbraaksma** [comment]
@vasily-kirichenko, no, not a problem, I was just surprised. I see you edited the `readme.md`, thanks!
