### ISSUE TITLE
Possible VsVim Conflict: Matching Parentheses Highlight

### ISSUE THREAD

**Issue by jeroldhaas** [fsprojects/VisualFSharpPowerTools#1494]
### Description

When using VsVim to edit a `.fs` or `.fsx` file, highlighting of matching braces doesn't work.
Disabling VsVim restores the behavior. Other file types work with matching brace / parenthesis
highlighting.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install VsVim if not already installed & activated.
2. Open `.fs` or `.fsx` file with matching parentheses / braces or write code with them therein.
3. Note missing highlight behavior. Disable VsVim (Ctrl+Shift+F12 is default toggle) and note
   restoration of behavior. Re-enable VsVim and note behavior is missing again.

### Expected behavior

Braces & parentheses (`(`, `)`, `[`, `]`, `{`, `}`) should show matching character.

### Actual behavior

Placing the caret over one of the "supported" characters yields no highlight for the matching character.

### Known workarounds

Current workaround is to disable VsVim, which removes all vim-style editing capabilities.

### Related information 

* Windows 8.1
* Visual Studio 2015 Update 3 (v14.0.25431.01)
* F# Power Tools v2.5.6
* VsVim v2.2.0.0
* Editor Enhancements 1.0.27, Elucidate 1.0.2
* Referencing issue jaredpar/VsVim#1763

**Comment by vasily-kirichenko** [comment]
1. We don't do parens highlighting in this extension
2. This project is obsolete
3. Brace highlighting is done in Visual F# Tool
4. It was completely rewritten with Roslyn VS infrastructure in VS 2017
5. Nobody is gonna fix any bugs in VS 2015 and earlier versions 

So, in short, grab VS 2017 RC and check if the bug is gone.

**Comment by jeroldhaas** [comment]
Wow. Ok, Vasily. Thanks.

**Comment by dsyme** [comment]
@vasily-kirichenko Perhaps there are some drink(s) we could buy you to make one service release for VS2015 at some point? :)  :)   Just wondering if it might help the community grow in the enterprise situations where they will no doubt be stuck on VS2015 for a while

**Comment by vasily-kirichenko** [comment]
@dsyme that's a bug in VFT, not in VFPT, as I said. We don't touch brace matching at all.

**Comment by dsyme** [comment]
> @dsyme that's a bug in VFT, not in VFPT, as I said. We don't touch brace matching at all.

Yep, understood. I just wanted to raise the prospect of a service release at some point :) Though fundamentally the convergence with VFT is awesome :)

**Comment by vasily-kirichenko** [comment]
:) The last VFPT release was long time ago and no serious bugs have been found so far. So, if there are bugs, I'll certainly fix them.

**Comment by smoothdeveloper** [comment]
@ReedCopsey was calling out to release a new version with latest FSharpXaml to avoid issues for end-users:
#1495

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper somehow I forget about it :( It's just released.
