### ISSUE TITLE
Enrich syntax highlighting with rainbow braces

### ISSUE THREAD

**Issue by financial-engineer** [fsprojects/VisualFSharpPowerTools#1497]
### New feature suggestion

Dear developers!
Please add rainbow braces to F# Power Tools syntax highlighting.
Rainbow braces are colorization of braces {}, square brackets [], square and angle brackets  [< >] for attributes, angle brackets < > for generic type parameters,  and parenthesis (), so language users visually see the corresponding matching brace. As braces are enclosed inside one another, the color changes, so the depth of the expression can be easily seen by language users.

### Expected behavior
(just like in C# code given below):
![rainbowbraces](https://cloud.githubusercontent.com/assets/1476239/22148769/b9cd99cc-df18-11e6-8292-7f1399b0aa20.png)

**Comment by vasily-kirichenko** [comment]
@financial-engineer This project is obsolete, create an issue on https://github.com/Microsoft/visualfsharp
