### ISSUE TITLE
Provide support for Visual Studio 2017

### ISSUE THREAD

**Issue by mateuszlewko** [fsprojects/VisualFSharpPowerTools#1499]
### Description

When I search for Visual F# Power Tools from within VS17 I can't find this.
Also installing directly from VSIX file doesn't work. 

### Related information 

* Windows 10
* Visual Studio 2017

**Comment by vasily-kirichenko** [comment]
There won't be version for VS 2017. Just use VS 2017 where we ported all the features.

**Comment by CmdQ** [comment]
So where can I enable the [quick info panel][qi] in VS2017 then?

[qi]: http://fsprojects.github.io/VisualFSharpPowerTools/quickinfopanel.html

**Comment by vasily-kirichenko** [comment]
@CmdQ There are no plans to add quick info panel to VS 2017. Current status of Visual F# Tools in VS 2017 is as following:

* there are no contributors working on UI features (I personally switched to Rider and have no interest in working on VFT)
* the MS team does not do anything at all, including UI features. I'm not aware of their plans to start working on anything either

My recommendation: switch to Rider or VS Code.
