### ISSUE TITLE
F12 Navigate to Source

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/VisualFSharpPowerTools#201]
Along the same lines as [Ref12](https://github.com/SLaks/Ref12) and ReSharper's Navigate to Sources from Symbol Files, it would be great to pull up the actual source code in Visual Studio instead of just the metadata when you hit F12 if the pdb is present and it is [source linked](https://github.com/ctaggart/SourceLink). [FSharp.Data 2.0 is](http://blog.codebeside.org/blog/2014/03/10/fsharp-data-2-0-0-released/) and would be a good test. I got this project cloned and building last week. I think a lot of code can be borrowed from the Rename support.

I'm interested in helping out on this, especially from the pdb and SourceLink side of things.

**Comment by dungpa** [comment]
@ctaggart I attempt a prototype with SourceLink.SymbolStore today and ran into a bug. Returned urls are incomplete e.g.

> pdb original source file path: C:\GitHub\fsharp\FSharp.Compiler.Service\src\utils\sformat.fs
it had an md5 checksum of: C0FAF9F19DF8F0AA8FA783E728A20EE6
has download url if source indexed: "https://raw.githubusercontent.com/fsharp/FSharp.Compiler.Service/ec0293a16d1efb75a8dde78f0b495759179ee9bb/%var2%"
downloaded the file to the cache 

I use your example to run inside F# Interactive using FCS 0.0.85 (see https://github.com/dungpa/PowerTools/blob/navigate-to-source/SourceLink.fsx).

You can debug the Visual Studio extension using this branch https://github.com/dungpa/PowerTools/tree/navigate-to-source; it exhibits the same issue.

Any ideas?

**Comment by ctaggart** [comment]
Awesome! So happy this is being worked on. I'll take a look after work today.

**Comment by ctaggart** [comment]
Something is wrong with the source index of `0.0.82` and newer. I'll need to troubleshoot. You can continue forward by using a different library or an older version.

```
PS C:\Projects\PowerTools> cmd /c where srctool
C:\Program Files (x86)\Windows Kits\8.0\Debuggers\x64\srcsrv\srctool.exe
srctool -x packages\FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.pdb
nuget install FSharp.Compiler.Service -version 0.0.81 -out packages
srctool -x packages\FSharp.Compiler.Service.0.0.81\lib\net45\FSharp.Compiler.Service.pdb
```

**Comment by ctaggart** [comment]
So the bug is that the new indexes end up with `%%var2%%` when it is supposed to be just %var2%.

`pdbstr -r -s:srcsrv -p:packages\FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.pdb`

`SRCSRVTRG=https://raw.githubusercontent.com/fsharp/FSharp.Compiler.Service/ec0293a16d1efb75a8dde78f0b495759179ee9bb/%%var2%%`

This line hasn't changed in a long time:
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/build.fsx#L124

Whose machine is doing the builds where the output ends up being `C:\GitHub\fsharp\FSharp.Compiler.Service`? Why not build it on AppVeyor? Which compiler version is being used?

**Comment by dungpa** [comment]
I think @dsyme is the one who has pushed recent releases. We has always built the package locally and pushed it to NuGet.

**Comment by dungpa** [comment]
@ctaggart Thanks. I will try that. 

I wonder whether BCL assemblies and FSharp.Core.dll are source indexed.  If yes, this would make the feature much more compelling. And who are responsible for doing it?

**Comment by ctaggart** [comment]
Catch-22! If you add this feature, it will be much more compelling for them to source index the pdb files. Now that Microsoft has moved a lot of .NET to GitHub, it is now possible for them to source index it all. I just logged the issue above for FSharp.Core.pdb. For all the aspnet vnext stuff, the issue is https://github.com/aspnet/Universe/issues/131. If you get this working, I'll definitely show it off and promote usage to those teams.

**Comment by dungpa** [comment]
@ctaggart It seems we can't avoid downloading pdb files from symbols servers. I know pdb files can be downloaded on demand if the debugger needs it in debugging mode. Is there any way I can download pdb files manually all at once? Or does SourceLink provide API to download certain pdb files from a given symbol server?

**Comment by ctaggart** [comment]
@dungpa .pdb files can be put in the NuGet packages like several projects are already doing. `FSharp.Compiler.Service\lib\net45\FSharp.Compiler.Service.pdb`
This avoids having to use symbol servers.

If you enable Symbol Servers in Visual Studio, it will try to find the pdb files. It is usually a slow process and I don't recommend enabling symbol servers. Do note that you must set the cache directory.
http://ctaggart.github.io/SourceLink/visualstudio.html
