### ISSUE TITLE
Make it possible to use NCrunch

### ISSUE THREAD

**Issue by forki** [fsprojects/VisualFSharpPowerTools#299]
![image](https://cloud.githubusercontent.com/assets/57396/2579122/5a5c100c-b99d-11e3-818c-15e5d149c7a0.png)

    It has been detected that this component is referencing assemblies within the build output directories of projects within this solution.  It is strongly recommended that assemblies are referenced from a directory location that is not subject to disruption from the build process.

    Directly referencing assemblies that are updated, copied or manipulated by the build of projects in this solution will create implicit build dependencies that cannot be tracked by NCrunch or MSBuild.  This can result in inconsistent build behaviour patterns and code versioning issues.  It can also cause problems when trying to execute a clean build of the solution after it is checked out of a source control system.

    The following assembly references have triggered this warning: 
    C:\Code\FSharpVSPowerTools\bin\Microsoft.VisualStudio.Editor.dll
    C:\Code\FSharpVSPowerTools\bin\Microsoft.VisualStudio.Shell.11.0.dll

**Comment by vasily-kirichenko** [comment]
@forki is it still actual for you? If it's not, I'll close it since nobody else seems to use NCrunch with VFPT.
