### ISSUE TITLE
[Coloring] Wrong C# nested types colorization

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#544]
![image](https://cloud.githubusercontent.com/assets/873919/3473472/30375276-02d8-11e4-8d90-0044b8132459.png)

`VSConstants` and `VSStd2KCmdID` should both be categorized as types.

**Comment by dungpa** [comment]
This has been fixed in FCS 1.4.0.6. Could you please check?

**Comment by vasily-kirichenko** [comment]
I confirm it's fixed.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1134
