### ISSUE TITLE
The "PowerToolsCommandsPackage" package did not load correctly

### ISSUE THREAD

**Issue by mastoj** [fsprojects/VisualFSharpPowerTools#583]
I tried to install the power tools in Visual studio 2013 with update 2. I have resharper installed and also some other plugins. After I installed the power tools I got the message "The 'PowerToolsCommandPackage' package did not load correctly", see screen shot.

![error](https://cloud.githubusercontent.com/assets/501424/3575182/f9dd744c-0b85-11e4-9e51-b2eb0a13a801.PNG)

The message from the `ActivitLog.xml`:

```
<entry>
    <record>456</record>
    <time>2014/07/14 18:34:12.275</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [PowerToolsCommandsPackage]</description>
    <guid>{F152487E-9A22-4CF9-BEE6-A8F7C77F828D}</guid>
    <hr>80131500</hr>
    <errorinfo>No exports were found that match the constraint: 
    ContractName    FSharpVSPowerTools.ClassificationColorManager
    RequiredTypeIdentity    FSharpVSPowerTools.ClassificationColorManager</errorinfo>
</entry>
<entry>
    <record>457</record>
    <time>2014/07/14 18:34:12.275</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [PowerToolsCommandsPackage]</description>
    <guid>{F152487E-9A22-4CF9-BEE6-A8F7C77F828D}</guid>
    <hr>80131500</hr>
    <errorinfo>No exports were found that match the constraint: 
    ContractName    FSharpVSPowerTools.ClassificationColorManager
    RequiredTypeIdentity    FSharpVSPowerTools.ClassificationColorManager</errorinfo>
</entry>
```

I got the same error on two different machines and can probably recreate it if needed.

**Comment by larsw** [comment]
Hi,

 Experienced the same error today with the latest release that has been released to the Visual Studio Gallery + Visual Studio 2015.

**Comment by dungpa** [comment]
@larsw Is this on Windows 10? 

I heard that some users had to reinstall the extension on Administrator mode to make it work on Windows 10. https://twitter.com/adamchester/status/634338461537832960 . Not sure why...

**Comment by larsw** [comment]
Yes, Win10 - thanks for the advice, I'll try later.
