### ISSUE TITLE
Investigate use of AstVisitorBase

### ISSUE THREAD

**Issue by OkayX6** [fsprojects/VisualFSharpPowerTools#694]
We all traverse the AST with manual pattern matching (for implement interface/record stub/union cases generation), but since the tree is huge, we often forget or misconsider the cases (cf a recent issue opened by Vasily...)

I wonder if using the AstVisitorBase object would help us treat more cases by default?
This way we would homogenize our code base with something more "robust".

https://github.com/fsharp/FSharp.Compiler.Service/blob/f3e5a7cc181e921115e91944ad17d9cc54cefb6f/src/fsharp/vs/ServiceParseTreeWalk.fs#L47

**Comment by dungpa** [comment]
I don't think we plan to do this anytime soon. Closing for now.
