### ISSUE TITLE
Migrate from FSharpx.TypeProviders.Xaml to FsXaml

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#74]
Relate to https://github.com/fsprojects/fsharpx/issues/284.

FSharpx.TypeProviders.Xaml is no longer supported. The type provider is now supported in [FsXaml](https://github.com/ReedCopsey/FsXaml) which perhaps has more idiomatic ways to work with Xaml.

It would be nice to migrate to FsXaml once its NuGet package is published.

cc @ReedCopsey

**Comment by rk540** [comment]
Hi All,
`
I am trying to use FsXaml and I get the following error :

Any Help would be appreciated.

RK

------ Build started: Project: atfgui, Configuration: Debug Any CPU ------
	C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Debug\atfgui.exe -g --debug:full --noframework --define:DEBUG --define:TRACE --doc:bin\Debug\atfgui.XML --optimize- --tailcalls- --platform:x64 -r:C:\Dev\ATF\assembly\Debug\frameworkevents.dll -r:C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.dll -r:C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll -r:C:\Dev\ATF\assembly\Debug\hostengine.dll -r:C:\Dev\ATF\assembly\Debug\mktdataservices.dll -r:C:\Dev\ATF\assembly\Debug\mktdatastructs.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" -r:C:\Dev\ATF\assembly\Debug\persistence.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationCore.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\PresentationFramework.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll" -r:C:\Dev\ATF\framework\examples\atfgui\packages\Expression.Blend.Sdk.1.0.2\lib\net45\System.Windows.Interactivity.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xaml.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" -r:C:\Dev\ATF\assembly\Debug\tradingclasses.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\WindowsBase.dll" --target:exe --warn:3 --warnaserror:76 --vserrors --validate-type-providers --LCID:1033 --utf8output --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ --sqmsessionguid:ed3396d7-c111-4f7c-91a2-bf3691c7001c "c:\temp\.NETFramework,Version=v4.5.AssemblyAttributes.fs" atfgui.fs 
FSC: error FS3031: The type provider 'C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FsXaml.Wpf.TypeProvider' which cannot be loaded or doesn't exist. Could not load file or assembly 'file:///C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
FSC: warning FS3005: Referenced assembly 'C:\Dev\ATF\tp\FsXaml\Debug\FsXaml.Wpf.TypeProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
Done building project "atfgui.fsproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
