### ISSUE TITLE
Custom syntax color settings don't stick

### ISSUE THREAD

**Issue by latkin** [fsprojects/VisualFSharpPowerTools#773]
Does anyone else experience that if you update the "fonts and colors" for VFPT stuff, the setting works great for your current session, and maybe a few more, but then goes away after a while?

As an example, I like setting Pattern cases to bold Purple.  This works fine for a while, but at some point (new session of VS, reboot, something like that) the setting slips back to default black.

I'm not totally sure this is a bug, it might be something with my environment.  Perhaps related to the cloud-roaming VS setting stuff?

**Comment by vasily-kirichenko** [comment]
So I suppose @latkin has not repro for this. I'm closing it for now.
