### ISSUE TITLE
"Not all referenced projects are in the compiler options" assert popups in Release configuration

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#790]
![image](https://cloud.githubusercontent.com/assets/873919/4732374/0ff48c74-59bb-11e4-818d-dd9d08ea16da.png)

@dungpa I believe it started to popup after you introduced `getCurrentProject`. On my solution at work this dialog appears almost every time I open a file in a project no files from which are already opened.

**Comment by dungpa** [comment]
Couldn't repro cleanly. Closing since it doesn't affect any functionality.
