### ISSUE TITLE
Source code formatting stumbles inside inactive conditional compilation #if blocks

### ISSUE THREAD

**Issue by buybackoff** [fsprojects/VisualFSharpPowerTools#845]
While exploring Hopac, I have found that in this file https://github.com/VesaKarvonen/Hopac/blob/master/Libs/Hopac/Hopac.fs calling `Ctrl + K, Ctrl + D` (with Power Tools version 1.6.1) fails with:

> Parsing failed with errors: [|tmp.fsx (1238,3)-(1238,6) Parse error Unexpected keyword 'val' in definition;... 

The line 1238 is inside inactive `#if` block. If the block was active then the syntax is invalid and the error is correct, but both F# and C# compilers ignore completely such inactive regions.

```
#if NOT_YET_IMPLEMENTED
/// Operations on condition variables.
module Cond =
  val create: Lock -> (unit -> bool) -> Job<Cond>          //This is line 1238
  val wait: Cond -> Job<unit>
  val signal: Cond -> Job<unit>
  module Now =
    val create: unit -> Cond
#endif
```

Additionally, autoformatting breaks code at the bottom of the file: https://github.com/VesaKarvonen/Hopac/blob/master/Libs/Hopac.Experimental/Alts.fs

**Comment by dungpa** [comment]
I'm closing this issue since source code formatting has been aware of project options for quite some time.

The other issue with moving directives and comments is a known issue. It has been tracked in e.g. https://github.com/dungpa/fantomas/issues/126.
