### ISSUE TITLE
[Coloring] Wrong colorization on brakepoints

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#859]
C# editor shows all the text in white on red background

![image](https://cloud.githubusercontent.com/assets/873919/5058206/6bc140a2-6cf7-11e4-908f-263814ef4ecf.png)

We colorize as usual

![image](https://cloud.githubusercontent.com/assets/873919/5058209/8933e504-6cf7-11e4-82ef-49394beb14b7.png)

and it looks rather ugly and hard to read.

**Comment by vasily-kirichenko** [comment]
This is how it looks like at the moment:

![image](https://cloud.githubusercontent.com/assets/873919/7796301/9fe99d40-02e6-11e5-9ff4-0cd40a9c1081.png)

I think this PR is the cause https://github.com/fsprojects/VisualFSharpPowerTools/pull/952

**Comment by vasily-kirichenko** [comment]
@dungpa I don't think proper coloring in VS 2012 is that important now. What about reverting that PR?

**Comment by dungpa** [comment]
Ok, please revert #952. I don't know what we can do to make it work for every case.

**Comment by dungpa** [comment]
Fixed by #982.
