### ISSUE TITLE
[Coloring] Array slicing bounds highlighted as patterns

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#860]
![image](https://cloud.githubusercontent.com/assets/873919/5058717/2db5dbcc-6d0d-11e4-8459-1a10a21aa64e.png)

**Comment by dungpa** [comment]
@vasily-kirichenko This should be fixed in FCS 0.0.87. Could you have a look?

**Comment by vasily-kirichenko** [comment]
Sure.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/VisualFSharpPowerTools/pull/954
