### ISSUE TITLE
Running out of space to add disabling options for new features

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#863]
The "General Options" dialog needs to be redesigned to accommodate more options. Does anyone have any ideas to address this issue?

**Comment by dungpa** [comment]
Marked as up-for-grabs. Hoping for a UI guru to appear and solve this :-).

**Comment by dungpa** [comment]
@xperiandri Would you mind to help with this :-)? 

The idea is to replace all checkboxes by a property grid which is scrollable when adding more options. It works similar as Productivity Power Tools' options dialog.

**Comment by xperiandri** [comment]
Would you propose to use toggle switches like they do?

Although it is somewhat harder to read property pages in general this is a good idea. If you group options into categories it is easier to find. I looked at Web Essentials options and they look pretty well

Another option is the way it is done in Debugging.

**Comment by dungpa** [comment]
A property grid with True/False would be enough I think. Productivity Power Tools' toggle switches are fancier but they can be confusing sometimes.

I agree that grouping options is very natural. We have similar approaches for formatting options at http://fsprojects.github.io/VisualFSharpPowerTools/codeformatting.html.

**Comment by xperiandri** [comment]
So, would you like me to do that?
Move from checkboxes to property grid?

I think it is worth to do a release with my layout improvement before I do that so we can compare usability.

**Comment by dungpa** [comment]
Yes, please. You can choose a way that you find the most suitable. The main goal is to be able to accommodate more options.

We bump versions very often. You can download the latest version at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/branch/master/artifacts.

**Comment by xperiandri** [comment]
But the latest release does not have my UI changes.

**Comment by dungpa** [comment]
Your UI changes have been released with v2.0.0. It would be great if you help resolve this issue. It blocks us from adding any new feature to VFPT :-).

**Comment by xperiandri** [comment]
I see
Cool
Next week

**Comment by xperiandri** [comment]
So now it might look like you asked

**Comment by xperiandri** [comment]
What is Linter? LinterEnabled property?
Category
DisplayName
Description
DefaultValue

**Comment by dungpa** [comment]
```csharp
[Category("Editor enhancements")]
[DisplayName("Linter")]
[Description("Enable or disable FSharpLint integration.")]
[DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
[DefaultValue(true)]
public bool LinterEnabled { get; set; }
```

**Comment by xperiandri** [comment]
What does this integration mean?
How F# Power Tools are related to F# Lint?

**Comment by dungpa** [comment]
They publish a NuGet package that we use to provide Lint warninhs to users.

**Comment by xperiandri** [comment]
So I wonder how can I see this

**Comment by xperiandri** [comment]
What do I have to see after I install F# Lint NuGet and enable integration in VFPT?

**Comment by dungpa** [comment]
It's not officially released yet. You can install this build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1507261204 or build it from source.

Here is a screenshot https://cloud.githubusercontent.com/assets/873919/8511262/24354f9a-2317-11e5-864c-cf9afb35fdfa.png

**Comment by xperiandri** [comment]
Will it also appear on scrollbar as annotation?

**Comment by dungpa** [comment]
The layout has been made scrollable as per https://github.com/fsprojects/VisualFSharpPowerTools/pull/1024. Further improvement as per #1062 doesn't seem worthwhile. Closing.
