### ISSUE TITLE
Find All References does not work for Record names

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#876]
If you have a record e.g. 
    type Foo = { Name : string }

and do a Find All References on the type itself, it doesn't find anything. You have to do it against a field of the record in order to find any that refer to that field. This works for creation of records but isn't great if you want to e.g. find anywhere you're simply using the record.

**Comment by dungpa** [comment]
@isaacabraham This is a reasonable suggestion. However, the cost is too high to implement. I think we aren't gonna do it anytime soon :-).

**Comment by isaacabraham** [comment]
No problems - thanks for looking into it :-)
