### ISSUE TITLE
Syntax Coloring in VS2015 Preview

### ISSUE THREAD

**Issue by mofus** [fsprojects/VisualFSharpPowerTools#887]
The syntax coloring option looks a bit wrong on VS2015 previews dark theme.
See [this screenshot](http://d.pr/i/1bl9w).

If I disable the syntax coloring it works ok in the dark theme.

**Comment by buybackoff** [comment]
Indent guide/depth colorizer in the dark theme makes all background white (v1.7 in VS 2015 preview), while syntax coloring works OK without the indent option
https://www.dropbox.com/s/s2ey3f8cnq5qbv5/VFST_white.png?dl=0

**Comment by vasily-kirichenko** [comment]
@buybackoff could you copy-paste the image right into this issue? I don't have access to dropbox.

**Comment by buybackoff** [comment]
![vfst_white](https://cloud.githubusercontent.com/assets/489852/5700957/cbcc64ce-9a5e-11e4-8ff8-de8a681ad971.png)

**Comment by dungpa** [comment]
@mofus @szymoc-a @buybackoff Thanks to Victor, I've got a clue to fix this. Could you guys check v1.7.1 whether the issue still persists https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1501121425/artifacts?

**Comment by buybackoff** [comment]
@dungpa fixed, now it works great

**Comment by szymoc-a** [comment]
Also works for me!

**Comment by dungpa** [comment]
Thanks guys.

**Comment by tgjones** [comment]
In case anyone else finds this issue hoping to learn where VS2015 now stores the current theme: I used Process Monitor to look for it. As of 2015 RC (I guess it may change in RTM), it is here:

```
HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\ApplicationPrivateSettings\Microsoft\VisualStudio\ColorTheme
```

and the format of the string value is harder to read programmatically than it used to be, although still possible:

```
0*System.String*1ded0138-47ce-435e-84ef-9ec1f439b749
```

It would be great if there was a public API to access this value, but I haven't been able to find one.

**Comment by dungpa** [comment]
@tgjones Thanks for the tip. I used it in #1058 to make theme detection more robust.

**Comment by tanathos** [comment]
@tgjones I'm successfully using the VSRegistry class from Microsoft.VisualStudio.Shell, like this: 
 
```
VSRegistry.RegistryRoot(Microsoft.VisualStudio.Shell.Interop.__VsLocalRegistryType.RegType_UserSettings).OpenSubKey("ApplicationPrivateSettings").OpenSubKey("Microsoft").OpenSubKey("VisualStudio").GetValue("ColorTheme", "de3dbbcd-f642-433c-8353-8f1df4370aba", Microsoft.Win32.RegistryValueOptions.DoNotExpandEnvironmentNames)
```

**Comment by tgjones** [comment]
@tanathos That removes the hardcoded version number - i.e. `HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0` - which is nice, but you still need to split the string, in VS2015, to get to the GUID, as far as I can see.

**Comment by tanathos** [comment]
@tgjones yeah, the manual parsing of the value is still needed
