### ISSUE TITLE
Is it possible to implement add references extension from Tao Liu?

### ISSUE THREAD

**Issue by halcwb** [fsprojects/VisualFSharpPowerTools#897]
I am using this tool (https://visualstudiogallery.msdn.microsoft.com/6d40737b-9a08-466a-9316-e6371c81a14a) from Tao Liu in VS2012. I know that in VS2013 you can right click and references are loaded in the FSI. But it does not create the Scripts folder with script files that contain the references. That works much nicer, as you can then load the 'add reference script' file at the top of your own script file.
Any change that this will be added to the power tools?

**Comment by halcwb** [comment]
I am now using this excellent feature. At first I did not understand that you had to add your script files to the Script folder (unlike the original tool), due to the fact that you use relative paths. But I do think that this setup is nicer, as you now separate source code with script code. So I came up with the following setup:

![scriptssetup](https://cloud.githubusercontent.com/assets/683631/5597548/7a77d494-92a4-11e4-9035-427d167008d4.png)

However, maybe this should be mentioned in the user guides? The fact that you cannot use the load scripts from the root folder?

**Comment by dungpa** [comment]
Thanks. The original doc is at https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/docs/content/generatereferences.fsx, which generates the html version at http://fsprojects.github.io/VisualFSharpPowerTools/generatereferences.html. Please feel free to send a pull request if you would like to add more information.
