### ISSUE TITLE
Ctrl + . vanishes on the first attempt

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#898]
When you ctrl + . to get the smart tag helper up (e.g. open namespace), the first time you click it on a particularly symbol, the tag immediately vanishes. You need to then hit ctrl + . again to get it to stay.

**Comment by vasily-kirichenko** [comment]
Nobody is going to investigate it.

**Comment by isaacabraham** [comment]
Seems to be fine in VS2015 anyway.

**Comment by vasily-kirichenko** [comment]
@isaacabraham great :)
