### ISSUE TITLE
Syntax coloring problem using VS2013 Dark Theme

### ISSUE THREAD

**Issue by halcwb** [fsprojects/VisualFSharpPowerTools#910]
Using syntax coloring in VS2013 dark theme, methods and module functions are coloured black, so not quite visible. See attached image:

![syntaxcoloring](https://cloud.githubusercontent.com/assets/683631/5592844/656d16a8-91e7-11e4-9894-e4d0a153a6d7.png)

**Comment by vasily-kirichenko** [comment]
Are you able to set proper colors in this dialog? 

![image](https://cloud.githubusercontent.com/assets/873919/5592978/0b8cfa24-91fe-11e4-9fd5-7e25d972dee9.png)

**Comment by dungpa** [comment]
What VS updates do you have in your installation?

Not sure why this happens, but you can fix this by setting appropriate colors for "F# Functions / Methods" Display item.

**Comment by halcwb** [comment]
I'll do that thanks. When it remains a problem I will come back to that.
