### ISSUE TITLE
Formatting selection goes to bottom of file

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#915]
If you highlight a section of code and hit CTRL + K, CTRL + F then the editor moves to the bottom of the code file, even if you've modified some code at the top of the file. I would expect the code window to remain where it was before.

**Comment by dungpa** [comment]
@isaacabraham Any update on an example repro?

**Comment by isaacabraham** [comment]
Tried again now - can't repro on the code I have here. Happy to close this until I can get a repro for you.
