### ISSUE TITLE
Format Document removes [<ParamArray>] attribute

### ISSUE THREAD

**Issue by cmendible** [fsprojects/VisualFSharpPowerTools#918]
If you write this simple type:

`type ILogger = 
    abstract DebugFormat : provider:IFormatProvider * format:String * [<ParamArray>]args:Object [] -> unit`

And format the document the `[<ParamArray>]` attribute is removed, which is not the expected behavior.

**Comment by dungpa** [comment]
Thanks for reporting. I'll have a look.
