### ISSUE TITLE
[Generate references] It should respect order of #r's in a user-modified load-references.fsx

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#920]
Sometimes order in which assemblies are referenced matters, for example the following auto-generated script does not work:
```fsharp
// Warning: generated file; your changes could be lost when a new file is generated. 
#r @"..\..\..\Libs\Hopac\Hopac.dll"
#r @"..\..\..\Libs\Hopac\Hopac.Core.dll"
#r @"..\..\..\Libs\Hopac\Hopac.Extra.dll"
#r @"..\..\..\Libs\Hopac\Hopac.Platform.dll"
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Numerics.dll"
```
```
Script.fsx(9,10): error FS0074: The type referenced through 'Hopac.Ch`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'Hopac.Core'.
```
If I manually swap `Hopac.dll` and `Hopac.Core.dll`, everything becomes ok (the same issue exists with `FParsec` and `FParsec.Core`).
The problem is that the file is re-generated on each build and the ordering is reset.

**Comment by dungpa** [comment]
What's your suggestion?

Should we remove regeneration upon each build and leave the rest as is? I don't think `References` has any kind of ordering that we can capture.

**Comment by vasily-kirichenko** [comment]
1. Read the existing file keeping lines ordering.
2. Generate new file content in memory from scratch.
3. Remove obsolete lines from (1).
4. Append lines which are not in (1) but are in (2) to the end of (1).
5. Write new content.

**Comment by dungpa** [comment]
What are obsolete lines from (1)? As I understand, these lines are in (2) but have a different order there. If (1) has new contents (that users may insert), they should go to the end result also.

So we differentiate two lists and do a simple merge of their contents. Feel free to work on this, you probably understand it better than I do.

**Comment by vasily-kirichenko** [comment]
OK, I'll do this.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/VisualFSharpPowerTools/pull/921
