### ISSUE TITLE
Install error on Visual Studio 2015 CTP 5

### ISSUE THREAD

**Issue by frankhale** [fsprojects/VisualFSharpPowerTools#923]
I just installed Visual Studio CTP 5 today and went to install Visual F# Power Tools but get the following error. FWIW, I have Visual Studio 2013 installed as well along with F# Power Tools. I've got all of the .NET versions installed so I'm not sure why I get this message.

![visual_fsharp_powertools_error_vs2015ctp5](https://cloud.githubusercontent.com/assets/190154/5784078/f0d642e0-9d96-11e4-8d81-e064de20dcb6.png)

**Comment by dungpa** [comment]
@frankhale Could you check whether v1.7.2 fixes the installation issue https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1501172312/artifacts? Thanks.

**Comment by frankhale** [comment]
I will give it a try. Thank you!

**Comment by frankhale** [comment]
This did indeed work. Thank you!
