### ISSUE TITLE
Fonts & Colours does not show up on VS2015

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#925]
Using CTP5 on VS2015, I'm not seeing any F#-specific tokens in the Fonts and Colors options.

**Comment by vasily-kirichenko** [comment]
Have it been fixed with the latest VS CTP?

**Comment by dungpa** [comment]
It's no longer a problem for me in VS CTP 5. But it seems to appear for Isaac in the same VS version. Weird indeed.

**Comment by vlaci** [comment]
I've noticed the following behavior: If I reset my VS settings to default in `Tools -> Import and Export Settings...` menu, syntax highlight works fine. But if I change the color scheme via importing a theme (in my case it was http://studiostyl.es/schemes/coding-horror-2010) F# specifgic syntax coloring is gone. Given that VS imports setting from MS account it is very likely that a customization from a previous version affects the syntax highligting in this case too.
I am using the very same them in VS 2013 without problem.

**Comment by vlaci** [comment]
I tracked down the problem: if I change the `Identifier` color in VS settingsto anything other than `Default` or `Automatic`, the syntax highlight of types, modules, etc is gone.

**Comment by isaacabraham** [comment]
OK, I've got 2015 CTP 6 and VFPT 1.7.3 and the problem is fixed now. The only issue I had was that a load of colourings e.g. functions etc. had been set to black-on-black. Now that the elements were available in Fonts and Colors I was able to manually fix them.
