### ISSUE TITLE
Unable to install: Missing .NET Framework

### ISSUE THREAD

**Issue by Ravadre** [fsprojects/VisualFSharpPowerTools#927]
Hello,

 I receive an error while trying to install Visual F# Power Tools 1.7.0 (both from inside VS and from *.vsix from Visual Gallery. Error message: 

> The extension 'Visual F# Power Tools' required a version of the .NE Framework that is not installed

Installation log: [here](https://onedrive.live.com/redir?resid=6C6794F26C0EAC13!2881&authkey=!AKo_sjuR1fNffCM&ithint=file%2clog)

My setup on this machine is a bit different than normal one, as I have Windows 8.1 and VS 2015 CTP5, however, I did remove Visual Studio 2013 Professional I had installed before (So 2015 is the only one installed). Windows claims that I have .Net framework 4.5, 4.5.2 and 4.6 (CTP) and I can't install 4.5 as it's "part of the system". I assume, from the log, that having .Net 4.5 should be ok?

Is it a known issue and is there a workaround for it?

**Comment by dungpa** [comment]
It's a dup of #923.

I think this v1.7.2 https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1501172312/artifacts should fix the issue.

**Comment by Ravadre** [comment]
Hi,

sorry, I don't know how I missed that issue. And it does fix the issue. Thank you.

**Comment by dungpa** [comment]
No problem. Glad that it works. Let us know if you have any problems with VS 2015.
