### ISSUE TITLE
[Formatting] Add a user setting to customize indent size

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#928]
I tend to use two-space indent but Formatting always makes it four-space.

**Comment by dungpa** [comment]
The option is available at "Tools --> Options --> Text Editor --> F# --> Tabs" (looking for "Indent size" option). It is implemented that way to be consistent with the F# editor.

**Comment by vasily-kirichenko** [comment]
Oh, great! Thanks. Maybe it's worth to mention this in the docs?

**Comment by dungpa** [comment]
It is in the last sentence at http://fsprojects.github.io/VisualFSharpPowerTools/codeformatting.html, but probably not in a good formulation

**Comment by vasily-kirichenko** [comment]
Sorry :crying_cat_face:
