### ISSUE TITLE
[Coloring] Self reference variable gets MutableVar category

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#930]
![image](https://cloud.githubusercontent.com/assets/873919/6163456/aa6d4b6a-b2a3-11e4-9d12-979ed9b17ec6.png)

I'm not sure this is a bug. What do you think, guys?

**Comment by dungpa** [comment]
I understand it as a mutable variable having scope of the whole class. Seem fine to me.

**Comment by vasily-kirichenko** [comment]
But actually it is not mutable:

![image](https://cloud.githubusercontent.com/assets/873919/6165121/7238b85c-b2b6-11e4-8d80-20a17842bea4.png)

**Comment by dungpa** [comment]
It's a binding arisen from a pattern; I don't think you can assign it in any context.

I understand `self` in

    do self.DoSomething()

as something being mutated inside it.

It is treated somewhat specially by the compiler. It's also fine if you would like to filter it out.

**Comment by vasily-kirichenko** [comment]
If it makes any sense, then leave it as is.
