### ISSUE TITLE
[Coloring] Single case DU is not got Patterns category if the leading | is omitted 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#934]
![image](https://cloud.githubusercontent.com/assets/873919/6234588/11f06824-b6ed-11e4-86d5-d060e19caac0.png)

![image](https://cloud.githubusercontent.com/assets/873919/6234602/29427fbc-b6ed-11e4-8fbe-9962637f0d42.png)

**Comment by dungpa** [comment]
Fixed by #940.
