### ISSUE TITLE
Feature Request - unused variables\ functions

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#938]
It would be cool if it is possible to grey out unused variables and functions, I think the function grey out can be done easily, as the support for 'find all references' is there, so it should be an extension ontop of that, i would suggest that it requires a hotkey to trigger so it does not slow down normal text processing.

**Comment by vasily-kirichenko** [comment]
Like this http://fsprojects.github.io/VisualFSharpPowerTools/syntaxcoloring.html#Graying-out-unused-declarations ?

**Comment by xenocons** [comment]
yes like that but perhaps at the function level and variables inside bindings? for example imagine function f that is not used anywhere in your code base, it'd be neat if you could know this without hunting through stuff, or will this cause more issues than the benefits it adds?

**Comment by xenocons** [comment]
FYI, adding warnon:1182 into the project option helps somewhat with un-used variable warnings.

**Comment by vasily-kirichenko** [comment]
Currently we highlight (in gray) unused private and internal: module/class let bindings, class methods, record fields, DU cases, local let bindings and unused open declarations (maybe some other categories). Doing the same solution-wide is so expensive (we would have to parse and check all projects which references the current one), that we intentionally cut it from the beginning.

**Comment by xenocons** [comment]
hmmm, I guess for some reason even though I have the 'grey out' box ticked in the F# Power options, it does not do this? is there some combinative setting that needs also to be selected (I have some stuff disabled). I know powertools is working as I see the depth colorizer 

![image](https://cloud.githubusercontent.com/assets/3858449/6401702/59c8b6cc-be56-11e4-9db4-e85d7225590d.png)

**Comment by dungpa** [comment]
@xenocons You need to enable Syntax Coloring to see those `greyed out` values/bindings.

**Comment by xenocons** [comment]
aha! thank you!!
