### ISSUE TITLE
[Coloring] Printf formatters and escaped symbols are not colored in VS 2015

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#942]
![image](https://cloud.githubusercontent.com/assets/873919/6457709/9a2f2656-c18a-11e4-850d-9376ea4f6b47.png)

![image](https://cloud.githubusercontent.com/assets/873919/6457714/b92d8f5c-c18a-11e4-81a4-798d98276374.png)

**Comment by vasily-kirichenko** [comment]
CTP 6 crashes on startup and is generally not usable. Defer fixing this bug until it becomes stable enough.

**Comment by dungpa** [comment]
@jaredpar Do you know if it is a known bug of VS 2015? 

We override ordering to show escaped-character tags on top of string tags (see https://github.com/fsprojects/VisualFSharpPowerTools/blob/ec7c43525f5bbeb9e1c0f223d5fc70179c7044c4/src/FSharpVSPowerTools/SyntaxConstructClassifierProvider.cs#L390). It works for VS 2013 but hasn't worked for VS 2015 CTP. Any ideas to fix this?

**Comment by jasonmalinowski** [comment]
Looking at your `FSharpEscapedFormat` definition that @dungpa referenced, I don't see any indication that the classification types will order correctly. The editor picks the color to use based upon the priorities specified in the Order attribute, with the highest priority ultimately "winning". Looking at the relative orderings, you order before "Default", and NaturalLanguage defines itself after Default, and String comes after NaturalLanguage. So I honestly can't say how it ever would have worked in VS2013.

Have you tried updating your Order to something more llke:

    [Order(After = PredefinedClassificationTypeNames.String)] 
    internal sealed class FSharpEscapedFormat : ClassificationFormatDefinition

**Comment by dungpa** [comment]
@jasonmalinowski You're absolutely right. It fixes the issue.

Is there any place to read about relative ordering by Order attribute? I find it really confusing.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1064

**Comment by jasonmalinowski** [comment]
@dungpa: if there is a good explanation of the Order attribute somewhere, I don't really know where it is. :cry:

As you're aware, multiple classifiers can tag the same span with different classifications. The editor ultimately chooses which color to show it based upon a priority system. The editor imports all of the different `ClassificationFormatDefinitions`, and then attempts to come up with a single priority order list based upon all the Before/After attributes. It internally does a topological sort to attempt to come up with a single priority list that satisfies everybody's requests. In the past there have been bad providers (I think even in the editor itself) that meant there were circularities and so the output of the topological sort might have been...interesting. And if you didn't specify anything, you could have been getting lucky anyways that you ended up in the right place.

In general, if you're doing the thing where you are trying to color atop something else, you should *always* have the thing you're overriding stated in your After. Looking at your classification formats, I suspect you *never* want to use `[Order(After = Priority.Low, Before = Priority.Default)]` anywhere.

**Comment by dungpa** [comment]
@jasonmalinowski Thanks for the explanation. It's really informative. 

Could you please comment on https://github.com/fsprojects/VisualFSharpPowerTools/issues/1053#issuecomment-126084817? I think it is related issue that requires understanding internal details for which I couldn't find anywhere.

**Comment by jasonmalinowski** [comment]
@dungpa, yep, that was next on my TODO list!

**Comment by dungpa** [comment]
Great. Thanks in advance :+1: .
