### ISSUE TITLE
Wrong full name for active pattern case in rename dialog

### ISSUE THREAD

**Issue by torbonde** [fsprojects/VisualFSharpPowerTools#943]
When renaming an active pattern case, the full name shown in the dialog is incorrect. I have attached a screenshot that shows it.

I don't know if this is a bug in VSFPT or in the F# compiler, but I don't know how to check it either.

![vsfpt rename](https://cloud.githubusercontent.com/assets/5451931/6473161/7991798e-c1ef-11e4-8e9d-fd5680f7b93e.PNG)

**Comment by dungpa** [comment]
What is wrong with that?

I read `Fo.Foo` as `Foo` active pattern case in `Fo` module.

**Comment by torbonde** [comment]
I guess I wasn't very clear. There is no `Fo` module. Had I tried renaming `Bar` the full name had read `Ba.Bar`.

**Comment by dungpa** [comment]
Thanks. It's indeed a bug here.

**Comment by vasily-kirichenko** [comment]
I must say `RenameDialog.fs` is a complete imperative mess.

**Comment by vasily-kirichenko** [comment]
It seems active patterns always has empty `DisplayName`:

![image](https://cloud.githubusercontent.com/assets/873919/6479896/c0b4890a-c25d-11e4-9a9f-85e63b804031.png)

So our logic here does not work properly

```fsharp
let location =
    if fullName.EndsWith displayName then 
        let locationLength = max 0 (fullName.Length - (displayName.Length + 1))
        fullName.Remove locationLength
    else fullName
```

Maximum we can do is to show `FullName = Bar`.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/944
