### ISSUE TITLE
navigate to source for Octokit.net not working

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/VisualFSharpPowerTools#947]
I'm testing out the latest build which has the `Navigate to Source` feature.
https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1503071249/artifacts

I created a new project with this NuGet `packages.config`:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Octokit" version="0.7.2" targetFramework="net45" />
  <package id="SourceLink.Core" version="0.5.0-ci1411242108" targetFramework="net45" />
</packages>
```

The `Library1.fs`:
```
module Test

let md5 = SourceLink.Crypto.hashMD5 "a.txt"

// https://github.com/octokit/octokit.net/
let dt = Octokit.Helpers.UnixTimestampExtensions.FromUnixTime 1425868070L
let github = Octokit.GitHubClient(Octokit.ProductHeaderValue "MyAmazingApp")
let a = github.Activity.Events.GetAll()
()
```

It correctly navigates to `hashMD5` implementation which is awesome to see!

It does not work when I try to navigate to `FromUnixTime` or `GitHubClient` constructor or `GetAll`. It doesn't seem to be working for the Octokit.net library. It is source indexed.

**Comment by dungpa** [comment]
Is there any error message being shown on the status bar? Or does VS just silently do nothing?

**Comment by ctaggart** [comment]
If the metadata option is enabled, it goes to the metadata. If the metadata option is disabled, the status bar shows: 
![image](https://cloud.githubusercontent.com/assets/80104/6560758/bf80e868-c649-11e4-8a54-61d2be0f5612.png)
I am able to start debugging and step into `FromUnixTime` so I know it is source indexed correctly.

**Comment by dungpa** [comment]
This issue is not worth fixing unless SourceLink has better support for symbols at design time.
