### ISSUE TITLE
Syntax Coloring Latency

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#958]
Hello,

I am not sure how to explain this issue, but I notice *significant* overhead when using Syntax Coloring, specifically, frequently when I am typing, the VS text editor 'freezes' input for roughly 1 to 2 seconds or so, my suspicion is that the cause is the Syntax Coloring (or something related to it) as when I disable it, then close the text editor and reopen it, the problem seems to go away.

**Comment by vasily-kirichenko** [comment]
What profiler says?

**Comment by xenocons** [comment]
Hi @vasily-kirichenko , I produced the behaviour and copied the output window:
[VFPT][Information 09:23:01 AM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.3352192
getCategoriesAndLocations, 00:00:00.3142426
GetAllUsesOfAllSymbolsInFile, 00:00:00.0194682
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.0194625
LS allSymbolsUses, 00:00:00.0155502
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0026046
ParseFileInProject, 00:00:00.0014041
LS ParseAndCheckFileInProject, 00:00:00.0012935

[VFPT][Information 09:26:29 AM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.1517972
ParseFileInProject, 00:00:00.1004051
GetAllUsesOfAllSymbolsInFile, 00:00:00.0256742
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.0256612
getCategoriesAndLocations, 00:00:00.0256038
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0212259
LS allSymbolsUses, 00:00:00.0022332
LS ParseAndCheckFileInProject, 00:00:00.0021929

I don't think these numbers represent the delay I am seeing?

**Comment by vasily-kirichenko** [comment]
You are right. 
@dungpa It seems we call FCS by `Async.StartImmediately`. I tried to switch to `Async.Start` everywhere and it was crashing constantly. We should carefully examine why `StartImmediately` was used initially and eliminate all the usages where possible.

**Comment by dungpa** [comment]
I think certain operations require to run on UI thread, but some uses of `StartImmediateSafe` are superficial. You can try to eliminate those constantly running on cursor changes first.

**Comment by dungpa** [comment]
@vasily-kirichenko What I meant is to change `StartImmediateSafe` to `StartInThreadPoolSafe`, identify some code fragments that access UI components and switch back to UI thread explicitly (see https://github.com/fsprojects/VisualFSharpPowerTools/blob/bc76dc272cb941fdbc04e2a0d203a685c5d3bc84/src/FSharpVSPowerTools.Logic/GoToDefinitionFilter.fs#L406-L451). It's a bit of pain, but it's doable if we would like to move most of the things off the UI thread.

**Comment by dungpa** [comment]
@xenocons We tried to address this issue via #975. Really appreciate if you can spend some time to test this beta build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.9.0-a1505251346/artifacts. If there is still UI freeze, please let us know. Thanks.

**Comment by xenocons** [comment]
Hi @dungpa , i have been testing with the beta build and VS2015 RC and i still get stuff like this:
```
[VFPT][Information 08:55:20 AM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:01.5645482
ParseFileInProject, 00:00:00.9148228
GetAllUsesOfAllSymbolsInFile, 00:00:00.5820789
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.5820538
LS ParseAndCheckFileInProject, 00:00:00.3055008
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.2605910
getCategoriesAndLocations, 00:00:00.0674381
LS allSymbolsUses, 00:00:00.0159509
```

Quite consistently it seems to be that 'GetAllUsesOfAllSymbolsInFile' takes the largest amount of time across all debug outputs, not uncommon to see it taking 150~400 msec

**Comment by vasily-kirichenko** [comment]
@xenocons The idea of our fix is to move heavy computations out of UI (main) thread whatever possible. `GetAllUsesOfAllSymbolsInFile`, `instance.GetAllUsesOfAllSymbolsInFile` and `ParseFileInProject` are all calls to the F# compiler wrapped as F# Compiler Service (FCS) library (NuGet package) which we use for analyzing code. We cannot make FCS faster, we only try to remove any UI freezes (which typically occur during active code editing). So, on large files parsing and checking will always take several seconds, or even a minute or two.

**Comment by xenocons** [comment]
hmm ok, what about getCategoriesAndLocations, they both seem to be the next candidates (see below, ignoring the exception which doesn't seem related to perf issues?). We might be splitting hairs here though. FYI the files I have in my project are not really what I would call large, they average about 400 LoC, and there is about 8k LoC in the solution.

```
[VFPT][Error 09:21:54 PM] Exception Message: Index and length must refer to a location within the string.
Parameter name: length
Stack Trace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at FSharpVSPowerTools.StringCategorizers.lines@89.Invoke(Int32 line)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at FSharpVSPowerTools.StringCategorizers.categorize[a](Category category, Regex regex, FSharpFunc`2 getTextLine, range r)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories@134.Invoke(range r)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories[a](FSharpOption`1 ast, FSharpFunc`2 getTextLine)
   at FSharpVSPowerTools.SourceCodeClassifier.getCategoriesAndLocations[a](SymbolUse[] allSymbolsUses, ParseAndCheckResults checkResults, LexerBase lexer, FSharpFunc`2 getTextLine, FSharpList`1 openDeclarations, FSharpOption`1 allEntities)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.spans@264-2.Invoke(Unit _arg12)
   at FSharpVSPowerTools.Profiler.Time[b](String msg, FSharpFunc`2 f)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.worker@262-31.Invoke(SymbolUse[] _arg12)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
[VFPT][Information 09:21:55 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.4116379
ParseFileInProject, 00:00:00.1758745
getCategoriesAndLocations, 00:00:00.1353445
GetAllUsesOfAllSymbolsInFile, 00:00:00.0748361
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.0748171
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0694045
LS allSymbolsUses, 00:00:00.0036427
LS ParseAndCheckFileInProject, 00:00:00.0017599

[VFPT][Information 09:22:17 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.5803634
ParseFileInProject, 00:00:00.3422934
getCategoriesAndLocations, 00:00:00.1388409
GetAllUsesOfAllSymbolsInFile, 00:00:00.0990271
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.0990028
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0604703
LS allSymbolsUses, 00:00:00.0361969
LS ParseAndCheckFileInProject, 00:00:00.0023229

[VFPT][Information 09:22:43 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.5764450
ParseFileInProject, 00:00:00.3507992
getCategoriesAndLocations, 00:00:00.1206598
GetAllUsesOfAllSymbolsInFile, 00:00:00.1047948
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.1047765
LS ParseAndCheckFileInProject, 00:00:00.0621087
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0327221
LS allSymbolsUses, 00:00:00.0099350

[VFPT][Information 09:22:50 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.2958585
ParseFileInProject, 00:00:00.1228455
getCategoriesAndLocations, 00:00:00.0959328
GetAllUsesOfAllSymbolsInFile, 00:00:00.0768881
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.0768702
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.0650581
LS allSymbolsUses, 00:00:00.0101231
LS ParseAndCheckFileInProject, 00:00:00.0016797

[VFPT][Warning 09:25:01 PM] Can't read Visual Studio themes from registry keys.
[VFPT][Information 09:25:11 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.2993082
GetAllUsesOfAllSymbolsInFile, 00:00:00.1809116
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.1808918
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.1737386
getCategoriesAndLocations, 00:00:00.0783531
ParseFileInProject, 00:00:00.0398567
LS allSymbolsUses, 00:00:00.0037438
LS ParseAndCheckFileInProject, 00:00:00.0033987

[VFPT][Information 09:25:17 PM] [SyntaxConstructClassifier] [Fast stage] 
Total = 00:00:00.7607649
ParseFileInProject, 00:00:00.3787960
GetAllUsesOfAllSymbolsInFile, 00:00:00.2833059
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.2832865
LS GetAllUsesOfAllSymbolsInFile, 00:00:00.1560695
LS ParseAndCheckFileInProject, 00:00:00.1117131
getCategoriesAndLocations, 00:00:00.0984307
LS allSymbolsUses, 00:00:00.0154943
```

**Comment by xenocons** [comment]
Another one, 'getOpenDeclarations', i have witnessed it taking a second:

```
[VFPT][Information 12:00:13 PM] [SyntaxConstructClassifier] [Slow stage] 
Total = 00:00:01.9359468
getOpenDeclarations, 00:00:00.9238624
GetAllUsesOfAllSymbolsInFile, 00:00:00.6248944
instance.GetAllUsesOfAllSymbolsInFile, 00:00:00.6248625
```
