### ISSUE TITLE
Syntax Coloring - Miscoloring

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#959]
Hello,

When I used Syntax Coloring, it seems that it miscolors variables and functions when the VS2013 Color Themes are used, I remember seeing this bug raised previously, and fixed, yet it is reoccuring, I think possibly it might be best to give the user the ability to tweak the Syntax Coloring Colors (let me know if there is already a way, it wasn't immediately obvious):

![image](https://cloud.githubusercontent.com/assets/3858449/7018396/09d2ffca-dd04-11e4-85a6-f386c150b519.png)

**Comment by vasily-kirichenko** [comment]
What colors do you expect in particular? I don't use the dark theme, so your screenshot looks ok for me.

**Comment by xenocons** [comment]
Hi Vasily,

When I use the normal VS dark theme with Syntax Coloring, it looks correct (unless I am missing something):
![image](https://cloud.githubusercontent.com/assets/3858449/7018564/61e6b09c-dd06-11e4-81d9-826f7fc6432b.png)

As you can see, the function names are nice and readable (a whiteish color). When I use the Solarized dark theme, it turns the text black, which is not suited to the dark background (it makes it hard to read, at least in my opinion). Perhaps the Syntax Coloring plugin should look at the background text editor color, and adapt a coloring strategy based on how dark the background is?

**Comment by dungpa** [comment]
You can temporarily fix this by changing colors of  "F# Functions/Methods" as per http://fsprojects.github.io/VisualFSharpPowerTools/syntaxcoloring.html#How-to-customize-colors.

**Comment by xenocons** [comment]
@dungpa aha! that is where the configuration is! Thanks ! Would you like to close this or track it as a bug/feature request?

**Comment by dungpa** [comment]
@xenocons I'm closing for now. Will try to find a better solution if anyone else complains about this.
