### ISSUE TITLE
[Coloring] old FSharp.Core.dll causes syntax coloring to stop working

### ISSUE THREAD

**Issue by toburger** [fsprojects/VisualFSharpPowerTools#960]
By accident I discovered that by having an "old" FSharp.Core.dll (4.3.0) in the same folder as the source code file the syntax coloring stops working. A recent FSharp.Core.dll (4.3.1.0) doesn't cause this problem.
I don't even claim this a bug or anything, I just wanted to mention it, because it's fairly hard to discover.

Presumably the coloring process uses the DLL found in the directory where the source code file is located and crashes (altough there is no error in the debug output).

**Comment by dungpa** [comment]
Thanks for the information.
I think this will be useful for others as well.

I wish error messages from FCS are more descriptive. Here is a related note http://fsharp.github.io/FSharp.Compiler.Service/corelib.html.

**Comment by dungpa** [comment]
I'm closing this issue. Will remember to point the users to this thread if similar problems come up.
