### ISSUE TITLE
Add keyboard shortcut for inserting / updating comment containing type signature

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#963]
Before:

```fsharp
member __.GetBases = getBasesCh
```

After:

```fsharp
// Ch<BasesType * Ch<Choice<Status, GetStatusError>>>
member __.GetBases = getBasesCh
```

**Comment by dungpa** [comment]
Feel free to do it if you want.

If we reuse `SignatureGenerator`, it will appear something like:

    // member GetBase: Ch<BasesType * Ch<Choice<Status, GetStatusError>>>

I think the information is useful in certain situations.

**Comment by dungpa** [comment]
Now that QuickInfo margin also includes type signatures, do you think this feature is necessary anymore?

**Comment by vasily-kirichenko** [comment]
You are right.
