### ISSUE TITLE
Show type of symbol under cursor in the status bar

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#964]

**Comment by dungpa** [comment]
Isn't it too intrusive to use the status bar? It is a shared UI that can be used by anyone; the information displayed there may be overriden at any time.

Other options are:

 - Popup windows as per http://vfpt.uservoice.com/forums/247560-general/suggestions/6143128-show-type-annotation-on-expression

 - Tool windows similar to F# Interactive as per http://vfpt.uservoice.com/forums/247560-general/suggestions/5737085-add-a-pane-that-constantly-shows-the-tooltip-conte

These options require more work (and some XAML skills), but probably constitute a more useful feature.

**Comment by vasily-kirichenko** [comment]
An entire tool window is too large and would waste a lot of space:

![image](https://cloud.githubusercontent.com/assets/873919/7535517/c85f9c08-f58e-11e4-9b1a-5994d2caf2e9.png)

I'd prefer an area inside the editor window, small and not sizable.

**Comment by vasily-kirichenko** [comment]
I'm going to show it in status bar. It seems VS does not use its left side. Will see how it's going.

**Comment by dungpa** [comment]
Sure, go for it.

An alternative is to build our own status bar.

An example from Viasfora:

http://viasfora.com/images/feat/devmargin-buffergraph.png

https://github.com/tomasr/viasfora/blob/67b34291909ddf327c0c97363dd887a48ded15bb/Viasfora/Margins/DevMarginVisual.xaml

**Comment by dungpa** [comment]
Addressed by #973. Closing.
