### ISSUE TITLE
Q: How were the animated gifs in the documentation created?

### ISSUE THREAD

**Issue by rpwjanzen** [fsprojects/VisualFSharpPowerTools#966]
What tools were used to make the animated gifs that are displayed in the documentation? (E.g. [Union pattern match case generation](http://fsprojects.github.io/VisualFSharpPowerTools/unionpatternmatchcasegeneration.html) )  I would like to make a few for my own documentation.
Thanks!

**Comment by OkayX6** [comment]
Hey Ryan,

I used LiceCap :)
http://www.cockos.com/licecap/
