### ISSUE TITLE
'Generate union cases' injects text to the wrong place

### ISSUE THREAD

**Issue by latkin** [fsprojects/VisualFSharpPowerTools#970]
![gencase](https://cloud.githubusercontent.com/assets/5943573/7714146/242fc42c-fe31-11e4-9126-57c47be3e9af.gif)

Not 100% repro, might be a race condition where cursor is out of sync with where VFPT thinks it is

Repro in VS 2013 and 2015

**Comment by dungpa** [comment]
@OkayX6 Do you have time to look at this bug yet?

**Comment by OkayX6** [comment]
Unfortunately not this moment :(
You can go ahead and fix it, I'll do the code review. But, I can tell you were to fix it if you need.
