### ISSUE TITLE
"Generate union cases" does not handle nested patterns

### ISSUE THREAD

**Issue by latkin** [fsprojects/VisualFSharpPowerTools#971]
```fsharp
type A = A1 | A2

type B = B1 | B2 of A

let test x =
    match x with
    | B1 -> ()
    | B2(A1 | A2) -> ()
```

Hover over `A1` or `A2` in bottom case, it will give bogus suggestion/completion:

![unioncase1](https://cloud.githubusercontent.com/assets/5943573/7715231/95e2d808-fe3a-11e4-84b2-2e3a60582c62.gif)

**Comment by OkayX6** [comment]
Aaahaha, I guess I will have to dive into the code after such a long break ;).
Interesting that nobody caught this before :).

Thanks @latkin !
