### ISSUE TITLE
[Performance] Opening a file takes too much time

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#977]
~ 2-3 seconds. It's not ok. We need to investigate what's going on and move everything to ThreadPool.

**Comment by dungpa** [comment]
Is this a standalone file or does it belong to certain project/solution?

I've got UI freezes but they happen after the file has been opened. I think VFPT only kick in when a file has been opened and it has `FSharp` content type.

**Comment by vasily-kirichenko** [comment]
I profiled opening files and got this

![image](https://cloud.githubusercontent.com/assets/873919/8267810/8baeb884-1776-11e5-91df-470c78b182a0.png)

As it's not our code, I'm closing the issue.
