### ISSUE TITLE
Expected and given type signature swapped in tooltip for forward pipe operators

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/VisualFSharpPowerTools#981]
When using forward pipe operators, Visual Studio shows the expected and given type signature in swapped (i.e. wrong) order when there are type mismatches:

Instead of 

> Type mismatch. Expecting a 
> ´string -> string -> bool´
> but given a 
> ´string -> string -> int´
> The type 'string' does not match the type 'bool' 
it shows

´´´
> Type mismatch. Expecting a 
> ´string -> string -> int´
> but given a 
> ´string -> string -> bool´
> The type 'string' does not match the type 'bool' 
´´´

Basically, the type signature are swapped on type mismatches. Expected = given and given = expected.

This makes it very confusing sometimes.

**Comment by vasily-kirichenko** [comment]
Although it's Visual F# Tool behavior, not this addin, could you provide a code snippet / screenshot showing the issue clearly?

**Comment by dungpa** [comment]
@exercitusvir This is a Visual F# Tools' issue. Feel free to open an issue at https://github.com/Microsoft/visualfsharp.
