### ISSUE TITLE
Unused markers in the scrollbar area are drawn over the arrows and not redrawn on resize

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/VisualFSharpPowerTools#985]
Unused markers are erroneously drawn over the full range of the scroll bar, including the up and down arrow:
![image](https://cloud.githubusercontent.com/assets/921395/7856316/7445d318-0528-11e5-8332-1b671218b6e0.png)

Additionally, their range is not recomputed when resizing the window, so they end up being drawn completely at the wrong place. For example this is what I got when shrinking the above window:
![image](https://cloud.githubusercontent.com/assets/921395/7856314/6e72c57c-0528-11e5-881c-b20389f2b892.png)

**Comment by dungpa** [comment]
Thanks for reporting the bug. I will have a look.
