### ISSUE TITLE
Ctrl + . doesn't work on VS2015

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/VisualFSharpPowerTools#987]
I've tried reclaiming the key in shortcuts but nothing seems to work.

**Comment by dungpa** [comment]
I remember you once said there is an alternative key binding that works. What was that key binding?

**Comment by isaacabraham** [comment]
Shift + Alt + F10

**Comment by dungpa** [comment]
Thanks.

The light bulb suggestions have got the `Ctrl + .` key binding now. Until we implement the new code path, one has to resort to `Shift + Alt + F10` then.

The new API is documented at https://msdn.microsoft.com/en-us/library/vstudio/dn903708(v=vs.140).aspx.

**Comment by isaacabraham** [comment]
What's annoying is that even though I removed the light bulb key binding, it still doesn't help.

**Comment by dungpa** [comment]
This has been fixed by #1069 and #1079.

@isaacabraham It would be great if you help us check how the light bulbs work on your scenarios: https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508110519. Thanks.

**Comment by isaacabraham** [comment]
Sure, I'll test later today

**Comment by ashtonkj** [comment]
I'll test too and let you know if I find any issues.

**Comment by dungpa** [comment]
Great. Thanks both.

**Comment by ashtonkj** [comment]
Tested on VS 2015 (in script file):

Generate Open statements - success
Generate Record Stubs - success
Generate DU Cases - success
Generate Interface Methods - success

Looks good to me so far.

**Comment by isaacabraham** [comment]
Yeah, seems to work here too! Awesome.

**Comment by vasily-kirichenko** [comment]
Thanks, guys! :)
