### ISSUE TITLE
Feature Request: shortcut to attach debugger to current Fsi.exe window

### ISSUE THREAD

**Issue by saosebastiao** [fsprojects/VisualFSharpPowerTools#988]
I would love to have a button or shortcut/command to attach the debugger to the FSI process in my active window. I guess it is fine to go through the menus most of the time, but even then there are times when I have to guess which of the few Fsi.exe processes is the one active in Visual Studio. It would be amazing to be able to do it with one click.

**Comment by vasily-kirichenko** [comment]
In VS 2015 there is a context menu "debug in fsi", which sends selected code to fsi and attaches the debugger to it. I think it's what you want.

**Comment by dungpa** [comment]
@saosebastiao We handle feature requests at http://vfpt.uservoice.com/. Please add suggestions there if you would like to. For this particular one, we are unlikely to do anything since it's available in VS 2015 out of the box.
