### ISSUE TITLE
[Quick info panel] It does not respect VS themes

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#989]
People say it's "black text on gray background" in the dark theme.

**Comment by dungpa** [comment]
It seems we haven't ported all the magics yet.

We need an equivalence of https://github.com/tomasr/viasfora/blob/8a4f492aee059d5cacd53cf9e1b6bbe4c0a5a49a/Viasfora/Util/VsColors.cs, which makes use of VS colors in the margin.

See the article at http://winterdom.com/2014/01/pretty-quickinfo-tooltips-and-vs-themes (I don't think we need any reflection, just the general mechanism).
