### ISSUE TITLE
Show errors and warnings right in the code editor

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#992]
I think this is an ideal option to show errors and warning without mouse and not stealing space (like Quick Info panel does):

![6677](https://cloud.githubusercontent.com/assets/873919/7990104/4e1df38a-0af7-11e5-806b-621b50192aac.gif)

![image](https://cloud.githubusercontent.com/assets/873919/7990306/e1f12388-0af8-11e5-9e07-aa23ced60bbc.png)

This is how Xamarin show errors for D language (I'm not sure it does the same for F# though).

**Comment by dungpa** [comment]
I think I have enough support for errors/warnings with error lists, error tips, squiggles, etc. I would prefer to display popup for type/function signatures as per http://vfpt.uservoice.com/forums/247560-general/suggestions/6143128-show-type-annotation-on-expression.

By the way, if you want to implement this, take a look at the following adornment examples:

 - https://code.msdn.microsoft.com/Intra-text-adornment-VS-9257bc99/sourcecode?fileId=115660&pathId=611924750
 - http://stackoverflow.com/questions/9282738/visual-studio-2010-sdk-how-to-place-an-adornment-next-to-xml-comment-groups
 - https://code.msdn.microsoft.com/Inline-XPS-Viewer-VS-2013-fe5a86f8/sourcecode?fileId=115658&pathId=581118782

**Comment by vasily-kirichenko** [comment]
I'm afraid I don't understand what do you mean by displaying popup for type/function signatures". Don't VFT's tooltips do it already?

**Comment by vasily-kirichenko** [comment]
Thanks for the links.

**Comment by dungpa** [comment]
By popup, I mean an adornment displayed on top of the identifier. They are turned on/off by keyboard shortcuts. They're different from tooltips in the sense that they can be left open and their contents can be copied.

**Comment by vasily-kirichenko** [comment]
Now I think I have enough type info in tooltips :)

**Comment by vasily-kirichenko** [comment]
I don't think it's a good idea anymore. I'm closing it.
