### ISSUE TITLE
[Quick info panel] Add a tooltip for the panel

### ISSUE THREAD

**Issue by dungpa** [fsprojects/VisualFSharpPowerTools#994]
When I open some files without any errors/warning, the panel is there but it displays nothing. At least we should have some tooltips on the panel so people know what it is supposed to do.

Something like "F# QuickInfo panel" would work.

**Comment by vasily-kirichenko** [comment]
I think we should return Tooltip copy. One guy on Slack asked for it.

**Comment by vasily-kirichenko** [comment]
Done in https://github.com/fsprojects/VisualFSharpPowerTools/pull/995
