### ISSUE TITLE
[Performance] Freezes VS UI for 30 seconds

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#999]
![image](https://cloud.githubusercontent.com/assets/873919/8079009/81a762fa-0f6a-11e5-865d-a6336c2c4d42.png)

=>

![image](https://cloud.githubusercontent.com/assets/873919/8078993/581dafa2-0f6a-11e5-96ea-3652b17ae768.png)

That's very strange because `Idents` is an array.

**Comment by dungpa** [comment]
Could we put thread guards somewhere to detect what shouldn't be run on UI thread? IMO, this functionality has been moved to background threads, it shouldn't freeze VS UI that long.

**Comment by vasily-kirichenko** [comment]
Another freeze caused by

![image](https://cloud.githubusercontent.com/assets/873919/8080178/e3147930-0f72-11e5-9088-ff44f1657415.png)

**Comment by vasily-kirichenko** [comment]
I'm profiling and optimizing in this PR https://github.com/fsprojects/VisualFSharpPowerTools/pull/1001, please review as I go. It's freezing like crazy in particular scenarios.

**Comment by dungpa** [comment]
Can you describe the scenarios? It would be great if I can reproduce them too.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/fsprojects/VisualFSharpPowerTools/pull/1001 and https://github.com/fsprojects/VisualFSharpPowerTools/pull/1002
